In [2]:
import requests
import pandas as pd
import pymysql
import traceback2

In [3]:
def __connect__():
    db_user = 'coin'
    db_password = 'dragonstone#123'
    db_name = 'master_data'
    db_host = 'localhost'
    return pymysql.connect(
        unix_socket=None,
        host=db_host,
        user=db_user,
        password=db_password,
        db=db_name,
        charset='latin1',
        cursorclass=pymysql.cursors.DictCursor)

def get_cursor(connection):
    if connection is None:
        connection = __connect__()
    connection.ping(reconnect=True)
    return connection.cursor()

In [3]:
cmc_symbols = pd.read_sql_query("select * from cmc_coin_metainfo", __connect__())
# dune_symbols = pd.read_sql_query("select * from dune_symbols", __connect__())
# debank_symbols = pd.read_sql_query("select * from debank_symbols3", __connect__())
# defi_symbols = pd.read_sql_query("select * from defi_symbols", __connect__())
# tt_symbols = pd.read_sql_query("select * from tt_symbols", __connect__())
# defistation_symbols = pd.read_sql_query("select * from defistation_symbols", __connect__())
# solana_symbols = pd.read_sql_query("select * from solana_symbols", __connect__())
coingecko_symbols = pd.read_sql_query("select * from coingecko_symbols", __connect__())

In [4]:
# cmc_symbols = pd.merge(cmc_symbols, dune_symbols, how='outer', left_on=['symbol', 'name'], right_on=['symbol', 'name_in_cmc'])
# cmc_symbols = pd.merge(cmc_symbols, debank_symbols, how='outer', left_on=['symbol', 'name'], right_on=['symbol', 'name_in_cmc'])
# cmc_symbols = pd.merge(cmc_symbols, defi_symbols, how='outer', left_on=['symbol', 'name'], right_on=['symbol', 'name_in_cmc'])
# cmc_symbols = pd.merge(cmc_symbols, tt_symbols, how='outer', left_on=['symbol', 'name'], right_on=['symbol', 'name_in_cmc'])
# cmc_symbols = pd.merge(cmc_symbols, defistation_symbols, how='outer', left_on=['symbol', 'name'], right_on=['symbol', 'name_in_cmc'])
# cmc_symbols = pd.merge(cmc_symbols, solana_symbols, how='outer', left_on=['symbol', 'name'], right_on=['symbol', 'name_in_cmc'])
cmc_symbols = pd.merge(cmc_symbols, coingecko_symbols, how='outer', left_on=['symbol', 'name'], right_on=['symbol', 'name_in_cmc'])

In [5]:
cmc_symbols = cmc_symbols[['cmc_id','name','current_name','symbol','name_in_coingecko']]
cmc_symbols = cmc_symbols[ cmc_symbols['name_in_coingecko'].notnull()]
cmc_symbols

      cmc_id       name current_name symbol name_in_coingecko
0        1.0    Bitcoin      Bitcoin    BTC           Bitcoin
1        2.0   Litecoin     Litecoin    LTC          Litecoin
2        3.0   Namecoin     Namecoin    NMC          Namecoin
3        4.0  Terracoin    Terracoin    TRC         Terracoin
4        5.0   Peercoin     Peercoin    PPC          Peercoin
...      ...        ...          ...    ...               ...
5495     NaN        NaN          NaN                  Zignaly
5496     NaN        NaN          NaN             Zipmex Token
5497     NaN        NaN          NaN           Zipper Network
5498     NaN        NaN          NaN                     zLOT
5499     NaN        NaN          NaN                    ZMINE

[1999 rows x 5 columns]

In [6]:
# cmc_symbols = cmc_symbols[['cmc_id','name','current_name','symbol','name_in_duneanalytics','name_in_debank','name_in_defi','name_in_tt', 'name_in_defistation', 'name_in_solana']]
# cmc_symbols = cmc_symbols[ cmc_symbols['name_in_duneanalytics'].notnull() | cmc_symbols['name_in_debank'].notnull() | cmc_symbols['name_in_defi'].notnull() | cmc_symbols['name_in_tt'].notnull() | cmc_symbols['name_in_defistation'].notnull() | cmc_symbols['name_in_solana'].notnull()]
# cmc_symbols

In [7]:
# cmc_symbols.to_csv("all_datasource_symbols_to_cmc_mapping.csv")

In [8]:
cmc_symbols = cmc_symbols.sort_values(['name'])
cmc_symbols

      cmc_id       name current_name symbol name_in_coingecko
1436  3756.0  #MetaHash    #MetaHash    MHC         #MetaHash
935   2882.0     0Chain       0Chain    ZCN            0chain
422   1896.0         0x           0x    ZRX                0x
907   2837.0  0xBitcoin    0xBitcoin  0xBTC         0xBitcoin
965   2920.0     0xcert       0xcert    ZXC            0xcert
...      ...        ...          ...    ...               ...
5495     NaN        NaN          NaN                  Zignaly
5496     NaN        NaN          NaN             Zipmex Token
5497     NaN        NaN          NaN           Zipper Network
5498     NaN        NaN          NaN                     zLOT
5499     NaN        NaN          NaN                    ZMINE

[1999 rows x 5 columns]

In [12]:
cmc_symbols.to_csv("debank_new_mappings.csv", index=False)

NameError: name 'cmc_symbols' is not defined

In [73]:
new_debank_mappings = pd.read_csv("query_result.csv")

In [69]:
new_debank_mappings['tmp'] = new_debank_mappings['name_in_coingecko']
new_debank_mappings['name_in_coingecko'] = new_debank_mappings['name_in_debank']
new_debank_mappings['name_in_debank'] = new_debank_mappings['tmp']
del new_debank_mappings['tmp']

In [65]:
new_debank_mappings = new_debank_mappings[new_debank_mappings['name_in_coingecko'].notnull()].reset_index(drop=True)

In [74]:
new_debank_mappings

,symbol,name_in_coingecko,name_in_debank
0,AMP,Amp,Amp
1,BABY,Baby Token,Babytoken
2,BASE,Base Protocol,Base Protocol
3,BSDS,Basis Dollar Share,Basis Dollar Share
4,BAG,Basis Gold,Basis Gold
5,BSGS,Basis Gold Share,BSGS
6,KFC,Chicken,Chicken
7,KFC,ChickenSwap,ChickenSwap
8,DFD,DeFiDollar,DefiDollar DAO
9,DFD,DefiDollar DAO,DefiDollar DAO
10,DEGOV,Degov,Degov
11,FLEX,FLEX Coin,Flexa
12,FXS,Frax Share,Frax Share
13,Kebab Token,KEBAB,Kebab
14,L2,Leverj Gluon,Leverj Gluon
15,LIDO,Lido DAO,LIDO
16,LUA,LuaSwap,Lua Token
17,LUA,LuaToken,LuaSwap
18,LUA,LuaToken,LuaToken
19,ONS,One Share,ONS
20,DOUGH,PieDAO DOUGH v2,PieDAO DOUGH v2
21,SAFE2,SAFE2,SAFE2
22,SAKE,SakeToken,SakeToken
23,SFI,Spice,saffron.finance
24,UNI,UNICORN Token,UNICORN Token
25,UNN,UNION Protocol Governance Token,UNION Protocol Governance Token
26,UNI,UNIVERSE Token,Universe
27,SIG,xSigma,xSigma

In [30]:
def insert_debank_coin_cmc_symbol(df):
    connection = __connect__()
    cursor = get_cursor(connection)
    for i, row in df.iterrows():
        try:
#             print([row['symbol'], row['name_in_cmc'], row['name_in_coingecko']])
            sql = f"delete from `coingecko_symbols` where symbol = '{row['symbol']}' and name_in_cmc = '{row['name_in_cmc']}' and name_in_coingecko = '{row['name_in_debank']}'"
#             cursor.execute(sql, (row['symbol'], row['name_in_cmc'], row['name_in_debank']))
            print(sql)
        except Exception:
            print(traceback2.format_exc())
    connection.commit()
    cursor.close()
    connection.close()

In [71]:
def insert_debank_coin_cmc_symbol(df):
    connection = __connect__()
    cursor = get_cursor(connection)
    for i, row in df.iterrows():
        try:
            print([row['symbol'], row['name_in_coingecko'], row['name_in_debank']])
            sql = "INSERT INTO `debank_symbols_cgk` (`symbol`, `name_in_coingecko`, `name_in_debank`) VALUES (%s, %s, %s)"
            cursor.execute(sql, (row['symbol'], row['name_in_coingecko'], row['name_in_debank']))
        except Exception:
            print(traceback2.format_exc())
    connection.commit()
    cursor.close()
    connection.close()

In [75]:
insert_debank_coin_cmc_symbol(new_debank_mappings)

['AMP', 'Amp', 'Amp']
['BABY', 'Baby Token', 'Babytoken']
['BASE', 'Base Protocol', 'Base Protocol']
['BSDS', 'Basis Dollar Share', 'Basis Dollar Share']
['BAG', 'Basis Gold', 'Basis Gold']
['BSGS', 'Basis Gold Share', 'BSGS']
['KFC', 'Chicken', 'Chicken']
['KFC', 'ChickenSwap', 'ChickenSwap']
['DFD', 'DeFiDollar', 'DefiDollar DAO']
['DFD', 'DefiDollar DAO', 'DefiDollar DAO']
Traceback (most recent call last):
  File "<ipython-input-71-c1a706e77877>", line 8, in insert_debank_coin_cmc_symbol
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'DFD-DefiDollar DAO-DefiDollar DAO' for key 'debank_symbols_cgk.PRIMARY'")

['DEGOV', 'Degov', 'Degov']
['FLEX', 'FLEX Coin', 'Flexa']
['FXS', 'Frax Share', 'Frax Share']
['Kebab Token', 'KEBAB', 'Kebab']
['L2', 'Leverj Gluon', 'Leverj Gluon']
['LIDO', 'Lido DAO', 'LIDO']
['LUA', 'LuaSwap', 'Lua Token']
['LUA', 'LuaToken', 'LuaSwap']
['LUA', 'LuaToken', 'LuaToken']
['ONS', 'One Share', 'ONS']
['DOUGH', 'PieDAO DOUGH v2', 'PieDAO DOUGH v2']
['SAFE2', 'SAFE2', 'SAFE2']
['SAKE', 'SakeToken', 'SakeToken']
['SFI', 'Spice', 'saffron.finance']
['UNI', 'UNICORN Token', 'UNICORN Token']
['UNN', 'UNION Protocol Governance Token', 'UNION Protocol Governance Token']
['UNI', 'UNIVERSE Token', 'Universe']
['SIG', 'xSigma', 'xSigma']