In [1]:
import pandas as pd
import pymysql
import numpy as np
import requests

In [2]:
def __connect__():
    db_user = 'coin'
    db_password = 'dragonstone#123'
    db_name = 'master_data'
    db_host = 'localhost'
    return pymysql.connect(
        unix_socket=None,
        host=db_host,
        user=db_user,
        password=db_password,
        db=db_name,
        charset='latin1',
        cursorclass=pymysql.cursors.DictCursor)


def get_cursor(connection):
    if connection is None:
        connection = __connect__()
    connection.ping(reconnect=True)
    return connection.cursor()

### Today's Top Defi Coins (marcketCap) under 1100

In [3]:
# Configs

# CoinMarketCap.com API Key
api_key = "a86e3326-8c8d-434e-897a-5d6becbf1f35"
top_symbols_count = 1100
read_data_from_file = True

def fetch_top_n_market_cap_symbols_(n):
    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    payload = {
        'convert':'USD',
        'aux':'cmc_rank',
        'limit':n,
        'tag':'defi'
    }
    headers = {
      'Accepts': 'application/json',
      'X-CMC_PRO_API_KEY': api_key
    }
    
    data = requests.get(url, params=payload, headers=headers).json()['data']
    return data

def parse_data(rows):
    parsed_data = []
    for data in rows:
        if data['cmc_rank'] < top_symbols_count:
            parsed_data.append([data['name'], data['symbol'],data['cmc_rank'], data['quote']['USD']['market_cap']])
    return parsed_data

data = fetch_top_n_market_cap_symbols_(top_symbols_count)
d = parse_data(data)
sybmol_rank_df = pd.DataFrame(d, columns = ['name','symbol', 'rank', 'market_cap'])
top_symbols = sybmol_rank_df['symbol'].values.tolist()

In [4]:
print(top_symbols)

['UNI', 'LINK', 'WBTC', 'LUNA', 'AAVE', 'AVAX', 'CAKE', 'DAI', 'RUNE', 'GRT', 'MKR', 'COMP', 'SNX', 'SUSHI', 'ZRX', 'FEI', 'UMA', 'YFI', 'DFI', 'BNT', 'FTM', 'RSR', 'REN', '1INCH', 'CRV', 'MDX', 'LRC', 'RENBTC', 'KNC', 'OCEAN', 'XVS', 'OGN', 'KSP', 'MIR', 'NXM', 'REP', 'DODO', 'REEF', 'SXP', 'ALPHA', 'BAKE', 'KAVA', 'WAN', 'SRM', 'NMR', 'BTS', 'BAL', 'KEEP', 'XHV', 'BADGER', 'BAND', 'AXS', 'JST', 'ORN', 'RAY', 'TRIBE', 'SCRT', 'GNO', 'POLS', 'USDN', 'COTI', 'INJ', 'RAMP', 'RLC', 'UQC', 'AMPL', 'AKRO', 'VAI', 'STRK', 'DIA', 'PERP', 'BZRX', 'SFI', 'DEGO', 'MLN', 'REQ', 'DAO', 'CHR', 'STAKE', 'DDX', 'SUSD', 'RGT', 'BEL', 'FLM', 'FRONT', 'AUCTION', 'FRM', 'SURE', 'OM', 'BEAM', 'FARM', 'PHB', 'TRB', 'VSP', 'YFII', 'OXEN', 'IDEX', 'HEGIC', 'CREAM', 'SWTH', 'UNFI', 'WING', 'DREP', 'STPT', 'SUKU', 'CVP', 'XPR', 'SWINGBY', 'ZEE', 'AST', 'FXS', 'BOR', 'PNT', 'EASY', 'DEXE', 'FSN', 'FOR', 'TRU', 'SUTER', 'AUTO', 'CORE', 'BONDLY', 'MTA', 'KP3R', 'DF', 'ANY', 'ZAP', 'POLK', 'PEAK', 'MATTER', 'CUSD', 'RBC', 'APY', 'MUSD', 'DHT', 'BOT', 'FIS', 'NEX', 'MET', 'MARK', 'OPIUM', 'EGG', 'SHROOM', 'BEPRO', 'SWRV', 'LTX', 'SWFTC', 'SOCKS', 'YF-DAI', 'XEND', 'ARMOR', 'DEC', 'STRONG', 'WHITE', 'UMB', 'PICKLE', 'APYS', 'HOT', 'MTRG', 'DOWS', 'UNISTAKE', 'YFL', 'AUC', 'HGET', 'IDLE', 'LUA', 'TKN', 'DYP', 'FIN', 'DOUGH', 'COMBO', 'HAKKA', 'SYNC', 'LDO', 'SMARTCREDIT', 'YIELD', 'NSURE']

In [5]:
len(top_symbols)

177

In [6]:
df = pd.read_sql_query("select * from g_master_data_joins order by date", __connect__())

In [7]:
original_df = df.copy()

In [8]:
df = original_df.copy()

In [9]:
df

,date,Name,Symbol,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Debank,...,Transaction GMV,Interest GMV,Price/Sale,Users 24hr Debank,Transactions Count Debank,Trading Volume Debank,Borrowing Volume Debank,Users life-to-date duneanlytics,CoinUrl,Tags
0,2020-12-21,Aave,AAVE,81.311937,9.757233e+08,2.154891e+08,1.199975e+07,1.600000e+07,1.600000e+07,1.723929e+09,...,1.190984e+06,3.366851e+08,72.158217,NaN,NaN,NaN,NaN,32549.0,https://aave.com,"defi,dao,yield-farming,three-arrows-capital-po..."
1,2020-12-21,AllianceBlock,ALBT,0.174965,0.000000e+00,7.007850e+06,0.000000e+00,1.000000e+09,1.000000e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://allianceblock.io,
2,2020-12-21,Amp,AMP,0.006596,6.361912e+07,3.698943e+05,9.645497e+09,1.200105e+09,9.239914e+10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://amptoken.org,
3,2020-12-21,Ampleforth,AMPL,0.820038,1.885767e+08,1.046414e+07,2.299609e+08,NaN,4.102788e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://ampleforth.org,"defi,rebase,arrington-xrp-capital,alameda-rese..."
4,2020-12-21,Anchor Neural World,ANW,0.105945,1.071682e+07,1.948454e+05,1.011550e+08,1.000000e+09,1.000000e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://an-va.com,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127754,2021-04-11,ZeroSwap,ZEE,2.211059,8.598739e+07,2.467450e+07,3.888968e+07,NaN,1.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://zeroswap.io,"defi,binance-smart-chain"
127755,2021-04-11,ZKSwap,ZKS,3.468607,6.848417e+08,4.762437e+07,1.974400e+08,1.000000e+09,1.000000e+09,1.113361e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://zks.org,"decentralized-exchange,amm,layer-2"
127756,2021-04-11,Zelwin,ZLW,5.859316,4.141579e+08,2.660658e+05,7.068366e+07,3.000000e+08,3.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://zelwin.com,
127757,2021-04-11,Zenon,ZNN,20.411898,1.097897e+08,1.223627e+06,5.378713e+06,NaN,6.150849e+06,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://zenon.network,mineable
127758,2021-04-11,Zynecoin,ZYN,0.555831,1.230547e+07,2.915718e+05,2.213888e+07,NaN,9.255612e+07,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://zynecoin.io,mineable

### filtering only defi tagged coins

In [10]:
df = df[df['Symbol'].isin(top_symbols)]
df = df.reset_index()
del df['index']

In [11]:
df

,date,Name,Symbol,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Debank,...,Transaction GMV,Interest GMV,Price/Sale,Users 24hr Debank,Transactions Count Debank,Trading Volume Debank,Borrowing Volume Debank,Users life-to-date duneanlytics,CoinUrl,Tags
0,2020-12-21,Aave,AAVE,81.311937,9.757233e+08,2.154891e+08,1.199975e+07,16000000.0,1.600000e+07,1.723929e+09,...,1.190984e+06,3.366851e+08,72.158217,NaN,NaN,NaN,NaN,32549.0,https://aave.com,"defi,dao,yield-farming,three-arrows-capital-po..."
1,2020-12-21,Ampleforth,AMPL,0.820038,1.885767e+08,1.046414e+07,2.299609e+08,NaN,4.102788e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://ampleforth.org,"defi,rebase,arrington-xrp-capital,alameda-rese..."
2,2020-12-21,Anyswap,ANY,0.198054,2.757083e+06,1.703378e+06,1.392088e+07,100000000.0,1.000000e+08,4.999804e+05,...,NaN,NaN,NaN,12.0,22.0,12187.952376,NaN,NaN,https://anyswap.exchange,"decentralized-exchange,defi,amm,binance-smart-..."
3,2020-12-21,APY.Finance,APY,0.232858,2.661404e+06,2.651785e+05,1.142932e+07,NaN,1.000000e+08,9.500688e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://apy.finance,"defi,yield-farming,yield-aggregator,alameda-re..."
4,2020-12-21,Band Protocol,BAND,6.201058,1.270847e+08,7.327053e+07,2.049403e+07,NaN,1.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://bandprotocol.com,"cosmos-ecosystem,defi,oracles,binance-chain,bi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18169,2021-04-11,yearn.finance,YFI,45127.296833,1.653236e+09,3.277292e+08,3.663494e+04,36666.0,3.666600e+04,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://yearn.finance,"defi,yield-farming,yield-aggregator,yearn-part..."
18170,2021-04-11,DFI.Money,YFII,2997.790960,1.157027e+08,7.943857e+07,3.859600e+04,39375.0,3.937500e+04,3.208410e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://dfi.money,"defi,dao,yield-farming,binance-chain,yield-agg..."
18171,2021-04-11,YF Link,YFL,303.541197,1.563320e+07,4.852106e+05,5.150274e+04,52000.0,5.200000e+04,5.036109e+06,...,NaN,NaN,NaN,17.0,30.0,43631.672764,NaN,NaN,https://yflink.io,"defi,dao,yield-farming,governance"
18172,2021-04-11,Yield Protocol,YIELD,0.254329,8.649653e+06,1.714820e+06,3.400974e+07,140682540.0,1.406825e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://yieldprotocol.org,"defi,dao-maker"
18173,2021-04-11,ZeroSwap,ZEE,2.211059,8.598739e+07,2.467450e+07,3.888968e+07,NaN,1.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://zeroswap.io,"defi,binance-smart-chain"

### adding tags as columns in DF

In [12]:
required_tags = ['binance-smart-chain','polkadot-ecosystem','ethereum','cosmos-ecosystem','polkadot','solana-ecosystem','binance-chain','avalanche-ecosystem','heco','layer-2','eos','sidechain','cosmos','tron','defi','yield-farming','decentralized-exchange','governance','dao','gaming','stablecoin','asset-management','centralized-exchange','staking','yield-aggregator','oracles','lending-borowing','dex','options','launchpad','stablecoin-algorithmically-stabilized']
required_tags.sort()
tag_df = pd.DataFrame(df['Tags'].copy())

required_tags_map = {}
i = 0
for tag in required_tags:
    required_tags_map[tag] = i
    i = i + 1

all_symbol_tags = []
for index, row in tag_df.iterrows():
    tag = [''] * (len(required_tags))
    tags = row['Tags']
    tags = tags.split(',') if tags else []
    for t in tags:
        index = required_tags_map[t] if t in required_tags_map else -1
        if index > -1:
            tag[index] = 1
    all_symbol_tags.append(tag)

tag_columns = []
tag_columns.extend(required_tags)

tag_column_df = pd.DataFrame(all_symbol_tags, columns = tag_columns)
df = df.join(tag_column_df)
del df['Tags']
del df['CoinUrl']
df

,date,Name,Symbol,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Debank,...,polkadot,polkadot-ecosystem,sidechain,solana-ecosystem,stablecoin,stablecoin-algorithmically-stabilized,staking,tron,yield-aggregator,yield-farming
0,2020-12-21,Aave,AAVE,81.311937,9.757233e+08,2.154891e+08,1.199975e+07,16000000.0,1.600000e+07,1.723929e+09,...,,,,,,,,,,1
1,2020-12-21,Ampleforth,AMPL,0.820038,1.885767e+08,1.046414e+07,2.299609e+08,NaN,4.102788e+08,NaN,...,,,,,,,,,,
2,2020-12-21,Anyswap,ANY,0.198054,2.757083e+06,1.703378e+06,1.392088e+07,100000000.0,1.000000e+08,4.999804e+05,...,,,,,,,,,,
3,2020-12-21,APY.Finance,APY,0.232858,2.661404e+06,2.651785e+05,1.142932e+07,NaN,1.000000e+08,9.500688e+06,...,,,,,,,,,1,1
4,2020-12-21,Band Protocol,BAND,6.201058,1.270847e+08,7.327053e+07,2.049403e+07,NaN,1.000000e+08,NaN,...,,,,1,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18169,2021-04-11,yearn.finance,YFI,45127.296833,1.653236e+09,3.277292e+08,3.663494e+04,36666.0,3.666600e+04,NaN,...,,,,,,,,,1,1
18170,2021-04-11,DFI.Money,YFII,2997.790960,1.157027e+08,7.943857e+07,3.859600e+04,39375.0,3.937500e+04,3.208410e+07,...,,,,,,,,,1,1
18171,2021-04-11,YF Link,YFL,303.541197,1.563320e+07,4.852106e+05,5.150274e+04,52000.0,5.200000e+04,5.036109e+06,...,,,,,,,,,,1
18172,2021-04-11,Yield Protocol,YIELD,0.254329,8.649653e+06,1.714820e+06,3.400974e+07,140682540.0,1.406825e+08,NaN,...,,,,,,,,,,
18173,2021-04-11,ZeroSwap,ZEE,2.211059,8.598739e+07,2.467450e+07,3.888968e+07,NaN,1.000000e+08,NaN,...,,,,,,,,,,

### only coins tagged to defi

In [13]:
df = df[(df['defi'] == 1)]
df['defi'].unique()

array([1], dtype=object)

In [14]:
len(df['Symbol'].unique())

171

In [15]:
df['Symbol'].unique()

array(['AAVE', 'AMPL', 'ANY', 'APY', 'BAND', 'BEPRO', 'BONDLY', 'BZRX',
       'CHR', 'COMP', 'CREAM', 'CRV', 'CUSD', 'CVP', 'DF', 'DODO', 'FOR',
       'IDEX', 'KAVA', 'KP3R', 'LTX', 'MARK', 'MIR', 'MTA', 'OGN', 'PEAK',
       'PERP', 'RAMP', 'RENBTC', 'SCRT', 'SHROOM', 'SOCKS', 'STAKE',
       'SWINGBY', 'TRB', 'TRU', 'UMA', 'VAI', 'WING', 'XPR', 'XVS',
       'YF-DAI', 'YFI', 'YFII', 'ZEE', 'AKRO', 'ALPHA', 'AVAX', 'BADGER',
       'BAKE', 'BAL', 'BEL', 'BOR', 'CAKE', 'CORE', 'COTI', 'DAI', 'DEC',
       'DEGO', 'DEXE', 'DFI', 'DHT', 'DIA', 'EASY', 'FARM', 'FIS', 'FLM',
       'FRM', 'FRONT', 'HEGIC', 'INJ', 'JST', 'KEEP', 'LUNA', 'MUSD',
       'NXM', 'OCEAN', 'OM', 'ORN', 'POLS', 'RGT', 'RSR', 'RUNE', 'SFI',
       'SRM', 'STPT', 'SUKU', 'SURE', 'SUSHI', 'SUTER', 'SXP', 'UNFI',
       'UNI', 'USDN', 'AST', 'BEAM', 'BNT', 'BTS', 'FSN', 'FTM', 'GNO',
       'KNC', 'LINK', 'LRC', 'MET', 'MKR', 'MLN', 'NEX', 'NMR', 'PHB',
       'REN', 'REP', 'REQ', 'RLC', 'SNX', 'SUSD', 'SWTH', 'UQC', 'WAN',
       'WBTC', 'XHV', 'ZAP', 'ZRX', 'DDX', '1INCH', 'FXS', 'WHITE',
       'REEF', 'PNT', 'UNISTAKE', 'FIN', 'HAKKA', 'MTRG', 'NSURE',
       'PICKLE', 'SWRV', 'SYNC', 'YFL', 'DOUGH', 'DYP', 'HGET', 'IDLE',
       'LDO', 'LUA', 'STRONG', 'AUC', 'SWFTC', 'TKN', 'COMBO', 'KSP',
       'ARMOR', 'MDX', 'OPIUM', 'BOT', 'OXEN', 'DAO', 'UMB', 'AUTO',
       'VSP', 'RAY', 'EGG', 'POLK', 'AUCTION', 'MATTER', 'APYS', 'DOWS',
       'XEND', 'YIELD', 'STRK', 'FEI', 'TRIBE'], dtype=object)

In [16]:
original_df.columns

Index(['date', 'Name', 'Symbol', 'Price', 'Marketcap CMC', 'Volume CMC',
       'Circulating supply CMC', 'MAX Supply CMC', 'Total Supply CMC',
       'TVL Debank', 'TVL Defipulse', 'Transaction Revenue',
       'Interest Revenue', 'Transaction Revenue Supply Side',
       'Interest Revenue Supply Side', 'Transaction Revenue Protocol',
       'Interest Revenue Protocol', 'Transaction GMV', 'Interest GMV',
       'Price/Sale', 'Users 24hr Debank', 'Transactions Count Debank',
       'Trading Volume Debank', 'Borrowing Volume Debank',
       'Users life-to-date duneanlytics', 'CoinUrl', 'Tags'],
      dtype='object')

In [17]:
df['TVL_max'] = df[['TVL Debank', 'TVL Defipulse']].max(axis=1)

<ipython-input-17-615ad563b3ca>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TVL_max'] = df[['TVL Debank', 'TVL Defipulse']].max(axis=1)

In [18]:
df['GMV'] = (df['Transaction GMV'].fillna(0) + df['Interest GMV'].fillna(0)).replace({'0':np.nan, 0:np.nan})
df['Defi Volume DeBank'] = (df['Trading Volume Debank'].fillna(0) + df['Borrowing Volume Debank'].fillna(0)).replace({'0':np.nan, 0:np.nan})

<ipython-input-18-c6d5e2bb4a4b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['GMV'] = (df['Transaction GMV'].fillna(0) + df['Interest GMV'].fillna(0)).replace({'0':np.nan, 0:np.nan})
<ipython-input-18-c6d5e2bb4a4b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Defi Volume DeBank'] = (df['Trading Volume Debank'].fillna(0) + df['Borrowing Volume Debank'].fillna(0)).replace({'0':np.nan, 0:np.nan})

In [19]:
# add defi volume max as max of gmv from tokenterminal and defi volume debank
df['Defi Volume_max'] = df[['GMV', 'Defi Volume DeBank']].max(axis=1)

<ipython-input-19-fb777fdab8ae>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Defi Volume_max'] = df[['GMV', 'Defi Volume DeBank']].max(axis=1)

In [20]:
df['GMV']

0        3.378761e+08
1                 NaN
2                 NaN
3                 NaN
4                 NaN
             ...
18169             NaN
18170             NaN
18171             NaN
18172             NaN
18173             NaN
Name: GMV, Length: 17279, dtype: float64

In [21]:
# add defi volume max as max of gmv from tokenterminal and defi volume debank
df['Defi Volume_max'] = df[['GMV', 'Defi Volume DeBank']].max(axis=1)

<ipython-input-21-fb777fdab8ae>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Defi Volume_max'] = df[['GMV', 'Defi Volume DeBank']].max(axis=1)

In [22]:
df['Defi Volume DeBank']

0                 NaN
1                 NaN
2        12187.952376
3                 NaN
4                 NaN
             ...
18169             NaN
18170             NaN
18171    43631.672764
18172             NaN
18173             NaN
Name: Defi Volume DeBank, Length: 17279, dtype: float64

In [23]:
df['max_test'] = df[['MAX Supply CMC', 'Total Supply CMC']].max(axis=1)
df['fully_diluted_mkt_cap'] = df.max_test * df.Price

del df['max_test']

<ipython-input-23-28ed4bdc6395>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['max_test'] = df[['MAX Supply CMC', 'Total Supply CMC']].max(axis=1)
<ipython-input-23-28ed4bdc6395>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fully_diluted_mkt_cap'] = df.max_test * df.Price

In [24]:
df["total_revenue"] = (df["Transaction Revenue"].fillna(0) + df["Interest Revenue"].fillna(0)).replace({'0':np.nan, 0:np.nan})
df["total_supply_revenue"] = (df["Transaction Revenue Supply Side"].fillna(0) + df["Interest Revenue Supply Side"].fillna(0)).replace({'0':np.nan, 0:np.nan})
df["total_protocol_revenue"] = (df["Interest Revenue Protocol"].fillna(0) + df["Transaction Revenue Protocol"].fillna(0)).replace({'0':np.nan, 0:np.nan})

<ipython-input-24-c3f5021f3958>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["total_revenue"] = (df["Transaction Revenue"].fillna(0) + df["Interest Revenue"].fillna(0)).replace({'0':np.nan, 0:np.nan})
<ipython-input-24-c3f5021f3958>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["total_supply_revenue"] = (df["Transaction Revenue Supply Side"].fillna(0) + df["Interest Revenue Supply Side"].fillna(0)).replace({'0':np.nan, 0:np.nan})
<ipython-input-24-c3f5021f3958>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["total_protocol_revenue"] = (df["Interest Revenue Protocol"].fillna(0) + df["Transaction Revenue Protocol"].fillna(0)).replace({'0':np.nan, 0:np.nan})

In [25]:
df[["total_revenue", "total_supply_revenue", "total_protocol_revenue"]]

       total_revenue  total_supply_revenue  total_protocol_revenue
0       51058.960937          50173.411248              885.549689
1                NaN                   NaN                     NaN
2                NaN                   NaN                     NaN
3                NaN                   NaN                     NaN
4                NaN                   NaN                     NaN
...              ...                   ...                     ...
18169            NaN                   NaN                     NaN
18170            NaN                   NaN                     NaN
18171            NaN                   NaN                     NaN
18172            NaN                   NaN                     NaN
18173            NaN                   NaN                     NaN

[17279 rows x 3 columns]

In [26]:
df[df['Name'] == 'Compound'][['Transaction Revenue', 'Interest Revenue', 'total_revenue']]

       Transaction Revenue  Interest Revenue  total_revenue
10                     NaN      3.290080e+05   3.290080e+05
226                    NaN      2.997162e+05   2.997162e+05
274                    NaN      3.206756e+05   3.206756e+05
491                    NaN      3.234628e+05   3.234628e+05
540                    NaN      3.759938e+05   3.759938e+05
...                    ...               ...            ...
17414                  NaN      1.706923e+06   1.706923e+06
17476                  NaN      1.429647e+06   1.429647e+06
17768                  NaN      1.579009e+06   1.579009e+06
17830                  NaN      1.638977e+06   1.638977e+06
18122                  NaN               NaN            NaN

[111 rows x 3 columns]

In [27]:
df = df.sort_values('date')

In [28]:
cmc_symbol_name_df = pd.read_sql_query("select distinct Symbol, Name from g_master_data_joins order by Symbol, Name", __connect__())

In [29]:
cmc_symbol_name_df = cmc_symbol_name_df[cmc_symbol_name_df['Symbol'].isin(top_symbols)]

In [ ]:
# add n day users
def calculate_nDay_users(df, days):
    column_name = f"total_users_{days}d"
    df[column_name] = 0
    for index, row in cmc_symbol_name_df.iterrows():
        symbol = row['Symbol']
        name = row['Name']
        temp_df = df[(df['Symbol'] == symbol) & (df['Name'] == name)].copy()
        temp_df['parent_index'] = temp_df.index
        temp_df.index = pd.DatetimeIndex(temp_df['date'])
        temp_df[column_name] = temp_df['Users 24hr Debank'].rolling(f"{days}d").sum()
        temp_df.index = temp_df["parent_index"]
        del temp_df['parent_index']
        for index, row in temp_df.iterrows():
            df.loc[index, column_name] = row[column_name]

In [30]:
def calculate_nDay_revenue(df, days):
    column_name = f"total_revenue_{days}d"
    df[column_name] = 0
    for index, row in cmc_symbol_name_df.iterrows():
        symbol = row['Symbol']
        name = row['Name']
        temp_df = df[(df['Symbol'] == symbol) & (df['Name'] == name)].copy()
        temp_df['parent_index'] = temp_df.index
        temp_df.index = pd.DatetimeIndex(temp_df['date'])
        temp_df[column_name] = temp_df['total_revenue'].rolling(f"{days}d").sum()
        temp_df.index = temp_df["parent_index"]
        del temp_df['parent_index']
        for index, row in temp_df.iterrows():
            df.loc[index, column_name] = row[column_name]

In [31]:
# function for defi volume sums
# substitute for volume cmc sum
# changing defi volume debank to Defi Volume_max
def calculate_nDay_defi_volume(df, days):
    column_name = f"total_defi_volume_{days}d"
    df[column_name] = 0
    for index, row in cmc_symbol_name_df.iterrows():
        symbol = row['Symbol']
        name = row['Name']
        temp_df = df[(df['Symbol'] == symbol) & (df['Name'] == name)].copy()
        temp_df['parent_index'] = temp_df.index
        temp_df.index = pd.DatetimeIndex(temp_df['date'])
        temp_df[column_name] = temp_df['Defi Volume_max'].rolling(f"{days}d").sum()
        temp_df.index = temp_df["parent_index"]
        del temp_df['parent_index']
        for index, row in temp_df.iterrows():
            df.loc[index, column_name] = row[column_name]

In [32]:
def calculate_nDay_change(df, days, column, column_name):
    df[column_name] = 0
    for index, row in cmc_symbol_name_df.iterrows():
        symbol = row['Symbol']
        name = row['Name']
        temp_df = df[(df['Symbol'] == symbol) & (df['Name'] == name)].copy()
        temp_df['parent_index'] = temp_df.index
        temp_df.index = pd.DatetimeIndex(temp_df['date'])
        temp_df[column_name] = temp_df[column].pct_change(days)
        temp_df.index = temp_df["parent_index"]
        del temp_df['parent_index']
        for index, row in temp_df.iterrows():
            df.loc[index, column_name] = row[column_name]
    
def calculate_nDay_std(df, days, column, column_name, div_by_column='Price'):
    df[column_name] = 0
    for index, row in cmc_symbol_name_df.iterrows():
        symbol = row['Symbol']
        name = row['Name']
        temp_df = df[(df['Symbol'] == symbol) & (df['Name'] == name)].copy()
        temp_df['parent_index'] = temp_df.index
        temp_df.index = pd.DatetimeIndex(temp_df['date'])
        temp_df[column_name] = temp_df[column].rolling(days).std() / temp_df[div_by_column]
        temp_df.index = temp_df["parent_index"]
        del temp_df['parent_index']
        for index, row in temp_df.iterrows():
            df.loc[index, column_name] = row[column_name]

In [33]:
calculate_nDay_revenue(df, 7)
calculate_nDay_revenue(df, 30)
#calculate_nDay_trading_volume(df, 30)
calculate_nDay_defi_volume(df, 30)
# add n day users
calculate_nDay_users(df, 30)

# add 1, 3, 7, 30 day defi volume pct change here
# added column calculations
#
calculate_nDay_change(df, 1, 'Defi Volume_max', 'Defi_volume_pct_chg_1d')
calculate_nDay_change(df, 3, 'Defi Volume_max', 'Defi_volume_pct_chg_3d')
calculate_nDay_change(df, 7, 'Defi Volume_max', 'Defi_volume_pct_chg_7d')
calculate_nDay_change(df, 30, 'Defi Volume_max', 'Defi_volume_pct_chg_30d')
#

In [34]:
df[df['Symbol'] == 'AAVE']['total_revenue_7d']

0        5.105896e+04
216      1.039415e+05
264      1.514182e+05
481      2.232560e+05
530      2.762748e+05
             ...
17404    1.716373e+06
17466    1.551086e+06
17758    1.509591e+06
17820    1.427605e+06
18112    1.119079e+06
Name: total_revenue_7d, Length: 112, dtype: float64

In [35]:
df[df['Symbol'] == 'AAVE']['total_defi_volume_30d']

0        3.378761e+08
216      6.595928e+08
264      9.596765e+08
481      1.247095e+09
530      1.599726e+09
             ...
17404    3.394203e+10
17466    3.344731e+10
17758    3.307400e+10
17820    3.271072e+10
18112    3.149080e+10
Name: total_defi_volume_30d, Length: 112, dtype: float64

In [36]:
df

,date,Name,Symbol,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Debank,...,total_revenue,total_supply_revenue,total_protocol_revenue,total_revenue_7d,total_revenue_30d,total_defi_volume_30d,Defi_volume_pct_chg_1d,Defi_volume_pct_chg_3d,Defi_volume_pct_chg_7d,Defi_volume_pct_chg_30d
0,2020-12-21,Aave,AAVE,81.311937,9.757233e+08,2.154891e+08,1.199975e+07,1.600000e+07,1.600000e+07,1.723929e+09,...,51058.960937,50173.411248,885.549689,51058.960937,51058.960937,3.378761e+08,NaN,NaN,NaN,NaN
96,2020-12-21,Swipe,SXP,0.857921,6.894847e+07,2.569640e+07,8.036693e+07,NaN,2.892670e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,2020-12-21,suterusu,SUTER,0.003697,6.004558e+06,7.755178e+04,1.624038e+09,NaN,1.000000e+10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,2020-12-21,SushiSwap,SUSHI,2.514379,4.298866e+08,1.834664e+08,1.709713e+08,0.000000e+00,1.709713e+08,1.114148e+09,...,270633.667338,225528.056115,45105.611223,270633.667338,270633.667338,9.021122e+07,NaN,NaN,NaN,NaN
93,2020-12-21,inSure,SURE,0.001968,7.003992e+06,1.222256e+04,3.559703e+09,8.800000e+10,8.800000e+10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18057,2021-04-11,DIA,DIA,4.688825,1.888549e+08,3.864829e+07,4.027766e+07,2.000000e+08,2.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18058,2021-04-11,PieDAO DOUGH v2,DOUGH,1.346194,9.147810e+06,9.745090e+05,6.795315e+06,NaN,7.617169e+07,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18059,2021-04-11,Shadows,DOWS,1.766102,1.687731e+07,1.490669e+06,9.556250e+06,NaN,1.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18051,2021-04-11,DerivaDAO,DDX,5.897248,1.538867e+08,2.732501e+05,2.609466e+07,1.000000e+08,5.029731e+07,3.381876e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18173,2021-04-11,ZeroSwap,ZEE,2.211059,8.598739e+07,2.467450e+07,3.888968e+07,NaN,1.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
df.columns

Index(['date', 'Name', 'Symbol', 'Price', 'Marketcap CMC', 'Volume CMC',
       'Circulating supply CMC', 'MAX Supply CMC', 'Total Supply CMC',
       'TVL Debank', 'TVL Defipulse', 'Transaction Revenue',
       'Interest Revenue', 'Transaction Revenue Supply Side',
       'Interest Revenue Supply Side', 'Transaction Revenue Protocol',
       'Interest Revenue Protocol', 'Transaction GMV', 'Interest GMV',
       'Price/Sale', 'Users 24hr Debank', 'Transactions Count Debank',
       'Trading Volume Debank', 'Borrowing Volume Debank',
       'Users life-to-date duneanlytics', 'asset-management',
       'avalanche-ecosystem', 'binance-chain', 'binance-smart-chain',
       'centralized-exchange', 'cosmos', 'cosmos-ecosystem', 'dao',
       'decentralized-exchange', 'defi', 'dex', 'eos', 'ethereum', 'gaming',
       'governance', 'heco', 'launchpad', 'layer-2', 'lending-borowing',
       'options', 'oracles', 'polkadot', 'polkadot-ecosystem', 'sidechain',
       'solana-ecosystem', 'stablecoin',
       'stablecoin-algorithmically-stabilized', 'staking', 'tron',
       'yield-aggregator', 'yield-farming', 'TVL_max', 'GMV',
       'Defi Volume DeBank', 'Defi Volume_max', 'fully_diluted_mkt_cap',
       'total_revenue', 'total_supply_revenue', 'total_protocol_revenue',
       'total_revenue_7d', 'total_revenue_30d', 'total_defi_volume_30d',
       'Defi_volume_pct_chg_1d', 'Defi_volume_pct_chg_3d',
       'Defi_volume_pct_chg_7d', 'Defi_volume_pct_chg_30d'],
      dtype='object')

In [38]:
# flip such that mc in numerator 
#df['VOL : MC'] = df['Volume CMC'] / df['Marketcap CMC']
df['MC : VOL'] = df['Marketcap CMC'] / df['Volume CMC'] 
# added column calculations
calculate_nDay_change(df, 1, 'MC : VOL', 'MC_VOL_pct_chg_1d')
calculate_nDay_change(df, 3, 'MC : VOL', 'MC_VOL_pct_chg_3d')
calculate_nDay_change(df, 7, 'MC : VOL', 'MC_VOL_pct_chg_7d')
calculate_nDay_change(df, 30, 'MC : VOL', 'MC_VOL_pct_chg_30d')
#

# flip such that mc in numerator
#df['VOL : DMC'] = df['Volume CMC'] / df['fully_diluted_mkt_cap']
df['DMC : VOL'] = df['fully_diluted_mkt_cap'] / df['Volume CMC']
# added column calculations
calculate_nDay_change(df, 1, 'DMC : VOL', 'DMC_VOL_pct_chg_1d')
calculate_nDay_change(df, 3, 'DMC : VOL', 'DMC_VOL_pct_chg_3d')
calculate_nDay_change(df, 7, 'DMC : VOL', 'DMC_VOL_pct_chg_7d')
calculate_nDay_change(df, 30, 'DMC : VOL', 'DMC_VOL_pct_chg_30d')
#



df['MC : TVL'] = df['Marketcap CMC'] / df['TVL_max']
# added column calculations
calculate_nDay_change(df, 1, 'MC : TVL', 'MC_TVL_pct_chg_1d')
calculate_nDay_change(df, 3, 'MC : TVL', 'MC_TVL_pct_chg_3d')
calculate_nDay_change(df, 7, 'MC : TVL', 'MC_TVL_pct_chg_7d')
calculate_nDay_change(df, 30, 'MC : TVL', 'MC_TVL_pct_chg_30d')
#


df['DMC : TVL'] = df['fully_diluted_mkt_cap'] / df['TVL_max']
# added column calculations
calculate_nDay_change(df, 1, 'DMC : TVL', 'DMC_TVL_pct_chg_1d')
calculate_nDay_change(df, 3, 'DMC : TVL', 'DMC_TVL_pct_chg_3d')
calculate_nDay_change(df, 7, 'DMC : TVL', 'DMC_TVL_pct_chg_7d')
calculate_nDay_change(df, 30, 'DMC : TVL', 'DMC_TVL_pct_chg_30d')
#


df['MC : users (1d)'] = df['Marketcap CMC'] / df['Users 24hr Debank']
# added column calculations
calculate_nDay_change(df, 1, 'MC : users (1d)', 'MC_users_pct_chg_1d')
calculate_nDay_change(df, 3, 'MC : users (1d)', 'MC_users_pct_chg_3d')
calculate_nDay_change(df, 7, 'MC : users (1d)', 'MC_users_pct_chg_7d')
calculate_nDay_change(df, 30, 'MC : users (1d)', 'MC_users_pct_chg_30d')
#




df['DMC : users (1d)'] = df['fully_diluted_mkt_cap'] / df['Users 24hr Debank']
# added column calculations
calculate_nDay_change(df, 1, 'DMC : users (1d)', 'DMC_users_pct_chg_1d')
calculate_nDay_change(df, 3, 'DMC : users (1d)', 'DMC_users_pct_chg_3d')
calculate_nDay_change(df, 7, 'DMC : users (1d)', 'DMC_users_pct_chg_7d')
calculate_nDay_change(df, 30, 'DMC : users (1d)', 'DMC_users_pct_chg_30d')
#



df['MC : transactions (1d)'] = df['Marketcap CMC'] / df['Transactions Count Debank']
# added column calculations
calculate_nDay_change(df, 1, 'MC : transactions (1d)', 'MC_transactions_pct_chg_1d')
calculate_nDay_change(df, 3, 'MC : transactions (1d)', 'MC_transactions_pct_chg_3d')
calculate_nDay_change(df, 7, 'MC : transactions (1d)', 'MC_transactions_pct_chg_7d')
calculate_nDay_change(df, 30, 'MC : transactions (1d)', 'MC_transactions_pct_chg_30d')
#

df['DMC : transactions (1d)'] = df['fully_diluted_mkt_cap'] / df['Transactions Count Debank']
# added column calculations
calculate_nDay_change(df, 1, 'DMC : transactions (1d)', 'DMC_transactions_pct_chg_1d')
calculate_nDay_change(df, 3, 'DMC : transactions (1d)', 'DMC_transactions_pct_chg_3d')
calculate_nDay_change(df, 7, 'DMC : transactions (1d)', 'DMC_transactions_pct_chg_7d')
calculate_nDay_change(df, 30, 'DMC : transactions (1d)', 'DMC_transactions_pct_chg_30d')
#

#df['MC : DEX Vol (1d)'] = df['Marketcap CMC'] / df['Trading Volume Debank']
# add
df['MC : Defi Vol (1d)'] = df['Marketcap CMC'] / df['Defi Volume_max']
# added column calculations
calculate_nDay_change(df, 1, 'MC : Defi Vol (1d)', 'MC_defi_volume_pct_chg_1d')
calculate_nDay_change(df, 3, 'MC : Defi Vol (1d)', 'MC_defi_volume_pct_chg_3d')
calculate_nDay_change(df, 7, 'MC : Defi Vol (1d)', 'MC_defi_volume_pct_chg_7d')
calculate_nDay_change(df, 30, 'MC : Defi Vol (1d)', 'MC_defi_volume_pct_chg_30d')
#


df['MC : Defi Vol (30d)'] = df['Marketcap CMC'] / df['total_defi_volume_30d']
#df['DMC : DEX Vol (1d)'] = df['fully_diluted_mkt_cap'] / df['Trading Volume Debank']
#df['DMC : DEX Vol (30d)'] = df['fully_diluted_mkt_cap'] / df['total_volume_30d']



df['MC : revenue'] = df['Marketcap CMC'] / df['total_revenue']
# added column calculations
calculate_nDay_change(df, 1, 'MC : revenue', 'MC_revenue_pct_chg_1d')
calculate_nDay_change(df, 3, 'MC : revenue', 'MC_revenue_pct_chg_3d')
calculate_nDay_change(df, 7, 'MC : revenue', 'MC_revenue_pct_chg_7d')
calculate_nDay_change(df, 30, 'MC : revenue', 'MC_revenue_pct_chg_30d')
#

df['DMC : revenue'] = df['fully_diluted_mkt_cap'] / df['total_revenue']
# added column calculations
calculate_nDay_change(df, 1, 'DMC : revenue', 'DMC_revenue_pct_chg_1d')
calculate_nDay_change(df, 3, 'DMC : revenue', 'DMC_revenue_pct_chg_3d')
calculate_nDay_change(df, 7, 'DMC : revenue', 'DMC_revenue_pct_chg_7d')
calculate_nDay_change(df, 30, 'DMC : revenue', 'DMC_revenue_pct_chg_30d')
#



df['MC : total_users_30d'] = df['Marketcap CMC'] / df['total_users_30d']
# added column calculations
calculate_nDay_change(df, 1, 'MC : total_users_30d', 'MC_users_30d_pct_chg_1d')
calculate_nDay_change(df, 3, 'MC : total_users_30d', 'MC_users_30d_pct_chg_3d')
calculate_nDay_change(df, 7, 'MC : total_users_30d', 'MC_users_30d_pct_chg_7d')
calculate_nDay_change(df, 30, 'MC : total_users_30d', 'MC_users_30d_pct_chg_30d')
#



df['DMC : total_users_30d'] = df['fully_diluted_mkt_cap'] / df['total_users_30d']
# added column calculations
calculate_nDay_change(df, 1, 'DMC : total_users_30d', 'DMC_users_30d_pct_chg_1d')
calculate_nDay_change(df, 3, 'DMC : total_users_30d', 'DMC_users_30d_pct_chg_3d')
calculate_nDay_change(df, 7, 'DMC : total_users_30d', 'DMC_users_30d_pct_chg_7d')
calculate_nDay_change(df, 30, 'DMC : total_users_30d', 'DMC_users_30d_pct_chg_30d')
#


# df['MC : policies sold'] = df['Marketcap CMC'] / df['abc']
# df['DMC : policies sold'] = df['fully_diluted_mkt_cap'] / df['abc']
# df['MC : premium'] = df['Marketcap CMC'] / df['abc']
# df['DMC : premium'] = df['fully_diluted_mkt_cap'] / df['abc']

In [39]:
df

,date,Name,Symbol,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Debank,...,MC : revenue,MC_revenue_pct_chg_1d,MC_revenue_pct_chg_3d,MC_revenue_pct_chg_7d,MC_revenue_pct_chg_30d,DMC : revenue,DMC_revenue_pct_chg_1d,DMC_revenue_pct_chg_3d,DMC_revenue_pct_chg_7d,DMC_revenue_pct_chg_30d
0,2020-12-21,Aave,AAVE,81.311937,9.757233e+08,2.154891e+08,1.199975e+07,1.600000e+07,1.600000e+07,1.723929e+09,...,19109.736101,NaN,NaN,NaN,NaN,25480.169805,NaN,NaN,NaN,NaN
96,2020-12-21,Swipe,SXP,0.857921,6.894847e+07,2.569640e+07,8.036693e+07,NaN,2.892670e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,2020-12-21,suterusu,SUTER,0.003697,6.004558e+06,7.755178e+04,1.624038e+09,NaN,1.000000e+10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,2020-12-21,SushiSwap,SUSHI,2.514379,4.298866e+08,1.834664e+08,1.709713e+08,0.000000e+00,1.709713e+08,1.114148e+09,...,1588.444779,NaN,NaN,NaN,NaN,1588.444779,NaN,NaN,NaN,NaN
93,2020-12-21,inSure,SURE,0.001968,7.003992e+06,1.222256e+04,3.559703e+09,8.800000e+10,8.800000e+10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18057,2021-04-11,DIA,DIA,4.688825,1.888549e+08,3.864829e+07,4.027766e+07,2.000000e+08,2.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18058,2021-04-11,PieDAO DOUGH v2,DOUGH,1.346194,9.147810e+06,9.745090e+05,6.795315e+06,NaN,7.617169e+07,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18059,2021-04-11,Shadows,DOWS,1.766102,1.687731e+07,1.490669e+06,9.556250e+06,NaN,1.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18051,2021-04-11,DerivaDAO,DDX,5.897248,1.538867e+08,2.732501e+05,2.609466e+07,1.000000e+08,5.029731e+07,3.381876e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18173,2021-04-11,ZeroSwap,ZEE,2.211059,8.598739e+07,2.467450e+07,3.888968e+07,NaN,1.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
calculate_nDay_change(df, 1, 'Price', 'Price_pct_chg_1d')
calculate_nDay_change(df, 3, 'Price', 'Price_pct_chg_3d')
calculate_nDay_change(df, 7, 'Price', 'Price_pct_chg_7d')
calculate_nDay_change(df, 30, 'Price', 'Price_pct_chg_30d')
calculate_nDay_std(df, 7, 'Price', 'Price_7day_volatility_pct', div_by_column='Price')
calculate_nDay_std(df, 30, 'Price', 'Price_30day_volatility_pct', div_by_column='Price')
calculate_nDay_std(df, 90, 'Price', 'Price_90day_volatility_pct', div_by_column='Price')

In [41]:
calculate_nDay_change(df, 1, 'Marketcap CMC', 'MC_pct_chg_1d')
calculate_nDay_change(df, 3, 'Marketcap CMC', 'MC_pct_chg_3d')
calculate_nDay_change(df, 7, 'Marketcap CMC', 'MC_pct_chg_7d')
calculate_nDay_change(df, 30, 'Marketcap CMC', 'MC_pct_chg_30d')
calculate_nDay_std(df, 30, 'Marketcap CMC', 'MC_30day_volatility_pct', div_by_column='Marketcap CMC')
calculate_nDay_std(df, 90, 'Marketcap CMC', 'MC_90day_volatility_pct', div_by_column='Marketcap CMC')

In [42]:
calculate_nDay_change(df, 1, 'fully_diluted_mkt_cap', 'DMC_pct_chg_1d')
calculate_nDay_change(df, 3, 'fully_diluted_mkt_cap', 'DMC_pct_chg_3d')
calculate_nDay_change(df, 7, 'fully_diluted_mkt_cap', 'DMC_pct_chg_7d')
calculate_nDay_change(df, 30, 'fully_diluted_mkt_cap', 'DMC_pct_chg_30d')
calculate_nDay_std(df, 30, 'fully_diluted_mkt_cap', 'DMC_30day_volatility_pct', div_by_column='fully_diluted_mkt_cap')
calculate_nDay_std(df, 90, 'fully_diluted_mkt_cap', 'DMC_90day_volatility_pct', div_by_column='fully_diluted_mkt_cap')

In [43]:
calculate_nDay_change(df, 1, 'Circulating supply CMC', 'CS_pct_chg_1d')
calculate_nDay_change(df, 3, 'Circulating supply CMC', 'CS_pct_chg_d')
calculate_nDay_change(df, 7, 'Circulating supply CMC', 'CS_pct_chg_7d')
calculate_nDay_change(df, 30, 'Circulating supply CMC', 'CS_pct_chg_30d')
calculate_nDay_std(df, 30, 'Circulating supply CMC', 'CS_30day_volatility_pct', div_by_column='Circulating supply CMC')
calculate_nDay_std(df, 90, 'Circulating supply CMC', 'CS_90day_volatility_pct', div_by_column='Circulating supply CMC')

In [44]:
calculate_nDay_change(df, 1, 'Volume CMC', 'Volume_pct_chg_1d')
calculate_nDay_change(df, 3, 'Volume CMC', 'Volume_pct_chg_3d')
calculate_nDay_change(df, 7, 'Volume CMC', 'Volume_pct_chg_7d')
calculate_nDay_change(df, 30, 'Volume CMC', 'Volume_pct_chg_30d')
calculate_nDay_std(df, 30, 'Volume CMC', 'Volume_30day_volatility_pct', div_by_column='Volume CMC')
calculate_nDay_std(df, 90, 'Volume CMC', 'Volume_90day_volatility_pct', div_by_column='Volume CMC')

In [45]:
calculate_nDay_change(df, 1, 'TVL_max', 'TVL_pct_chg_1d')
calculate_nDay_change(df, 3, 'TVL_max', 'TVL_pct_chg_3d')
calculate_nDay_change(df, 7, 'TVL_max', 'TVL_pct_chg_7d')
calculate_nDay_change(df, 30, 'TVL_max', 'TVL_pct_chg_30d')
calculate_nDay_std(df, 30, 'TVL_max', 'TVL_30day_volatility_pct', div_by_column='TVL_max')
calculate_nDay_std(df, 90, 'TVL_max', 'TVL_90day_volatility_pct', div_by_column='TVL_max')

In [46]:
calculate_nDay_change(df, 1, 'total_revenue', 'Rev_pct_chg_1d')
calculate_nDay_change(df, 3, 'total_revenue', 'Rev_pct_chg_3d')
calculate_nDay_change(df, 7, 'total_revenue', 'Rev_pct_chg_7d')
calculate_nDay_change(df, 30, 'total_revenue', 'Rev_pct_chg_30d')
calculate_nDay_std(df, 30, 'total_revenue', 'Rev_30day_volatility_pct', div_by_column='total_revenue')
calculate_nDay_std(df, 90, 'total_revenue', 'Rev_90day_volatility_pct', div_by_column='total_revenue')

In [47]:
# moved pct change to next to ratio so commenting these out

#calculate_nDay_change(df, 1, 'MC : TVL', 'MC : TVL_pct_chg_1d')
#calculate_nDay_change(df, 3, 'MC : TVL', 'MC : TVL_pct_chg_3d')
#calculate_nDay_change(df, 7, 'MC : TVL', 'MC : TVL_pct_chg_7d')
#calculate_nDay_change(df, 30, 'MC : TVL', 'MC : TVL_pct_chg_30d')
# commented out below 
# calculate_nDay_std(df, 30, 'Circulating supply CMC', 'Rev σ 30d')
# calculate_nDay_std(df, 90, 'Circulating supply CMC', 'Rev σ 90d')

In [48]:
# moved pct change to next to ratio so commenting these out

#calculate_nDay_change(df, 1, 'DMC : TVL', 'DMC : TVL_pct_chg_1d')
#calculate_nDay_change(df, 3, 'DMC : TVL', 'DMC : TVL_pct_chg_3d')
#calculate_nDay_change(df, 7, 'DMC : TVL', 'DMC : TVL_pct_chg_7d')
#calculate_nDay_change(df, 30, 'DMC : TVL', 'DMC : TVL_pct_chg_30d')
# calculate_nDay_std(df, 30, 'Circulating supply CMC', 'CS σ 30d')
# calculate_nDay_std(df, 90, 'Circulating supply CMC', 'CS σ 90d')

In [49]:
df['Annual revenue (estimate)'] = df['total_revenue_30d'] * (1 + df['Rev_pct_chg_30d'])*12

In [50]:
df['Annual revenue (estimate)'].unique()

array([              nan, 83208884.0865837 ,  9925154.22741311, ...,
        7570245.86281545, 44286947.33420965,  5329069.03951519])

In [51]:
columns = df.columns.tolist()

In [52]:
df[df['defi'] == 1]

,date,Name,Symbol,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Debank,...,TVL_pct_chg_30d,TVL_30day_volatility_pct,TVL_90day_volatility_pct,Rev_pct_chg_1d,Rev_pct_chg_3d,Rev_pct_chg_7d,Rev_pct_chg_30d,Rev_30day_volatility_pct,Rev_90day_volatility_pct,Annual revenue (estimate)
0,2020-12-21,Aave,AAVE,81.311937,9.757233e+08,2.154891e+08,1.199975e+07,1.600000e+07,1.600000e+07,1.723929e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,2020-12-21,Swipe,SXP,0.857921,6.894847e+07,2.569640e+07,8.036693e+07,NaN,2.892670e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,2020-12-21,suterusu,SUTER,0.003697,6.004558e+06,7.755178e+04,1.624038e+09,NaN,1.000000e+10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,2020-12-21,SushiSwap,SUSHI,2.514379,4.298866e+08,1.834664e+08,1.709713e+08,0.000000e+00,1.709713e+08,1.114148e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,2020-12-21,inSure,SURE,0.001968,7.003992e+06,1.222256e+04,3.559703e+09,8.800000e+10,8.800000e+10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18057,2021-04-11,DIA,DIA,4.688825,1.888549e+08,3.864829e+07,4.027766e+07,2.000000e+08,2.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18058,2021-04-11,PieDAO DOUGH v2,DOUGH,1.346194,9.147810e+06,9.745090e+05,6.795315e+06,NaN,7.617169e+07,NaN,...,-0.147532,0.073440,0.731224,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18059,2021-04-11,Shadows,DOWS,1.766102,1.687731e+07,1.490669e+06,9.556250e+06,NaN,1.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18051,2021-04-11,DerivaDAO,DDX,5.897248,1.538867e+08,2.732501e+05,2.609466e+07,1.000000e+08,5.029731e+07,3.381876e+07,...,-0.004297,0.044308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18173,2021-04-11,ZeroSwap,ZEE,2.211059,8.598739e+07,2.467450e+07,3.888968e+07,NaN,1.000000e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
len(columns)

171

In [54]:
for tag in tag_columns:
    columns.remove(tag)

columns.extend(tag_columns)

In [55]:
columns

['date',
 'Name',
 'Symbol',
 'Price',
 'Marketcap CMC',
 'Volume CMC',
 'Circulating supply CMC',
 'MAX Supply CMC',
 'Total Supply CMC',
 'TVL Debank',
 'TVL Defipulse',
 'Transaction Revenue',
 'Interest Revenue',
 'Transaction Revenue Supply Side',
 'Interest Revenue Supply Side',
 'Transaction Revenue Protocol',
 'Interest Revenue Protocol',
 'Transaction GMV',
 'Interest GMV',
 'Price/Sale',
 'Users 24hr Debank',
 'Transactions Count Debank',
 'Trading Volume Debank',
 'Borrowing Volume Debank',
 'Users life-to-date duneanlytics',
 'TVL_max',
 'GMV',
 'Defi Volume DeBank',
 'Defi Volume_max',
 'fully_diluted_mkt_cap',
 'total_revenue',
 'total_supply_revenue',
 'total_protocol_revenue',
 'total_revenue_7d',
 'total_revenue_30d',
 'total_defi_volume_30d',
 'Defi_volume_pct_chg_1d',
 'Defi_volume_pct_chg_3d',
 'Defi_volume_pct_chg_7d',
 'Defi_volume_pct_chg_30d',
 'MC : VOL',
 'MC_VOL_pct_chg_1d',
 'MC_VOL_pct_chg_3d',
 'MC_VOL_pct_chg_7d',
 'MC_VOL_pct_chg_30d',
 'DMC : VOL',
 'DMC_VOL_pct_chg_1d',
 'DMC_VOL_pct_chg_3d',
 'DMC_VOL_pct_chg_7d',
 'DMC_VOL_pct_chg_30d',
 'MC : TVL',
 'MC_TVL_pct_chg_1d',
 'MC_TVL_pct_chg_3d',
 'MC_TVL_pct_chg_7d',
 'MC_TVL_pct_chg_30d',
 'DMC : TVL',
 'DMC_TVL_pct_chg_1d',
 'DMC_TVL_pct_chg_3d',
 'DMC_TVL_pct_chg_7d',
 'DMC_TVL_pct_chg_30d',
 'MC : users (1d)',
 'MC_users_pct_chg_1d',
 'MC_users_pct_chg_3d',
 'MC_users_pct_chg_7d',
 'MC_users_pct_chg_30d',
 'DMC : users (1d)',
 'DMC_users_pct_chg_1d',
 'DMC_users_pct_chg_3d',
 'DMC_users_pct_chg_7d',
 'DMC_users_pct_chg_30d',
 'MC : transactions (1d)',
 'MC_transactions_pct_chg_1d',
 'MC_transactions_pct_chg_3d',
 'MC_transactions_pct_chg_7d',
 'MC_transactions_pct_chg_30d',
 'DMC : transactions (1d)',
 'DMC_transactions_pct_chg_1d',
 'DMC_transactions_pct_chg_3d',
 'DMC_transactions_pct_chg_7d',
 'DMC_transactions_pct_chg_30d',
 'MC : Defi Vol (1d)',
 'MC_defi_volume_pct_chg_1d',
 'MC_defi_volume_pct_chg_3d',
 'MC_defi_volume_pct_chg_7d',
 'MC_defi_volume_pct_chg_30d',
 'MC : Defi Vol (30d)',
 'MC : revenue',
 'MC_revenue_pct_chg_1d',
 'MC_revenue_pct_chg_3d',
 'MC_revenue_pct_chg_7d',
 'MC_revenue_pct_chg_30d',
 'DMC : revenue',
 'DMC_revenue_pct_chg_1d',
 'DMC_revenue_pct_chg_3d',
 'DMC_revenue_pct_chg_7d',
 'DMC_revenue_pct_chg_30d',
 'Price_pct_chg_1d',
 'Price_pct_chg_3d',
 'Price_pct_chg_7d',
 'Price_pct_chg_30d',
 'Price_7day_volatility_pct',
 'Price_30day_volatility_pct',
 'Price_90day_volatility_pct',
 'MC_pct_chg_1d',
 'MC_pct_chg_3d',
 'MC_pct_chg_7d',
 'MC_pct_chg_30d',
 'MC_30day_volatility_pct',
 'MC_90day_volatility_pct',
 'DMC_pct_chg_1d',
 'DMC_pct_chg_3d',
 'DMC_pct_chg_7d',
 'DMC_pct_chg_30d',
 'DMC_30day_volatility_pct',
 'DMC_90day_volatility_pct',
 'CS_pct_chg_1d',
 'CS_pct_chg_d',
 'CS_pct_chg_7d',
 'CS_pct_chg_30d',
 'CS_30day_volatility_pct',
 'CS_90day_volatility_pct',
 'Volume_pct_chg_1d',
 'Volume_pct_chg_3d',
 'Volume_pct_chg_7d',
 'Volume_pct_chg_30d',
 'Volume_30day_volatility_pct',
 'Volume_90day_volatility_pct',
 'TVL_pct_chg_1d',
 'TVL_pct_chg_3d',
 'TVL_pct_chg_7d',
 'TVL_pct_chg_30d',
 'TVL_30day_volatility_pct',
 'TVL_90day_volatility_pct',
 'Rev_pct_chg_1d',
 'Rev_pct_chg_3d',
 'Rev_pct_chg_7d',
 'Rev_pct_chg_30d',
 'Rev_30day_volatility_pct',
 'Rev_90day_volatility_pct',
 'Annual revenue (estimate)',
 'asset-management',
 'avalanche-ecosystem',
 'binance-chain',
 'binance-smart-chain',
 'centralized-exchange',
 'cosmos',
 'cosmos-ecosystem',
 'dao',
 'decentralized-exchange',
 'defi',
 'dex',
 'eos',
 'ethereum',
 'gaming',
 'governance',
 'heco',
 'launchpad',
 'layer-2',
 'lending-borowing',
 'options',
 'oracles',
 'polkadot',
 'polkadot-ecosystem',
 'sidechain',
 'solana-ecosystem',
 'stablecoin',
 'stablecoin-algorithmically-stabilized',
 'staking',
 'tron',
 'yield-aggregator',
 'yield-farming']

In [56]:
tmp = df[columns]

In [57]:
tmp

,date,Name,Symbol,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Debank,...,polkadot,polkadot-ecosystem,sidechain,solana-ecosystem,stablecoin,stablecoin-algorithmically-stabilized,staking,tron,yield-aggregator,yield-farming
0,2020-12-21,Aave,AAVE,81.311937,9.757233e+08,2.154891e+08,1.199975e+07,1.600000e+07,1.600000e+07,1.723929e+09,...,,,,,,,,,,1
96,2020-12-21,Swipe,SXP,0.857921,6.894847e+07,2.569640e+07,8.036693e+07,NaN,2.892670e+08,NaN,...,,,,,,,,,,
95,2020-12-21,suterusu,SUTER,0.003697,6.004558e+06,7.755178e+04,1.624038e+09,NaN,1.000000e+10,NaN,...,,,,,,,,,,
94,2020-12-21,SushiSwap,SUSHI,2.514379,4.298866e+08,1.834664e+08,1.709713e+08,0.000000e+00,1.709713e+08,1.114148e+09,...,,,,,,,,,,1
93,2020-12-21,inSure,SURE,0.001968,7.003992e+06,1.222256e+04,3.559703e+09,8.800000e+10,8.800000e+10,NaN,...,,1,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18057,2021-04-11,DIA,DIA,4.688825,1.888549e+08,3.864829e+07,4.027766e+07,2.000000e+08,2.000000e+08,NaN,...,,1,,,,,,,,
18058,2021-04-11,PieDAO DOUGH v2,DOUGH,1.346194,9.147810e+06,9.745090e+05,6.795315e+06,NaN,7.617169e+07,NaN,...,,,,,,,,,,1
18059,2021-04-11,Shadows,DOWS,1.766102,1.687731e+07,1.490669e+06,9.556250e+06,NaN,1.000000e+08,NaN,...,1,1,,,,,,,,
18051,2021-04-11,DerivaDAO,DDX,5.897248,1.538867e+08,2.732501e+05,2.609466e+07,1.000000e+08,5.029731e+07,3.381876e+07,...,,,,,,,,,,
18173,2021-04-11,ZeroSwap,ZEE,2.211059,8.598739e+07,2.467450e+07,3.888968e+07,NaN,1.000000e+08,NaN,...,,,,,,,,,,

In [58]:
tmp.to_csv('master_data_ratios_and_percentages.csv')