In [1]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import traceback2
import time

In [2]:
# Configs

# CoinMarketCap.com API Key
api_key = "a86e3326-8c8d-434e-897a-5d6becbf1f35"
top_symbols_count = 500
read_data_from_file = True

### Method to fetch top n symbols/coin based on market_cap

In [3]:
def fetch_top_n_market_cap_symbols_(n):
    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    payload = {
        'convert':'USD',
        'aux':'cmc_rank',
        'limit':n
    }
    headers = {
      'Accepts': 'application/json',
      'X-CMC_PRO_API_KEY': api_key
    }
    
    data = requests.get(url, params=payload, headers=headers).json()['data']
    return data

### method to parse the top n market_cap symbols response ^^

In [15]:
def parse_data(rows):
    parsed_data = []
    for data in rows:
        parsed_data.append([data['name'], data['symbol'],data['cmc_rank'], data['quote']['USD']['market_cap']])
    return parsed_data

In [5]:
data = fetch_top_n_market_cap_symbols_(top_symbols_count)

In [6]:
d = parse_data(data)

In [7]:
df = pd.DataFrame(d, columns = ['name','symbol', 'rank', 'market_cap'])

In [8]:
df

                  name symbol  rank    market_cap
0              Bitcoin    BTC     1  1.028106e+12
1             Ethereum    ETH     2  2.619975e+11
2         Binance Coin    BNB     3  8.756377e+10
3                  XRP    XRP     4  6.060437e+10
4               Tether   USDT     5  4.906620e+10
..                 ...    ...   ...           ...
495  RSK Smart Bitcoin   RBTC   496  6.544100e+07
496            GXChain    GXC   497  6.535131e+07
497            Nebulas    NAS   500  6.505844e+07
498          Prometeus   PROM   498  6.506275e+07
499        DuckDaoDime   DDIM   501  6.465819e+07

[500 rows x 4 columns]

### top 300 coins based on market cap

In [9]:
symbols = df['symbol'].values.tolist()
# symbols = ['BTC', 'ETH', 'USDT','XRP']
merged_symbols = '1INCH,AAVE,ADA,ALPHA,ANY,APY,AR,ARMOR,AST,BAC,BADGER,BAL,BNB,BNT,BOND,BOR,BTC,BUSD,BZRX,COMP,CORE,COVER,CREAM,CRV,CVP,DAI,DCR,DDX,DF,DODO,DOGE,DOT,DUCK,ESD,ETH,EXRD,FARM,FOR,FRAX,GNO,GUSD,HEGIC,HUSD,ICHI,IDEX,IDLE,KEEP,KNC,KP3R,KSM,LDO,LINK,LPT,LRC,LTC,LUNA,MARK,MEME,MET,MIR,MKR,MLN,MPH,NXM,OPIUM,ORN,PAX,PEAK,PERP,PICKLE,RAMP,RARI,REN,RENBTC,REP,ROOK,SFI,SNOW,SNX,STAKE,SUSHI,SWAP,TORN,TRU,TRX,TUSD,UMA,UNI,USDC,USDK,USDN,USDT,UST,VSP,XLM,XTZ,YF-DAI,YFI,YFII,YLD,ZEC,ZRX'.split(',')
cmc_symbols = 'UNI,LINK,WBTC,LUNA,AAVE,AVAX,DAI,CAKE,RUNE,COMP,SNX,MKR,GRT,SUSHI,YFI,UMA,ZRX,BNT,FTM,RSR,REN,1INCH,OGN,CRV,MDX,DODO,OCEAN,LRC,KNC,RENBTC,XVS,REP,ALPHA,KAVA,REEF,SXP,BADGER,BAL,BTS,NMR,BAND,JST,WAN,SRM,COTI,GNO,POLS,INJ,XHV,FEI,DFI,KSP,MIR,NXM,ORN,KEEP,TRIBE,RAY,RLC,USDN,SCRT,AMPL,AKRO,BAKE,STAKE,BZRX,DDX,UQC,VAI,PERP,MLN,RAMP,REQ,BEL,CHR,SUSD,VSP,FLM,FRM,SURE,DIA,DEGO,DAO,SFI,OM,AUCTION,RGT,FARM,STRK,YFII,PHB,FRONT,DREP,TRB,ZEE,BEAM,HEGIC,CREAM,IDEX,SWTH,UNFI,XPR,WING,STPT,SUKU,OXEN,FXS,PNT,EASY,SWINGBY,DEXE,AST,CVP,BOR,FSN,TRU,BONDLY,CORE,MATTER,AUTO,ZAP,ANY,MTA,SUTER,POLK,NEX,DF,KP3R,PEAK,CUSD,MUSD,BOT,APY,FIS,RBC,DHT,FOR,MET,EGG,BEPRO,LTX,SHROOM,OPIUM,MARK,SOCKS,XEND,DEC,WHITE,ARMOR,UMB,APYS,STRONG,YF-DAI,SWRV,PICKLE,SWFTC,UNISTAKE,HOT,AUC,YFL,DOWS,HGET,MTRG,LUA,IDLE,TKN,FIN,DYP,SYNC,LDO,COMBO,HAKKA,SMARTCREDIT,DOUGH,CNS,NSURE,YIELD,HYPR,JRT,ALPACA,BITCNY,ALLOY,DMG,ADD,ROT,EOSDT,YVS,YFIII,DEFI++,VTX,ETHYS,PIPT,ACED,KP4R,DAM,ETHY,ORE,REB2,CDAI,CUSDC,VALUE,DPI,CUSDT,ALCX,COOK,ZDEX,DVG,LIEN,WGRT,DXD,MCB,XTK,CZRX,BOTS,YAX,PREMIA,CBAT,ORO,ONX,DEGEN,VBNT,INDEX,FONT,arNXM,ADEL,imBTC,DFD,STKR,DUSD,SASHIMI,PIE,CAP,CWBTC,CC10,ibETH,XSUSHI,DEFI+L,SETH,NEC,WARP,TBTC,RSV,DEFI+S,ORCL5,OKS,SBTC,YAM,ASSY,YETI,sYFL,U8D,CREP,CORD,YPIE,DCL,BANANA,EONS,THX,CSAI,PBTC,BTC++,ATUSD,AKNC,ALINK,ASNX,AMKR,ABAT,ABUSD,ADAI,SDEFI,IETH,VOLTS,DEFI5,MBTC,aENJ'.split(',')
defi_symbols = 'INCH,AAVE,AUC,BADGER,BAL,BNT,BZRX,COMP,CORE,COVER,CREAM,CREAM,CRV,DEXTF,DF,DHT,DODO,DOUGH,FARM,FARM,FIN,FOR,FXC,GNO,HEGIC,IDEX,IDLE,INDEX,KEEP,KNC,LRC,MATIC,MATIC,MCB,MET,MKR,MLN,MPH,NXS,OPIUM,PEAK,PERL,PICKLE,PIPT,REN,REP,SI,SNOW,SNX,STAKE,SUSHI,SWRV,TORN,TORN,TRADE,TRU,UNI,VALUE,VSP,YAX,YFI,YFII'.split(',')
debank_symbols = '1INCH,AAVE,ACS,ADD,aEth,ALCX,ALPA,ALPACA,ALPHA,AMP,AMPL,ANT,ANY,APY,ARMOR,AST,AUTO,BAC,BADGER,BAG,BAKE,BAL,BAND,BANK,BAS,BASE,BCS,BDO,BDP,BEL,BELT,BNT,BOND,BOR,BSD,BSDS,BSWAP,BT,BUNNY,BZRX,CAKE,COFI,COMBO,COMP,CORE,COVER,CREAM,CRM,CRV,CVP,DAIQ,DDIM,DDX,DEGO,DEGOV,DEXE,DEXTF,DF,DFD,DFT,DHT,DMG,DODO,DOKI,DOS,DOUGH,DRC,DSD,EGG,EPS,ESD,EXRD,FARM,FIN,FL,FNX,FOR,FRAX,FRM,FXS,GET,GHST,GNO,GOF,GRO,GYSR,HAKKA,HEGIC,HELMET,HGET,HOT,ICHI,IDEX,IDLE,INDEX,INV,JRT,JULD,KEEP,KFC,KIMCHI,KNC,KP3R,L2,LDO,LIEN,LINA,LINK,LON,LRC,LUA,MARK,Mars,MCB,MEE,MEME,MINI,MIR,MIS,MKR,MLN,MM,MPH,MTA,N3RDz,NEC,NEST,NRV,NSURE,NXM,ONC,ONES,ONS,OPEN,OPIUM,OPT,ORAI,ORN,PBTC,PEAK,PERL,PERP,PHOON,PICKLE,PLOT,PNT,POOL,POWER,RAI,RAMP,REN,REP,RFI,RGT,ROOK,ROOT,RSR,RSV,SAKE,SASHIMI,SDT,SFG,SFI,SI,SIG,SNOW,SNX,STAKE,STBZ,STN,SUSHI,SWAP,SWINGBY,SWISS,SWRV,SWTH,SYN,TBTC,TCORE,TORN,TRB,TRU,UMA,UMB,UNC,UNCX,UNI,UNN,USF,VALUE,VSP,WARP,wxDai,xBTC,XDEX,XTK,XUSD,XVIX,XVS,YAM,YAX,YF-DAI,YFI,YFII,YFIII,YFL,YVS,ZAI,ZKS,ZRX'.split(',')
tt_symbols = '1INCH,AAVE,BAL,BNB,BNT,BTC,COMP,CREAM,CRV,DCR,DODO,DOGE,DOT,ETH,FIL,FST,GNO,HEGIC,IDEX,KAVA,KNC,KSM,LON,LPT,LRC,LTC,LUNA,MIR,MKR,MTA,NXM,PERP,POOL,QUICK,RAD,RARI,REN,ROOK,SNX,SUSHI,UMA,UNI,XLM,XTZ,YFI,ZEC,ZRX'.split(',')
print(len(merged_symbols), len(cmc_symbols), len(defi_symbols), len(debank_symbols), len(tt_symbols))

102 275 62 210 47

In [6]:
not_in_symbols = []
for dbs in debank_symbols:
    if dbs not in cmc_symbols:
        not_in_symbols.append(dbs)
print(not_in_symbols)
print(len(not_in_symbols))

['ACS', 'aEth', 'ALPA', 'AMP', 'ANT', 'BAC', 'BAG', 'BANK', 'BAS', 'BASE', 'BCS', 'BDO', 'BDP', 'BELT', 'BOND', 'BSD', 'BSDS', 'BSWAP', 'BT', 'BUNNY', 'COFI', 'COVER', 'CRM', 'DAIQ', 'DDIM', 'DEGOV', 'DEXTF', 'DFT', 'DOKI', 'DOS', 'DRC', 'DSD', 'EPS', 'ESD', 'EXRD', 'FL', 'FNX', 'FRAX', 'GET', 'GHST', 'GOF', 'GRO', 'GYSR', 'HELMET', 'ICHI', 'INV', 'JULD', 'KFC', 'KIMCHI', 'L2', 'LINA', 'LON', 'Mars', 'MEE', 'MEME', 'MINI', 'MIS', 'MM', 'MPH', 'N3RDz', 'NEST', 'NRV', 'ONC', 'ONES', 'ONS', 'OPEN', 'OPT', 'ORAI', 'PERL', 'PHOON', 'PLOT', 'POOL', 'POWER', 'RAI', 'RFI', 'ROOK', 'ROOT', 'SAKE', 'SDT', 'SFG', 'SI', 'SIG', 'SNOW', 'STBZ', 'STN', 'SWAP', 'SWISS', 'SYN', 'TCORE', 'TORN', 'UNC', 'UNCX', 'UNN', 'USF', 'wxDai', 'xBTC', 'XDEX', 'XUSD', 'XVIX', 'ZAI', 'ZKS']
101

In [20]:
def get_joins(symbols1, symbols2):
    symbols_list = symbols1.copy()
    for symbol in symbols2:
        if symbol not in symbols1:
            symbols_list.append(symbol)            
    return symbols_list

joined_list = []
joined_list = get_joins(joined_list, merged_symbols)
joined_list = get_joins(joined_list, cmc_symbols)
joined_list = get_joins(joined_list, defi_symbols)
joined_list = get_joins(joined_list, debank_symbols)
joined_list = get_joins(joined_list, tt_symbols)

In [21]:
len(joined_list)

413

In [24]:
joined_list.sort()
','.join(joined_list)

'1INCH,AAVE,ABAT,ABUSD,ACED,ACS,ADA,ADAI,ADD,ADEL,AKNC,AKRO,ALCX,ALINK,ALLOY,ALPA,ALPACA,ALPHA,AMKR,AMP,AMPL,ANT,ANY,APY,APYS,AR,ARMOR,ASNX,ASSY,AST,ATUSD,AUC,AUCTION,AUTO,AVAX,BAC,BADGER,BAG,BAKE,BAL,BANANA,BAND,BANK,BAS,BASE,BCS,BDO,BDP,BEAM,BEL,BELT,BEPRO,BITCNY,BNB,BNT,BOND,BONDLY,BOR,BOT,BOTS,BSD,BSDS,BSWAP,BT,BTC,BTC++,BTS,BUNNY,BUSD,BZRX,CAKE,CAP,CBAT,CC10,CDAI,CHR,CNS,COFI,COMBO,COMP,COOK,CORD,CORE,COTI,COVER,CREAM,CREP,CRM,CRV,CSAI,CUSD,CUSDC,CUSDT,CVP,CWBTC,CZRX,DAI,DAIQ,DAM,DAO,DCL,DCR,DDIM,DDX,DEC,DEFI++,DEFI+L,DEFI+S,DEFI5,DEGEN,DEGO,DEGOV,DEXE,DEXTF,DF,DFD,DFI,DFT,DHT,DIA,DMG,DODO,DOGE,DOKI,DOS,DOT,DOUGH,DOWS,DPI,DRC,DREP,DSD,DUCK,DUSD,DVG,DXD,DYP,EASY,EGG,EONS,EOSDT,EPS,ESD,ETH,ETHY,ETHYS,EXRD,FARM,FEI,FIL,FIN,FIS,FL,FLM,FNX,FONT,FOR,FRAX,FRM,FRONT,FSN,FST,FTM,FXC,FXS,GET,GHST,GNO,GOF,GRO,GRT,GUSD,GYSR,HAKKA,HEGIC,HELMET,HGET,HOT,HUSD,HYPR,ICHI,IDEX,IDLE,IETH,INCH,INDEX,INJ,INV,JRT,JST,JULD,KAVA,KEEP,KFC,KIMCHI,KNC,KP3R,KP4R,KSM,KSP,L2,LDO,LIEN,LINA,LINK,LON,LPT,LRC,LTC,LTX,LUA,LUNA,MARK,MATIC,MATIC,MATTER,MBTC,MCB,MDX,MEE,MEME,MET,MINI,MIR,MIS,MKR,MLN,MM,MPH,MTA,MTRG,MUSD,Mars,N3RDz,NEC,NEST,NEX,NMR,NRV,NSURE,NXM,NXS,OCEAN,OGN,OKS,OM,ONC,ONES,ONS,ONX,OPEN,OPIUM,OPT,ORAI,ORCL5,ORE,ORN,ORO,OXEN,PAX,PBTC,PEAK,PERL,PERP,PHB,PHOON,PICKLE,PIE,PIPT,PLOT,PNT,POLK,POLS,POOL,POWER,PREMIA,QUICK,RAD,RAI,RAMP,RARI,RAY,RBC,REB2,REEF,REN,RENBTC,REP,REQ,RFI,RGT,RLC,ROOK,ROOT,ROT,RSR,RSV,RUNE,SAKE,SASHIMI,SBTC,SCRT,SDEFI,SDT,SETH,SFG,SFI,SHROOM,SI,SIG,SMARTCREDIT,SNOW,SNX,SOCKS,SRM,STAKE,STBZ,STKR,STN,STPT,STRK,STRONG,SUKU,SURE,SUSD,SUSHI,SUTER,SWAP,SWFTC,SWINGBY,SWISS,SWRV,SWTH,SXP,SYN,SYNC,TBTC,TCORE,THX,TKN,TORN,TRADE,TRB,TRIBE,TRU,TRX,TUSD,U8D,UMA,UMB,UNC,UNCX,UNFI,UNI,UNISTAKE,UNN,UQC,USDC,USDK,USDN,USDT,USF,UST,VAI,VALUE,VBNT,VOLTS,VSP,VTX,WAN,WARP,WBTC,WGRT,WHITE,WING,XDEX,XEND,XHV,XLM,XPR,XSUSHI,XTK,XTZ,XUSD,XVIX,XVS,YAM,YAX,YETI,YF-DAI,YFI,YFII,YFIII,YFL,YIELD,YLD,YPIE,YVS,ZAI,ZAP,ZDEX,ZEC,ZEE,ZKS,ZRX,aENJ,aEth,arNXM,ibETH,imBTC,sYFL,wxDai,xBTC'

### method to fetch OHLC for a passes start and end time. symols count should be frater than 1.

In [10]:
def get_historical_data(start_time, end_time, symbols, parsed_data, count = 1000):
    url = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/ohlcv/historical"
    payload = {
        'convert':'USD',
        'time_period':'hourly',
        'time_start':start_time,
        'time_end': end_time,
        'count':count,
        'interval':'hourly',
        'symbol':symbols
    }
    headers = {
      'Accepts': 'application/json',
      'X-CMC_PRO_API_KEY': api_key
    }
#     return requests.get(url, params=payload, headers=headers).json()
#     print(payload)
    try:
        response = requests.get(url, params=payload, headers=headers).json()
        data = response['data']
        get_historical_parsed_data(data, parsed_data, symbols)
        return data
    except Exception:
        print(traceback2.format_exc())
        print(response)

### method to parse the historical OHLC data

In [11]:
def get_historical_parsed_data(data, parsed_data, symbol):
#     print(data)
    if True:
        if 'symbol' in data:
            symbol = data['symbol']
            quotes = data['quotes']
        else:
            quotes = data[symbol]['quotes']
        for row in quotes:
            time_str = row['time_close']
            o = row['quote']['USD']['open']
            h = row['quote']['USD']['high']
            l = row['quote']['USD']['low']
            c = row['quote']['USD']['close']
#             print([time_str, symbol, o, h, l, c])
            parsed_data.append([time_str, symbol, o, h, l, c])
    return parsed_data

### method to fetch data for pased symbols and start and end time. (a looped method for all the symbols). batching the symbols list.

In [12]:
def get_data(start_time, end_time, symbols, parsed_data):
    symbols_size = len(symbols) if 100 > len(symbols) else len(symbols)
    i = 0
    batch_size = 1
    while i <  symbols_size:
        j = i + batch_size
        if j > symbols_size:
            j = symbols_size
        count = 10000
        s = ",".join(symbols[i:j])
        print(f'Index: {i}, Count:{count} Symbols: {s}')
        i = j
        data = get_historical_data(start_time, end_time, s, parsed_data, count)
        time.sleep(2)
#     print(data)

#### fetching OHLC data.

In [14]:
# parsed_data = []
now = datetime.now()
start_time = now #- timedelta(days=3*29, hours=23, minutes = 55)
while start_time <= now:
    end_time = start_time + timedelta(days = 365, seconds = -1)
    if end_time > now:
        end_time = now
    get_data(start_time, end_time, symbols, parsed_data)
    start_time = end_time + timedelta(seconds = 1)

NameError: name 'parsed_data' is not defined

In [13]:
df = pd.DataFrame(parsed_data, columns = ['time','symbol','O', 'H', 'L', 'C'])

In [16]:
df

,time,symbol,O,H,L,C
0,2021-01-11T15:59:59.999Z,UNI,5.124032,5.159632,4.888691,4.916275
1,2021-01-11T16:59:59.999Z,UNI,4.906808,4.906808,4.467273,4.622832
2,2021-01-11T17:59:59.999Z,UNI,4.626230,4.853427,4.508674,4.787256
3,2021-01-11T18:59:59.999Z,UNI,4.789935,4.941852,4.783513,4.870845
4,2021-01-11T19:59:59.999Z,UNI,4.867891,4.872035,4.638070,4.764926
...,...,...,...,...,...,...
508592,2021-04-09T04:59:59.999Z,aENJ,3.158820,3.170295,3.132579,3.170295
508593,2021-04-09T05:59:59.999Z,aENJ,3.170341,3.482147,3.170326,3.482147
508594,2021-04-09T06:59:59.999Z,aENJ,3.475157,3.492558,3.364735,3.464678
508595,2021-04-09T07:59:59.999Z,aENJ,3.464247,3.589826,3.424020,3.510129
508596,2021-04-09T08:59:59.999Z,aENJ,3.524269,3.531693,3.382964,3.389973

### Hourly OHLC data for top 300 coins.

In [15]:
df.drop_duplicates()

,time,symbol,O,H,L,C
0,2021-01-11T15:59:59.999Z,UNI,5.124032,5.159632,4.888691,4.916275
1,2021-01-11T16:59:59.999Z,UNI,4.906808,4.906808,4.467273,4.622832
2,2021-01-11T17:59:59.999Z,UNI,4.626230,4.853427,4.508674,4.787256
3,2021-01-11T18:59:59.999Z,UNI,4.789935,4.941852,4.783513,4.870845
4,2021-01-11T19:59:59.999Z,UNI,4.867891,4.872035,4.638070,4.764926
...,...,...,...,...,...,...
508592,2021-04-09T04:59:59.999Z,aENJ,3.158820,3.170295,3.132579,3.170295
508593,2021-04-09T05:59:59.999Z,aENJ,3.170341,3.482147,3.170326,3.482147
508594,2021-04-09T06:59:59.999Z,aENJ,3.475157,3.492558,3.364735,3.464678
508595,2021-04-09T07:59:59.999Z,aENJ,3.464247,3.589826,3.424020,3.510129
508596,2021-04-09T08:59:59.999Z,aENJ,3.524269,3.531693,3.382964,3.389973

In [16]:
df['time'] = pd.to_datetime(pd.to_datetime(df['time']).dt.strftime('%Y %m %d %H:%M:00'))

In [17]:
coin_df = pd.DataFrame([])

In [18]:
df.index = pd.DatetimeIndex(df['time'])
del df['O']
del df['H']
del df['L']
del df['time']

### Converting data in time vs coin formate. (only having the close_price)

time, BTC, ETH, ADC 

2019-12-12 13:45, 12323, 532, 534

2019-12-12 13:46, 12323, 532, 534

In [19]:
df = df.drop_duplicates(keep='first')
df

                    symbol             C
time
2020-11-13 00:59:00    BTC  16388.495881
2020-11-13 01:59:00    BTC  16422.400050
2020-11-13 02:59:00    BTC  16402.714268
2020-11-13 03:59:00    BTC  16436.176734
2020-11-13 04:59:00    BTC  16392.419990
...                    ...           ...
2021-02-08 13:59:00    LDO      2.636628
2021-02-08 14:59:00    LDO      2.651580
2021-02-08 15:59:00    LDO      2.707967
2021-02-08 16:59:00    LDO      2.663864
2021-02-08 17:59:00    LDO      2.548043

[998809 rows x 2 columns]

In [20]:
df = df.pivot(columns='symbol', values='C')

### saving data in a file.

In [21]:
df.to_csv('coins_data.csv')

In [22]:
df = pd.read_csv('coins_data.csv')
df = df.set_index(df['time'])
del df['time']
df

,1INCH,AAVE,ABBC,ADA,ADK,ADX,AE,AGI,AION,AKRO,...,ZLW,ZNN,ZRX,aEth,vBNB,vBTC,vBUSD,vETH,vUSDT,vXVS
time,,,,,,,,,,,,,,,,,,,,,
2020-11-13 00:59:00,NaN,52.473048,0.235740,0.105107,0.298399,0.267566,0.099931,0.054599,0.069802,0.010028,...,5.091693,2.629108,0.361362,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 01:59:00,NaN,55.083418,0.227004,0.106019,0.299793,0.270614,0.100812,0.054205,0.070485,0.010049,...,5.103402,2.639515,0.365325,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 02:59:00,NaN,57.426488,0.216071,0.105861,0.303231,0.269487,0.101011,0.052973,0.069738,0.009932,...,5.068113,2.680695,0.364849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 03:59:00,NaN,57.742381,0.216975,0.105701,0.294888,0.270711,0.101102,0.053174,0.070383,0.009889,...,5.077858,2.646342,0.367933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 04:59:00,NaN,57.573407,0.217385,0.105696,0.294489,0.269937,0.100939,0.053875,0.070212,0.009723,...,5.066824,2.635170,0.366286,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-08 13:59:00,4.937143,500.136101,0.178421,0.683031,3.733816,0.576137,0.096953,0.105404,0.081598,0.042511,...,4.372287,15.173015,1.499802,1668.718809,1.460842,867.066621,0.020210,33.718864,0.020312,0.592463
2021-02-08 14:59:00,5.133483,514.808556,0.177317,0.685226,3.865189,0.573204,0.097638,0.109648,0.083045,0.044477,...,4.383173,15.203012,1.517876,1672.304128,1.506100,861.048284,0.020214,34.286201,0.020310,0.635757
2021-02-08 15:59:00,5.148776,513.040184,0.178364,0.685779,3.660357,0.574281,0.098357,0.112376,0.083686,0.042978,...,4.381821,14.925420,1.554849,1702.742006,1.486372,874.500347,0.020213,34.852345,0.020320,0.682240
2021-02-08 16:59:00,5.056908,503.462285,0.177647,0.709218,3.741055,0.572425,0.097609,0.112336,0.083885,0.044164,...,4.368032,14.978388,1.529407,1691.785450,1.494557,868.299538,0.020207,34.504196,0.020293,0.706522
2021-02-08 17:59:00,5.109941,498.759355,0.177469,0.705549,3.738392,0.574746,0.097774,0.114062,0.084285,0.045564,...,4.378300,14.935753,1.532780,1688.206263,1.494814,863.901772,0.020213,34.226295,0.020277,0.720768

In [23]:
# symbols = df.columns.values
# df1 = df.reset_index()
# coin_df = pd.DataFrame([])
# coin_df['time'] = df1['time']
# for symbol in symbols:
#     coin_df[symbol] = df1[symbol]
# coin_df.index = pd.DatetimeIndex(coin_df['time'])
# #del coin_df['time']

# del coin_df['time']

In [24]:
data_values_df = pd.DataFrame(df.isna().sum(), columns= ['nan_count'])
tmp_df = pd.DataFrame(df.count(), columns= ['values_count'])
data_values_df['values_count'] = tmp_df['values_count']
data_values_df['rows_count'] = data_values_df['values_count'] + data_values_df['nan_count']
print(data_values_df)
delete_coin_df = data_values_df[data_values_df['nan_count'] > (data_values_df['values_count']*.20)]
delete_coin_df.sort_values(['nan_count'])

       nan_count  values_count  rows_count
1INCH       1015          1091        2106
AAVE           6          2100        2106
ABBC           6          2100        2106
ADA            0          2106        2106
ADK            0          2106        2106
...          ...           ...         ...
vBTC         706          1400        2106
vBUSD        718          1388        2106
vETH         706          1400        2106
vUSDT        706          1400        2106
vXVS         706          1400        2106

[500 rows x 3 columns]

        nan_count  values_count  rows_count
API3          468          1638        2106
BAC           468          1638        2106
SKL           468          1638        2106
EAURIC        468          1638        2106
VAI           475          1631        2106
MIR           516          1590        2106
BADGER        516          1590        2106
RGT           543          1563        2106
WOZX          604          1502        2106
BONDLY        633          1473        2106
vETH          706          1400        2106
vBTC          706          1400        2106
vBNB          706          1400        2106
vUSDT         706          1400        2106
vXVS          706          1400        2106
vBUSD         718          1388        2106
GRT           839          1267        2106
POND          941          1165        2106
DUCK          945          1161        2106
BIFI          967          1139        2106
FIDA          971          1135        2106
STETH         977          1129        2106
aEth          983          1123        2106
DDX           983          1123        2106
LON           984          1122        2106
1INCH        1015          1091        2106
FRAX         1071          1035        2106
FXS          1071          1035        2106
WHITE        1091          1015        2106
REEF         1116           990        2106
SPI          1209           897        2106
BAO          1258           848        2106
COVER        1280           826        2106
LDO          1295           811        2106
NFTX         1304           802        2106
ZKS          1327           779        2106
SNOW         1700           406        2106
DIGG         1706           400        2106
PAID         1782           324        2106
FLOW         1815           291        2106
OPIUM        1818           288        2106
WNXM         1934           172        2106
MAPS         1935           171        2106
LIT          1998           108        2106
BUSD         2085            21        2106
SFP          2101             5        2106

### will delete below coins as most of the values are not available

In [25]:
symbols_del = delete_coin_df.index.tolist()
for symbol in symbols_del:
    print(f'Deleteing Coin: {symbol}')
    del df[symbol]

Deleteing Coin: 1INCH
Deleteing Coin: API3
Deleteing Coin: BAC
Deleteing Coin: BADGER
Deleteing Coin: BAO
Deleteing Coin: BIFI
Deleteing Coin: BONDLY
Deleteing Coin: BUSD
Deleteing Coin: COVER
Deleteing Coin: DDX
Deleteing Coin: DIGG
Deleteing Coin: DUCK
Deleteing Coin: EAURIC
Deleteing Coin: FIDA
Deleteing Coin: FLOW
Deleteing Coin: FRAX
Deleteing Coin: FXS
Deleteing Coin: GRT
Deleteing Coin: LDO
Deleteing Coin: LIT
Deleteing Coin: LON
Deleteing Coin: MAPS
Deleteing Coin: MIR
Deleteing Coin: NFTX
Deleteing Coin: OPIUM
Deleteing Coin: PAID
Deleteing Coin: POND
Deleteing Coin: REEF
Deleteing Coin: RGT
Deleteing Coin: SFP
Deleteing Coin: SKL
Deleteing Coin: SNOW
Deleteing Coin: SPI
Deleteing Coin: STETH
Deleteing Coin: VAI
Deleteing Coin: WHITE
Deleteing Coin: WNXM
Deleteing Coin: WOZX
Deleteing Coin: ZKS
Deleteing Coin: aEth
Deleteing Coin: vBNB
Deleteing Coin: vBTC
Deleteing Coin: vBUSD
Deleteing Coin: vETH
Deleteing Coin: vUSDT
Deleteing Coin: vXVS

In [26]:
df

,AAVE,ABBC,ADA,ADK,ADX,AE,AGI,AION,AKRO,AKT,...,YUSRA,ZAP,ZB,ZCN,ZEC,ZEN,ZIL,ZLW,ZNN,ZRX
time,,,,,,,,,,,,,,,,,,,,,
2020-11-13 00:59:00,52.473048,0.235740,0.105107,0.298399,0.267566,0.099931,0.054599,0.069802,0.010028,0.463789,...,3.697297,0.081410,0.252398,0.232567,62.806251,6.006031,0.019450,5.091693,2.629108,0.361362
2020-11-13 01:59:00,55.083418,0.227004,0.106019,0.299793,0.270614,0.100812,0.054205,0.070485,0.010049,0.461863,...,3.744519,0.083729,0.253304,0.227097,62.598245,6.039218,0.019575,5.103402,2.639515,0.365325
2020-11-13 02:59:00,57.426488,0.216071,0.105861,0.303231,0.269487,0.101011,0.052973,0.069738,0.009932,0.458634,...,3.734337,0.082124,0.253019,0.226751,62.490047,6.036562,0.019636,5.068113,2.680695,0.364849
2020-11-13 03:59:00,57.742381,0.216975,0.105701,0.294888,0.270711,0.101102,0.053174,0.070383,0.009889,0.450044,...,3.734013,0.082645,0.253261,0.226770,62.296230,6.094835,0.019711,5.077858,2.646342,0.367933
2020-11-13 04:59:00,57.573407,0.217385,0.105696,0.294489,0.269937,0.100939,0.053875,0.070212,0.009723,0.445543,...,3.724814,0.087140,0.252092,0.227399,62.236793,6.213114,0.019671,5.066824,2.635170,0.366286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-08 13:59:00,500.136101,0.178421,0.683031,3.733816,0.576137,0.096953,0.105404,0.081598,0.042511,2.354254,...,4.133004,0.118342,0.338985,0.773102,95.540161,34.592875,0.078414,4.372287,15.173015,1.499802
2021-02-08 14:59:00,514.808556,0.177317,0.685226,3.865189,0.573204,0.097638,0.109648,0.083045,0.044477,2.402078,...,4.036433,0.114652,0.333365,0.775996,95.711816,35.096094,0.079497,4.383173,15.203012,1.517876
2021-02-08 15:59:00,513.040184,0.178364,0.685779,3.660357,0.574281,0.098357,0.112376,0.083686,0.042978,2.390591,...,4.073141,0.115808,0.337383,0.798323,96.048793,34.903733,0.079765,4.381821,14.925420,1.554849
2021-02-08 16:59:00,503.462285,0.177647,0.709218,3.741055,0.572425,0.097609,0.112336,0.083885,0.044164,2.413460,...,4.037799,0.108277,0.334018,0.782471,95.756719,34.790490,0.079681,4.368032,14.978388,1.529407
2021-02-08 17:59:00,498.759355,0.177469,0.705549,3.738392,0.574746,0.097774,0.114062,0.084285,0.045564,2.451161,...,4.087764,0.109936,0.335047,0.774061,95.812988,34.791308,0.079609,4.378300,14.935753,1.532780

In [27]:
df.index = pd.DatetimeIndex(df.index)

In [28]:
df.ffill(inplace=True)
data_values_df = pd.DataFrame(df.isna().sum(), columns= ['nan_count'])
tmp_df = pd.DataFrame(df.count(), columns= ['values_count'])
data_values_df['values_count'] = tmp_df['values_count']
data_values_df['rows_count'] = data_values_df['values_count'] + data_values_df['nan_count']
# print(data_values_df)
delete_coin_df = data_values_df[data_values_df['nan_count'] > 10]
delete_coin_df.sort_values(['nan_count'])

      nan_count  values_count  rows_count
SFI          63          2043        2106
BCHA         81          2025        2106
HBTC        147          1959        2106
ROSE        152          1954        2106
UNFI        171          1935        2106
MPH         221          1885        2106
TRU         229          1877        2106
MARK        283          1823        2106
L2          292          1814        2106
UST         299          1807        2106

### scalling up the price as most of the values are less than 1

In [29]:
df = df.fillna(1)*1000

In [30]:
df

,AAVE,ABBC,ADA,ADK,ADX,AE,AGI,AION,AKRO,AKT,...,YUSRA,ZAP,ZB,ZCN,ZEC,ZEN,ZIL,ZLW,ZNN,ZRX
time,,,,,,,,,,,,,,,,,,,,,
2020-11-13 00:59:00,52473.048288,235.740357,105.107472,298.399363,267.565885,99.930894,54.599380,69.801560,10.028442,463.788951,...,3697.297073,81.410325,252.397974,232.566602,62806.251135,6006.031422,19.450178,5091.692860,2629.108075,361.361582
2020-11-13 01:59:00,55083.418315,227.004074,106.019093,299.792966,270.613623,100.812303,54.204704,70.485129,10.048895,461.862836,...,3744.519363,83.728874,253.303634,227.097034,62598.245041,6039.217914,19.575157,5103.401986,2639.515407,365.325043
2020-11-13 02:59:00,57426.487837,216.070935,105.861356,303.230664,269.487214,101.011222,52.973084,69.738499,9.932437,458.633793,...,3734.336932,82.123820,253.019093,226.751484,62490.047026,6036.561966,19.636255,5068.113295,2680.695044,364.849332
2020-11-13 03:59:00,57742.380801,216.974933,105.701133,294.887613,270.711259,101.102385,53.174260,70.382887,9.888824,450.044018,...,3734.013086,82.645471,253.261459,226.770289,62296.229597,6094.834590,19.710947,5077.858065,2646.342293,367.933404
2020-11-13 04:59:00,57573.406802,217.385073,105.696376,294.488882,269.937400,100.939462,53.874707,70.212262,9.722653,445.542758,...,3724.814229,87.139501,252.091954,227.399143,62236.792720,6213.113672,19.670815,5066.824311,2635.170338,366.286289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-08 13:59:00,500136.100671,178.420506,683.030516,3733.815780,576.136617,96.953231,105.403907,81.598286,42.511387,2354.253907,...,4133.003820,118.342442,338.985321,773.101956,95540.161196,34592.874504,78.414307,4372.286600,15173.014851,1499.801694
2021-02-08 14:59:00,514808.556344,177.317226,685.226209,3865.189194,573.203979,97.637598,109.648047,83.045479,44.476795,2402.078146,...,4036.433208,114.651646,333.364753,775.996291,95711.816167,35096.094205,79.496734,4383.172859,15203.012009,1517.876158
2021-02-08 15:59:00,513040.183604,178.363541,685.778820,3660.357330,574.280902,98.356724,112.375704,83.686493,42.977507,2390.590568,...,4073.141462,115.807703,337.382861,798.323292,96048.792745,34903.732564,79.765040,4381.820577,14925.419936,1554.848530
2021-02-08 16:59:00,503462.284979,177.646717,709.217646,3741.054843,572.425035,97.609233,112.335509,83.885260,44.163998,2413.460351,...,4037.798927,108.277120,334.018248,782.471081,95756.719129,34790.490078,79.680821,4368.032153,14978.388260,1529.406742
2021-02-08 17:59:00,498759.355199,177.469336,705.549211,3738.392011,574.745719,97.774005,114.062047,84.284993,45.563973,2451.160548,...,4087.764469,109.936336,335.047181,774.061051,95812.987981,34791.307519,79.609163,4378.300100,14935.753147,1532.779624

## coins that will be used in portfolio cretions

In [31]:
print(df.columns.values)

['AAVE' 'ABBC' 'ADA' 'ADK' 'ADX' 'AE' 'AGI' 'AION' 'AKRO' 'AKT' 'ALBT'
 'ALEPH' 'ALGO' 'ALPHA' 'AMP' 'AMPL' 'ANKR' 'ANT' 'ANY' 'AR' 'ARDR' 'ARK'
 'ARPA' 'ARRR' 'AST' 'ASTA' 'ATOM' 'ATT' 'AUDIO' 'AVA' 'AVAX' 'AXEL' 'AXS'
 'BAKE' 'BAL' 'BAND' 'BASIC' 'BASID' 'BAT' 'BCD' 'BCH' 'BCHA' 'BCN' 'BDX'
 'BEAM' 'BEL' 'BEST' 'BHAO' 'BLCT' 'BLZ' 'BNANA' 'BNB' 'BNK' 'BNT' 'BOA'
 'BOND' 'BOR' 'BORA' 'BOT' 'BOTX' 'BPS' 'BRG' 'BSV' 'BTC' 'BTCB' 'BTG'
 'BTM' 'BTMX' 'BTRS' 'BTS' 'BTT' 'BTU' 'BURGER' 'BZRX' 'CAKE' 'CAS' 'CCA'
 'CCXX' 'CEL' 'CELO' 'CELR' 'CENNZ' 'CHSB' 'CHZ' 'CIPHC' 'CKB' 'CND'
 'COCOS' 'COMP' 'CORE' 'COS' 'COTI' 'CRD' 'CRE' 'CREAM' 'CRO' 'CRV' 'CTC'
 'CTK' 'CTSI' 'CTXC' 'CUSD' 'CVC' 'CVP' 'CVT' 'DAD' 'DAI' 'DASH' 'DATA'
 'DCR' 'DDIM' 'DENT' 'DEXT' 'DF' 'DFI' 'DGB' 'DGD' 'DIA' 'DIP' 'DIVI'
 'DMCH' 'DNT' 'DODO' 'DOGE' 'DOT' 'DRGN' 'DRS' 'DUCATO' 'DUSK' 'DX' 'EASY'
 'EDG' 'EGLD' 'ELA' 'ELF' 'EMC2' 'ENJ' 'EOS' 'ERG' 'ESD' 'ETC' 'ETH' 'ETN'
 'EUM' 'EURS' 'EWT' 'FARM' 'FET' 'FIL' 'FIO' 'FIRO' 'FLG' 'FLM' 'FRM'
 'FSN' 'FST' 'FTM' 'FTT' 'FUN' 'GALA' 'GEO' 'GLEEC' 'GLM' 'GNO' 'GNY'
 'GRIN' 'GRN' 'GRS' 'GT' 'GXC' 'HARD' 'HBAR' 'HBTC' 'HC' 'HEDG' 'HEGIC'
 'HEX' 'HEZ' 'HIVE' 'HMR' 'HNC' 'HNS' 'HNT' 'HOT' 'HPT' 'HT' 'HUSD' 'HXRO'
 'ICH' 'ICX' 'IDEX' 'IGNIS' 'INB' 'INJ' 'INO' 'IOST' 'IOTX' 'IQ' 'IRIS'
 'IZE' 'JST' 'KAI' 'KAVA' 'KCS' 'KDA' 'KEEP' 'KIN' 'KLV' 'KMD' 'KNC'
 'KP3R' 'KRT' 'KSM' 'L2' 'LAMB' 'LBC' 'LEO' 'LGCY' 'LINA' 'LINK' 'LOKI'
 'LOOM' 'LPT' 'LRC' 'LRG' 'LSK' 'LTC' 'LTO' 'LUNA' 'MAID' 'MANA' 'MARK'
 'MASS' 'MATH' 'MATIC' 'MBN' 'MCO' 'MDT' 'MEME' 'MET' 'MFT' 'MIN' 'MIOTA'
 'MKR' 'MLN' 'MONA' 'MPH' 'MRPH' 'MTA' 'MTC' 'MTL' 'MTXLT' 'MUSD' 'MVL'
 'MWC' 'MX' 'MXC' 'NANO' 'NAS' 'NAV' 'NEAR' 'NEO' 'NEST' 'NEXO' 'NIM'
 'NKN' 'NMR' 'NOIA' 'NPXS' 'NRG' 'NSBT' 'NU' 'NULS' 'NXM' 'NXS' 'NYE'
 'OCEAN' 'OCTO' 'OGN' 'OKB' 'OM' 'OMG' 'ONE' 'ONT' 'ORBS' 'ORC' 'ORN'
 'OXT' 'PAX' 'PAXG' 'PCX' 'PEAK' 'PERL' 'PERP' 'PHA' 'PICKLE' 'PIVX' 'PNK'
 'POLS' 'POLY' 'POWR' 'PPT' 'PRE' 'PROM' 'PRQ' 'PZM' 'QC' 'QKC' 'QNT'
 'QQQ' 'QRL' 'QSP' 'QTUM' 'RAMP' 'RBTC' 'RCN' 'RDD' 'REN' 'RENBTC' 'REP'
 'REQ' 'REV' 'REW' 'RIF' 'RING' 'RKN' 'RLC' 'ROSE' 'RPL' 'RSR' 'RUNE'
 'RVN' 'SALT' 'SAND' 'SAPP' 'SC' 'SCC' 'SCRT' 'SERO' 'SFI' 'SHR' 'SNL'
 'SNT' 'SNTVT' 'SNX' 'SOL' 'SOLO' 'SOLVE' 'SPARTA' 'SRK' 'SRM' 'STAKE'
 'STAX' 'STEEM' 'STMX' 'STORJ' 'STPT' 'STRAX' 'STRONG' 'STX' 'SUN' 'SUSD'
 'SUSHI' 'SWAP' 'SWTH' 'SXP' 'SYS' 'TEL' 'TFUEL' 'THETA' 'THR' 'THX'
 'TITAN' 'TLOS' 'TMTG' 'TNC' 'TOMO' 'TRAC' 'TRB' 'TROY' 'TRU' 'TRX' 'TT'
 'TTT' 'TUSD' 'TWT' 'TXL' 'UBT' 'ULT' 'UMA' 'UNFI' 'UNI' 'UOS' 'UQC'
 'USDC' 'USDK' 'USDN' 'USDT' 'USDX' 'UST' 'UTK' 'VERI' 'VET' 'VGX' 'VIDT'
 'VITAE' 'VLX' 'VRSC' 'VSYS' 'VTHO' 'WAN' 'WAVES' 'WAXP' 'WBNB' 'WBTC'
 'WEST' 'WICC' 'WIN' 'WOO' 'WRX' 'WTC' 'WXT' 'XCM' 'XDC' 'XEM' 'XHV' 'XIN'
 'XLM' 'XLT' 'XMR' 'XNC' 'XOR' 'XPR' 'XRP' 'XRT' 'XSN' 'XTZ' 'XVG' 'XVS'
 'XWC' 'YFI' 'YFII' 'YFL' 'YOUC' 'YUSRA' 'ZAP' 'ZB' 'ZCN' 'ZEC' 'ZEN'
 'ZIL' 'ZLW' 'ZNN' 'ZRX']

In [32]:
print(len(df.columns.values))

454

### calculating the 14 days percentage change. 
As data is hourly, so shifting 24*7*2 rows to get the 14 days pct change

In [33]:
_14_days_pct_change_df = df.pct_change(periods=24*7*2)
_14_days_pct_change_df

,AAVE,ABBC,ADA,ADK,ADX,AE,AGI,AION,AKRO,AKT,...,YUSRA,ZAP,ZB,ZCN,ZEC,ZEN,ZIL,ZLW,ZNN,ZRX
time,,,,,,,,,,,,,,,,,,,,,
2020-11-13 00:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 01:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 02:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 03:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 04:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-08 13:59:00,0.928504,-0.132454,0.902113,0.862074,0.332897,0.161739,0.294243,0.021322,1.633275,0.369483,...,0.072792,0.228397,0.232990,0.072482,0.005778,0.026931,0.107968,-0.001953,2.254073,1.721774
2021-02-08 14:59:00,1.037712,-0.129465,0.912065,0.927112,0.333534,0.176283,0.358112,0.051105,1.790772,0.396714,...,0.048438,0.186194,0.208621,0.153696,0.017438,-0.022476,0.133863,0.003156,2.323559,1.771597
2021-02-08 15:59:00,0.998375,-0.132382,0.893026,0.825305,0.342596,0.184537,0.403225,0.068420,1.664512,0.389423,...,0.064330,0.198482,0.229569,0.183233,0.022842,-0.065513,0.134599,0.003676,2.432744,1.820162
2021-02-08 16:59:00,1.012660,-0.125149,0.995649,0.899987,0.308208,0.140375,0.409070,0.061016,1.832906,0.452233,...,0.057011,0.142541,0.218255,0.173978,0.025334,-0.065341,0.153052,0.009968,2.421324,1.819082
2021-02-08 17:59:00,1.001439,-0.132747,0.985829,0.901508,0.300569,0.150945,0.438113,0.065683,1.647898,0.483076,...,0.072781,0.155907,0.217778,0.160101,0.029196,-0.043792,0.153031,0.034177,2.496919,1.835332

### calculating the 7 days percentage change. 
As data is hourly, so shifting 7*24 rows to get the 7 days pct change

In [34]:
_7_days_pct_change_df = df.pct_change(periods=7*24)

In [35]:
_7_days_pct_change_df

,AAVE,ABBC,ADA,ADK,ADX,AE,AGI,AION,AKRO,AKT,...,YUSRA,ZAP,ZB,ZCN,ZEC,ZEN,ZIL,ZLW,ZNN,ZRX
time,,,,,,,,,,,,,,,,,,,,,
2020-11-13 00:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 01:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 02:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 03:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 04:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-08 13:59:00,0.737445,0.021260,0.954456,0.779188,0.429544,0.090962,0.363700,0.147171,1.447648,0.468913,...,0.074255,0.575664,0.199143,-0.144234,0.102249,-0.019989,0.117704,0.004034,1.111717,1.299700
2021-02-08 14:59:00,0.784496,0.008555,0.982280,0.861776,0.428414,0.092787,0.377431,0.173031,1.638767,0.499177,...,0.049811,0.458342,0.178799,-0.103306,0.111620,-0.014307,0.145956,0.006214,1.100815,1.327917
2021-02-08 15:59:00,0.766253,0.035442,0.954227,0.789009,0.433516,0.080852,0.413179,0.182032,1.557741,0.490530,...,0.056836,0.180417,0.187435,-0.054421,0.112636,-0.030177,0.124213,0.005911,1.071667,1.364461
2021-02-08 16:59:00,0.731870,0.027625,1.011326,0.813627,0.417178,0.096217,0.425244,0.179821,1.582881,0.509056,...,0.054247,0.125103,0.181899,-0.084851,0.108272,-0.033027,0.113951,0.001686,1.096656,1.285751
2021-02-08 17:59:00,0.674432,0.018385,0.974648,0.795087,0.415741,0.101150,0.487044,0.187762,1.619053,0.513229,...,0.056566,0.156423,0.174525,-0.128925,0.107223,-0.041783,0.094427,0.005014,1.171322,1.332817

#### Benchmark: For benchmark, taking ETH 7 days pct change as benchmarking

In [36]:
_eth_7_days_pct_change_df = _7_days_pct_change_df['ETH'].copy()

In [37]:
_eth_7_days_pct_change_df

time
2020-11-13 00:59:00         NaN
2020-11-13 01:59:00         NaN
2020-11-13 02:59:00         NaN
2020-11-13 03:59:00         NaN
2020-11-13 04:59:00         NaN
                         ...
2021-02-08 13:59:00    0.266131
2021-02-08 14:59:00    0.301992
2021-02-08 15:59:00    0.326793
2021-02-08 16:59:00    0.312615
2021-02-08 17:59:00    0.294940
Name: ETH, Length: 2106, dtype: float64

### As in the inital requiremnt
-# 7-day rel pct change (coin_pct_change - eth_pct_chg)

#### this method substract the benchmarked ETH 7 days pct change data to every coin's 7 days pct change

In [38]:
def benchmark_with_eth(df, eth_df, symbols):
    columns = df.columns
    for symbol in symbols:
#         print(symbol)
        if symbol not in columns:
            continue
        tmp = df[symbol]
#         print(tmp)
        if not tmp.empty and symbol != 'ETH':
            df[symbol] = df[symbol] - eth_df
    return df

In [39]:
rel_pct_change = benchmark_with_eth(_7_days_pct_change_df.copy(), _eth_7_days_pct_change_df, symbols)

In [40]:
rel_pct_change

,AAVE,ABBC,ADA,ADK,ADX,AE,AGI,AION,AKRO,AKT,...,YUSRA,ZAP,ZB,ZCN,ZEC,ZEN,ZIL,ZLW,ZNN,ZRX
time,,,,,,,,,,,,,,,,,,,,,
2020-11-13 00:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 01:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 02:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 03:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 04:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-08 13:59:00,0.471314,-0.244871,0.688325,0.513057,0.163413,-0.175169,0.097569,-0.118960,1.181517,0.202782,...,-0.191876,0.309533,-0.066988,-0.410365,-0.163882,-0.286120,-0.148427,-0.262097,0.845586,1.033569
2021-02-08 14:59:00,0.482504,-0.293437,0.680288,0.559784,0.126422,-0.209205,0.075440,-0.128960,1.336775,0.197186,...,-0.252180,0.156350,-0.123193,-0.405298,-0.190372,-0.316299,-0.156036,-0.295778,0.798824,1.025925
2021-02-08 15:59:00,0.439460,-0.291352,0.627433,0.462215,0.106723,-0.245941,0.086386,-0.144761,1.230948,0.163737,...,-0.269958,-0.146376,-0.139358,-0.381215,-0.214157,-0.356971,-0.202581,-0.320882,0.744873,1.037667
2021-02-08 16:59:00,0.419255,-0.284990,0.698711,0.501012,0.104563,-0.216397,0.112630,-0.132794,1.270266,0.196442,...,-0.258368,-0.187512,-0.130715,-0.397466,-0.204343,-0.345642,-0.198664,-0.310928,0.784041,0.973136
2021-02-08 17:59:00,0.379492,-0.276555,0.679708,0.500147,0.120801,-0.193790,0.192104,-0.107178,1.324113,0.218289,...,-0.238374,-0.138517,-0.120415,-0.423864,-0.187717,-0.336723,-0.200513,-0.289926,0.876382,1.037877

# rank all coins on 7-day rel_pct_change

to rank the coind, taking last row  data and sorting it based on the pct change

In [41]:
last_row_df = rel_pct_change[-1:]

In [42]:
columns = last_row_df.columns.values
values = last_row_df[0:].values

In [43]:
def convert_to_df(columns, values):
    data = []
    for i in range (0, len(columns)):
        data.append([columns[i], values[i]])
    return pd.DataFrame(data, columns=['symbol', 'rel_pct_change'])

In [44]:
rel_pct_change_df_sorted_on_last_row = convert_to_df(columns, values[0])

In [45]:
rel_pct_change_df_sorted_on_last_row

    symbol  rel_pct_change
0     AAVE        0.379492
1     ABBC       -0.276555
2      ADA        0.679708
3      ADK        0.500147
4      ADX        0.120801
..     ...             ...
449    ZEN       -0.336723
450    ZIL       -0.200513
451    ZLW       -0.289926
452    ZNN        0.876382
453    ZRX        1.037877

[454 rows x 2 columns]

#### top 7 coins based on 7 days pct change (benchmarked on ETH 7 days pct change)

In [46]:
rel_pct_change_df_sorted_on_last_row.sort_values(['rel_pct_change']).tail(7)

    symbol  rel_pct_change
371    THX        2.341055
386    TXL        2.468892
251  MTXLT        2.490339
160    GEO        3.132345
367    TEL        3.771177
18     ANY        4.074286
159   GALA        4.586235

### calculating the hourly percentage change. 
As data is hourly, so shifting 1 rows to get the hourly pct change

In [47]:
hourly_pct_df = df.pct_change(periods=1)

### coin_div: 

#### as in initial requirment :
coin_div -> benchmark (eth) -, where(eth -, pct_chg of coin, otherwise 0)

#### as in review:
use hourly pct change to calculate coin_div.  it should be 0 when eth hourly pct change is positive, and the pct change of the coin in hours when eth hourly pct change is negative

Based on above requirment below wethod will update hourly pct change for all the coins other that ETH as ETH is the bench mark here. and the logic is as below,

#### if eth hourly_pct_change is +ve, then the coin hourly_pct_change will be 0

#### if eht hourly_pct_change is -ve, then the coin hourly_pct_change will be the coin hourly_pct_change (no change)

In [48]:
def update_coin_devi(df):
    df = df.copy()
    columns = df.columns
    for ind in df.index:
        for symbol in columns:
            if 'ETH' != symbol:
                df[symbol][ind] = 0 if df['ETH'][ind] >= 0 else df[symbol][ind]
    return df

In [49]:
coin_div = update_coin_devi(hourly_pct_df)

In [50]:
coin_div

,AAVE,ABBC,ADA,ADK,ADX,AE,AGI,AION,AKRO,AKT,...,YUSRA,ZAP,ZB,ZCN,ZEC,ZEN,ZIL,ZLW,ZNN,ZRX
time,,,,,,,,,,,,,,,,,,,,,
2020-11-13 00:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 01:59:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-11-13 02:59:00,0.042537,-0.048163,-0.001488,0.011467,-0.004162,0.001973,-0.022722,-0.010593,-0.011589,-0.006991,...,-0.002719,-0.019170,-0.001123,-0.001522,-0.001728,-0.000440,0.003121,-0.006915,0.015601,-0.001302
2020-11-13 03:59:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-11-13 04:59:00,-0.002926,0.001890,-0.000045,-0.001352,-0.002859,-0.001611,0.013173,-0.002424,-0.016804,-0.010002,...,-0.002464,0.054377,-0.004618,0.002773,-0.000954,0.019406,-0.002036,-0.002173,-0.004222,-0.004477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-08 13:59:00,-0.015159,-0.022104,-0.003218,-0.017407,0.005414,-0.020863,-0.027321,-0.019297,-0.061008,-0.006370,...,0.008552,0.011398,0.010037,-0.027692,0.015064,-0.025203,-0.035891,0.002875,0.037203,0.002882
2021-02-08 14:59:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2021-02-08 15:59:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2021-02-08 16:59:00,-0.018669,-0.004019,0.034178,0.022046,-0.003232,-0.007600,-0.000358,0.002375,0.027607,0.009567,...,-0.008677,-0.065027,-0.009973,-0.019857,-0.003041,-0.003244,-0.001056,-0.003147,0.003549,-0.016363
2021-02-08 17:59:00,-0.009341,-0.000999,-0.005173,-0.000712,0.004054,0.001688,0.015369,0.004765,0.031699,0.015621,...,0.012374,0.015324,0.003080,-0.010748,0.000588,0.000023,-0.000899,0.002351,-0.002846,0.002205

### neg_div_score: 
#### initial ask:
neg_div_coin = coin_div.rolling(7 days).sum
#### Based in the review/comment
neg_div_score/coin is then the rolling 24*7 period (7-day) mean of the coin_div

as coin_div is hourly pct_changed benchedmarked on ETH, to get the **neg_div_score/coin**, will get mean over **24*7**rows of window data. i.e rolling_window = **24*7** and then the mean of that.

In [51]:
neg_div_score = coin_div.rolling(24*7).mean()
neg_div_score

,AAVE,ABBC,ADA,ADK,ADX,AE,AGI,AION,AKRO,AKT,...,YUSRA,ZAP,ZB,ZCN,ZEC,ZEN,ZIL,ZLW,ZNN,ZRX
time,,,,,,,,,,,,,,,,,,,,,
2020-11-13 00:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 01:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 02:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 03:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 04:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-08 13:59:00,-0.002748,-0.001773,-0.001530,-0.000261,-0.001644,-0.000219,-0.001795,-0.000951,-0.002254,0.000751,...,0.000258,0.001877,-0.000077,-0.004352,-0.000809,-0.002600,-0.001972,0.000334,0.001442,-0.001183
2021-02-08 14:59:00,-0.002761,-0.001811,-0.001466,-0.000197,-0.001618,-0.000251,-0.001973,-0.000923,-0.002078,0.000752,...,0.000262,0.001599,-0.000079,-0.004102,-0.000770,-0.002652,-0.001905,0.000332,0.001399,-0.001182
2021-02-08 15:59:00,-0.002802,-0.001691,-0.001556,-0.000111,-0.001608,-0.000361,-0.001967,-0.000923,-0.002060,0.000747,...,0.000248,0.000123,-0.000107,-0.003956,-0.000785,-0.002716,-0.002041,0.000332,0.001426,-0.001233
2021-02-08 16:59:00,-0.002913,-0.001715,-0.001352,0.000020,-0.001628,-0.000406,-0.001969,-0.000909,-0.001895,0.000804,...,0.000196,-0.000264,-0.000166,-0.004075,-0.000803,-0.002735,-0.002047,0.000313,0.001447,-0.001330
2021-02-08 17:59:00,-0.002968,-0.001721,-0.001383,0.000016,-0.001603,-0.000396,-0.001877,-0.000880,-0.001707,0.000897,...,0.000270,-0.000173,-0.000148,-0.004139,-0.000800,-0.002735,-0.002052,0.000327,0.001430,-0.001317

In [52]:
neg_div_score['BTC']

time
2020-11-13 00:59:00         NaN
2020-11-13 01:59:00         NaN
2020-11-13 02:59:00         NaN
2020-11-13 03:59:00         NaN
2020-11-13 04:59:00         NaN
                         ...
2021-02-08 13:59:00   -0.001381
2021-02-08 14:59:00   -0.001349
2021-02-08 15:59:00   -0.001297
2021-02-08 16:59:00   -0.001369
2021-02-08 17:59:00   -0.001397
Name: BTC, Length: 2106, dtype: float64

### 14 days neg_div_score

In [53]:
_14_neg_div_score = coin_div.rolling(24*7*2).mean()
_14_neg_div_score

,AAVE,ABBC,ADA,ADK,ADX,AE,AGI,AION,AKRO,AKT,...,YUSRA,ZAP,ZB,ZCN,ZEC,ZEN,ZIL,ZLW,ZNN,ZRX
time,,,,,,,,,,,,,,,,,,,,,
2020-11-13 00:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 01:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 02:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 03:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-13 04:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-08 13:59:00,-0.002867,-0.002347,-0.002357,-0.001918,-0.002523,-0.000395,-0.002385,-0.001794,-0.003132,0.000016,...,0.000017,-0.002103,-0.000388,-0.003846,-0.001354,-0.003138,-0.003029,-0.000233,-0.001296,-0.002477
2021-02-08 14:59:00,-0.002790,-0.002318,-0.002351,-0.001919,-0.002507,-0.000379,-0.002359,-0.001761,-0.003094,0.000015,...,0.000019,-0.002113,-0.000398,-0.003647,-0.001325,-0.003334,-0.003002,-0.000225,-0.001240,-0.002459
2021-02-08 15:59:00,-0.002790,-0.002318,-0.002351,-0.001919,-0.002507,-0.000379,-0.002359,-0.001761,-0.003094,0.000015,...,0.000019,-0.002113,-0.000398,-0.003647,-0.001325,-0.003334,-0.003002,-0.000225,-0.001240,-0.002459
2021-02-08 16:59:00,-0.002769,-0.002294,-0.002193,-0.001799,-0.002585,-0.000494,-0.002347,-0.001782,-0.002912,0.000145,...,-0.000001,-0.002249,-0.000425,-0.003670,-0.001318,-0.003334,-0.002954,-0.000206,-0.001250,-0.002460
2021-02-08 17:59:00,-0.002786,-0.002320,-0.002207,-0.001797,-0.002602,-0.000466,-0.002286,-0.001769,-0.003127,0.000208,...,0.000043,-0.002214,-0.000426,-0.003705,-0.001307,-0.003267,-0.002954,-0.000137,-0.001186,-0.002443

In [54]:
def get_next_trading_day_as_index(start_date, hour):
    return pd.to_datetime((start_date + timedelta(days = 1) ).replace(hour=hour, minute=59, second=0).strftime("%Y %m %d %H:%M:00"))

#### this method will ran whether the passed symbols is in top n or not on the given date

In [55]:
def is_symbol_in_top_n(df, symbol, trade_date, max_rank):
    data = df.loc[trade_date]
    data = pd.DataFrame(data)
    data = data.rename(columns={data.columns[0]:'C'})
    todays_close_df = pd.DataFrame(data)
    todays_close_df = todays_close_df.sort_values(['C']).tail(max_rank)
    try:
        tmp = todays_close_df.loc[symbol]
        return True
    except:
        return False

### returns the close price of the symbol on given date and time.

In [56]:
def get_close_price_on(df, symbol, trade_date):
    data = df.loc[trade_date]
    data = pd.DataFrame(data)
    data = data.rename(columns={data.columns[0]:'C'})
    todays_close_df = pd.DataFrame(data)
    try:
        return todays_close_df.loc[symbol]['C']
    except:
        return 0

In [57]:
def trade_for_symbol(symbol):    
    #trade start date
    now = datetime.now()
    start_time = now - timedelta(days=3*29, hours=23, minutes = 55)
    start_balance = 10000
    trades = []
    #trading hour
    hour = 16
    trade_date = start_time + timedelta(days=7)
    trade_date = get_next_trading_day_as_index(trade_date, hour)
    positions = False
    # top n symbols based on the 7 days pct change
    top_7_days_pct_symbols_pct = int(1 * len(_7_days_pct_change_df.columns.values))
    top_negdic_score_symbols_pct = int(1 * len(_7_days_pct_change_df.columns.values))
    # max holding period
    max_hold = 6

    holding = 0
    trade_id = 1
    last_buy = [trade_date, 0, 0, 0, 0, start_balance]
    while trade_date.timestamp() < now.timestamp():
        is_symbol_in_top = is_symbol_in_top_n(_7_days_pct_change_df.copy(), symbol, trade_date, top_7_days_pct_symbols_pct) and is_symbol_in_top_n(neg_div_score.copy(), symbol, trade_date, top_negdic_score_symbols_pct) 
        todays_close = get_close_price_on(df.copy(), symbol, trade_date)
    #     print(f"trade_date:{trade_date} close:{todays_close} positions:{positions} is_symbol_in_top_n:{is_symbol_in_top_n} holding:{holding}")
        if todays_close <= 0:
            last_buy[0] = trade_date
            last_buy[2] = todays_close
            last_buy[1] = 0
            trades.append(last_buy)
        elif positions and ( not is_symbol_in_top or max_hold == holding):
            #Sell
#             print(f'{start_balance}  {last_buy[3]} ')
            start_balance = last_buy[5] + (last_buy[3] * ( todays_close - last_buy[2]))
            last_buy = [trade_date, 1, todays_close, last_buy[3], last_buy[4], start_balance]
#             print(last_buy)
            trades.append(last_buy)
            trade_id = trade_id + 1
#             positions = False
            #Buy
#             print(f'{start_balance/todays_close} {start_balance} {todays_close}')
            last_buy = [trade_date, 2, todays_close, start_balance/todays_close, trade_id, start_balance]
            trades.append(last_buy)
#             print(last_buy)
            holding = -1
            positions = True
        elif not positions and is_symbol_in_top:
            positions = True
            last_buy = [trade_date, 2, todays_close, start_balance/todays_close, trade_id, start_balance]
            trades.append(last_buy)
        elif len(last_buy):
            trades.append([trade_date, 0, todays_close, last_buy[3], trade_id, last_buy[3]*todays_close])
#             print(holding)
#             trades.append(last_buy)

        holding = holding + 1
#         print(last_buy)
#         print(f'{top_7_days_pct_symbols_pct} {top_negdic_score_symbols_pct}')
        trade_date = get_next_trading_day_as_index(trade_date, hour)
    trade_df = pd.DataFrame(trades, columns=['time','side','close','positions','trade_id', 'today_balance'])
#     if not trade_df.empty:
#         trade_df[['today_balance','close']].plot(title=symbol)
#     print(trade_df)
    return trade_df

In [58]:
trade_start_date = start_time + timedelta(days=0)

In [59]:
trade_start_date = get_next_trading_day_as_index(trade_start_date, 16)
trade_start_date

Timestamp('2021-02-09 16:59:00')

In [60]:
_7_day_df

NameError: name '_7_day_df' is not defined

In [ ]:
now = datetime.now()
start_time = now - timedelta(days=3*29, hours=23, minutes = 55)
trade_start_date = start_time + timedelta(days=0)
trade_start_date = get_next_trading_day_as_index(trade_start_date, 16)
_7_day_df = _7_days_pct_change_df.copy()
data = _7_day_df.loc[trade_start_date]
data = pd.DataFrame(data)
data = data.rename(columns={data.columns[0]:'C'})
todays_close_df = pd.DataFrame(data)
# selectiong to top n symbols in portfolio.
todays_close_df = todays_close_df.sort_values(['C']).head(4)
top_coin_symbols = todays_close_df.index.values
print(f"Portfolio symbols: {top_coin_symbols}")
symbol_trades = {}
for symbol in top_coin_symbols:
#     print(symbol)
    symbol_trades[symbol] = trade_for_symbol(symbol)

In [ ]:
merged_mega_df = pd.DataFrame([]) 
first=1
for symbol_trade in symbol_trades:
    if not symbol_trades[symbol_trade].empty:
        if first > 0:
            merged_mega_df['todays_wallet'] = symbol_trades[symbol_trade]['today_balance']
            merged_mega_df['time'] = symbol_trades[symbol_trade]['time']
            first=0
        else:
            merged_mega_df['todays_wallet'] = merged_mega_df['todays_wallet'] + symbol_trades[symbol_trade]['today_balance']
        merged_mega_df[f'{symbol_trade}_close'] = symbol_trades[symbol_trade]['close']
        merged_mega_df[f'{symbol_trade}_side'] = symbol_trades[symbol_trade]['side']
        merged_mega_df[f'{symbol_trade}_positions'] = symbol_trades[symbol_trade]['positions']

In [ ]:
from IPython.display import display
pd.options.display.float_format = '{:,.2f}'.format
merged_mega_df
merged_mega_df.index = pd.DatetimeIndex(merged_mega_df['time'])

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
fig, ax = plt.subplots(figsize=(15, 6))
plt.plot(merged_mega_df['time'], merged_mega_df['todays_wallet'], label='Daily Wallet')
# ax.set_title('Daily Portfolio performance')
for symbol in symbol_trades:
    plt.plot(merged_mega_df['time'],merged_mega_df[f'{symbol}_close'], label=f'{symbol} close' )
# show a legend on the plot
plt.legend()
# Display a figure.
plt.show()
# ax.plot()

In [ ]:
merged_mega_df

#### return the top n coin symbols based on bassed pct_change or neg_div_score

In [ ]:
def get_todays_top_n_coin(df, trade_date,top_n):
    data = df.loc[trade_date]
    data = pd.DataFrame(data)
    data = data.rename(columns={data.columns[0]:'C'})
    todays_close_df = pd.DataFrame(data)
    todays_close_df = todays_close_df.sort_values(['C']).tail(top_n)
    return todays_close_df.index.values.tolist()

In [ ]:
def get_joins(symbols1, symbols2):
    symbols_list = symbols1.copy()
    for symbol in symbols2:
        if symbol not in symbols1:
            symbols_list.append(symbol)            
    return symbols_list

In [ ]:
def get_commons(symbols1, symbols2):
    symbols_list = []
    for symbol in symbols2:
        if symbol in symbols1:
            symbols_list.append(symbol)            
    return symbols_list

In [ ]:
def get_not_in_list(new_list, old_list):
    not_in_new = []
    for symbol in old_list:
        if symbol not in new_list:
            not_in_new.append(symbol)            
    return not_in_new

#### trading symbols

In [ ]:
def make_exit_symbol(df, trading_date, symbol, last_trade):
    quantity = last_trade[2]
    todays_close = get_close_price_on(df, symbol, trading_date)
    return quantity*todays_close

In [ ]:
def make_entry_symbol(df, trading_date, symbol, last_trade, fund):
    todays_close = get_close_price_on(df, symbol, trading_date)
    if not len(last_trade):
        last_trade = [trading_date,todays_close,fund/todays_close,fund]
        return last_trade
    last_trade[0] = trading_date
    last_trade[1] = todays_close
    last_trade[3] = last_trade[2]*todays_close
#     print(last_trade)
    return last_trade

In [ ]:
def get_todays_portfolio_balance(trades):
    balance = 0
    for symbol in trades:
        balance = balance + trades[symbol][3]
    return balance

### Portfolio Logic
1. on day 1, selectiong coins based on its 7 days pct change and negdiv_score. (top performer). And making entry of all the symbols.

2. next day again selecting symbols on same logic as aplied on day one. and perfoms the below actions
    
    1. hold the positions of the symbols if it was in last day trade
    2. exit the symbols who is not in top performer list today
    3. make entry for new symbols. (Funds will be trasfer to the new symbols by exiting the non performer symbols.)

3. then calculating the total balance for the day
    

by doing so, porfolio alwasy maintain same no of symbols each day.

In [ ]:
new = [1,2,3,4]
old = [3,2,5,6]
print(get_not_in_list(get_commons(old,new), new))

### Params

In [ ]:
def plot_portfolio_performence(trade_date, fund, df, pct_df, neg_div_score, pct_changed_symbols_count, negdiv_score_symbols_count):    
    trades = {}
    last_day_trading_symbols = None
    is_first_day_trading = True
    portfolio_performence = []
    while trade_date.timestamp() < now.timestamp():
        s1 = get_todays_top_n_coin(_7_days_pct_change_df, trade_date, pct_changed_symbols_count)
        s2 = get_todays_top_n_coin(neg_div_score, trade_date, negdiv_score_symbols_count)
    #     print(f'{s1} {s2}')
        todays_trading_symbols = get_commons(s1, s2)
        if is_first_day_trading:
            print(fund * len(todays_trading_symbols))
            for symbol in todays_trading_symbols:
                trade = make_entry_symbol(df, trade_date, symbol, [], fund)
                trades[symbol] = trade
            is_first_day_trading = False
            last_day_trading_symbols = todays_trading_symbols.copy()
            continue
        tmp_trades = trades

        trades = {}

        todays_exit_symbols = get_not_in_list(todays_trading_symbols, last_day_trading_symbols)
        todays_common_symbols = get_commons(todays_trading_symbols, last_day_trading_symbols)
        todays_new_entry_symbols = get_not_in_list(todays_common_symbols, todays_trading_symbols)
    #     print(f'{}')
        new_symbol = []
        for symbol_c in todays_common_symbols:
            trade = tmp_trades[symbol_c]
            trade = make_entry_symbol(df, trade_date, symbol_c, trade, 0)
            trades[symbol_c] = trade
        n = len(todays_exit_symbols)
#         print(todays_exit_symbols)
#         print(todays_new_entry_symbols)
        exit_fund = 0
        for exit_symbol in todays_exit_symbols:
            exit_trade = tmp_trades[exit_symbol]
            fund = make_exit_symbol(df, trade_date, exit_symbol, exit_trade)
            exit_fund = exit_fund + fund
        if len(todays_new_entry_symbols):
            new_entry_fund = exit_fund/len(todays_new_entry_symbols)
            for entry_symbol in todays_new_entry_symbols:
                trade = make_entry_symbol(df, trade_date, entry_symbol, [], new_entry_fund)
                trades[entry_symbol] = trade
                new_symbol.append(entry_symbol)
#         for i in range(0,n):
#             exit_symbol = todays_exit_symbols[i]
#             entry_symbol = todays_new_entry_symbols[i]
#             exit_trade = tmp_trades[exit_symbol]
#             fund = make_exit_symbol(df, trade_date, exit_symbol, exit_trade)
#             trade = make_entry_symbol(df, trade_date, entry_symbol, [], fund)
#             trades[entry_symbol] = trade
#             new_symbol.append(entry_symbol)
        portfolio_performence.append([get_todays_portfolio_balance(trades), trade_date])
        trade_date = get_next_trading_day_as_index(trade_date, hour)
        last_day_trading_symbols = get_joins(todays_common_symbols, new_symbol)
    print(todays_trading_symbols)
    return portfolio_performence

In [ ]:
### Default fund to invest in each symbols
total_symbols_count = len(df.columns.values.tolist())
start_balance = 100000/total_symbols_count
### no of symbols to be select based on the 7 days pct change
top_7_days_pct_changed_symbols_pct = 30
top_7_days_pct_changed_symbols_count = int(total_symbols_count/100*top_7_days_pct_changed_symbols_pct)


### no of symbols to be select based on the negdiv_score
top_n_negdiv_score_symbols_pct = 20
top_n_negdiv_score_symbols_count = int(total_symbols_count/100*top_n_negdiv_score_symbols_pct)

In [ ]:
f'Trading Start Date: {trade_start_date}'

In [ ]:
def plot_portfolio_for_config(days_pct_changed_symbols_pct, negdiv_score_symbols_pct, df, pct_df, neg_div_score_df):
    total_symbols_count = len(df.columns.values.tolist())
    pct_changed_symbols_count = int(total_symbols_count/100*days_pct_changed_symbols_pct)
    negdiv_score_symbols_count = int(total_symbols_count/100*negdiv_score_symbols_pct)
    
    now = datetime.now()
    start_time = now - timedelta(days=3*29, hours=23, minutes = 55)
    trades = {}
    #trading hour
    hour = 16
    trade_date = start_time + timedelta(days=0)
    trade_date = get_next_trading_day_as_index(trade_date, hour)
    print(trade_date)
    s1 = get_todays_top_n_coin(pct_df, trade_date, pct_changed_symbols_count)
    s2 = get_todays_top_n_coin(neg_div_score_df, trade_date, negdiv_score_symbols_count)
    symbols_to_be_trade_on_day_1 = get_commons(s1, s2)
#     print(f'Day 1 portfolio Symbols: \n{symbols_to_be_trade_on_day_1}')
#     print(f'Day 1 portfolio Symbols size: {len(symbols_to_be_trade_on_day_1)}')
    fund = 100000/len(symbols_to_be_trade_on_day_1)
    portfolio_performence = plot_portfolio_performence(trade_date, fund, df, pct_df, neg_div_score_df, pct_changed_symbols_count, negdiv_score_symbols_count)
    
    performance_df = pd.DataFrame(portfolio_performence, columns=['balance', 'time'])
    performance_df.index = pd.DatetimeIndex(performance_df['time'])
    del performance_df['time']
    performance_df.plot(figsize=[18,10])
    print(performance_df)

In [ ]:
plot_portfolio_for_config(50, 5, df, _7_days_pct_change_df, neg_div_score)

In [ ]:
plot_portfolio_for_config(50, 10, df, _7_days_pct_change_df, neg_div_score)

In [ ]:
plot_portfolio_for_config(50, 5, df, _14_days_pct_change_df, _14_neg_div_score)

In [ ]:
plot_portfolio_for_config(50, 10, df, _14_days_pct_change_df, _14_neg_div_score)