In [1]:
import pandas as pd
import pymysql
import numpy as np
import requests
from datetime import datetime, timedelta
import time
from pycoingecko import CoinGeckoAPI

# CoinMarketCap.com API Key
api_key = "a86e3326-8c8d-434e-897a-5d6becbf1f35"
top_symbols_count = 1300
required_tags = ['Binance Smart Chain Ecosystem', 'Polkadot Ecosystem', 'Cosmos Ecosystem', 'Solana Ecosystem', 'Avalanche Ecosystem', 'HECO Chain Ecosystem', 'Layer 1', 'Decentralized Finance (DeFi)', 'Yield Farming', 'Decentralized Exchange Token (DEX)', 'Governance', 'DaoMaker Ecosystem', 'Gaming', 'Stablecoins', 'Asset Manager', 'Centralized Exchange Token (CEX)', 'Eth 2.0 Staking', 'Yield Aggregator', 'Lending/Borrowing', 'Options', 'Launchpad']
cg = CoinGeckoAPI()

In [2]:
def __connect__():
    db_user = 'coin'
    db_password = 'dragonstone#123'
    db_name = 'master_data'
    db_host = 'localhost'
    return pymysql.connect(
        unix_socket=None,
        host=db_host,
        user=db_user,
        password=db_password,
        db=db_name,
        charset='latin1',
        cursorclass=pymysql.cursors.DictCursor)


def get_cursor(connection):
    if connection is None:
        connection = __connect__()
    connection.ping(reconnect=True)
    return connection.cursor()

### Today's Top Coins (marcketCap) under 1100

In [3]:
def get_market_data(page):
    market_data = cg.get_coins_markets(vs_currency="usd", page=page, per_page=250)
    ids = []
    for data in market_data:
        roi = data['roi']['times'] if data['roi'] else 0
        ids.append(data['symbol'].upper())
    return ids

def get_top_n_coins_symbol(n):
    page = 0
    totla_downloaded = 0
    rows = []
    while totla_downloaded < n:
        page = page + 1
        data = get_market_data(page)
        if not len(data):
            break
        totla_downloaded = totla_downloaded + len(data)
        rows.extend(data)
        time.sleep(1)
    rows = rows[0:n]
    return rows

In [4]:
# top_symbols = get_top_n_coins_symbol(top_symbols_count)

In [5]:
# top_symbols

In [6]:
def get_defi_tvl_data_df():
    defi_tvl = pd.read_sql_query("select * from notebook_defi_tvl;", __connect__())
    defi_tvl = defi_tvl.sort_values(['date', 'Symbol', 'Name'])
    defi_tvl['date'] = pd.to_datetime(defi_tvl['date'].dt.strftime('%Y-%m-%d'), format='%Y-%m-%d')
    defi_tvl = defi_tvl.groupby(['date', 'Symbol', 'Name']).tail(1)
    defi_tvl = defi_tvl.reset_index(drop=True)
    return defi_tvl

In [7]:
def get_supply_data_df():
    cmc_supply = pd.read_sql_query("select * from notebook_cmc_supply;", __connect__())
    cmc_supply['TVL'] = np.nan
    cgck_supply = pd.read_sql_query("select * from notebook_coingecko_supply;", __connect__())
    cgck_min_date = cgck_supply.date.min()
    cmc_supply = cmc_supply[cmc_supply['date'] < cgck_min_date]
    cmc_supply = cmc_supply[cmc_supply['Symbol'].isin(cgck_supply.Symbol.unique().tolist())]
    master_df = cmc_supply.append(cgck_supply)
    master_df['TVL Coingecko'] = master_df['TVL']
    del master_df['TVL']
    return master_df

In [ ]:
def update_empty_mcap_value(row):
    mcap = row['Marketcap CMC']
    if mcap == 0 or pd.isna(mcap):
        row['Marketcap CMC'] = row['Total Supply CMC'] * row['Price']

In [8]:
def get_all_other_datasource_symbols():
    sql = 'select * from notebook_all_required_symbols_cgk;'
    symbols = pd.read_sql_query(sql, __connect__())
    return symbols

In [61]:
def get_joins_data_df(all_datasource_symbols):
    # master_symbols = pd.read_sql_query("select symbol as Symbol, current_name as Name, group_concat(tags, ',') as Tags from cgk_coin_metainfo group by symbol, current_name;", __connect__())
    master_symbols = pd.read_sql_query("""select cgk.id as id, cgk.symbol as Symbol, cgk.`name` as Name, group_concat(cgk.tags, ',') as Tags from cgk_coin_metainfo cgk
group by cgk.id, cgk.symbol, cgk.name""", __connect__())
    cmc_supply = get_supply_data_df()
    cmc_supply.apply(update_empty_mcap_value)
    db_tvl = pd.read_sql_query("select * from notebook_debank_data;", __connect__())
    # defi_tvl = get_defi_tvl_data_df()
    dune_tua = pd.read_sql_query("select * from notebook_dune_tua;", __connect__())
    tt_metrics = pd.read_sql_query("select * from notebook_tt_metric_v2;", __connect__())
    defistation_tvl = pd.read_sql_query("select * from notebook_defisation_tvl;", __connect__())
    solana_tvl = pd.read_sql_query("select * from notebook_solana_tvl;", __connect__())
    master_df = pd.merge(cmc_supply, db_tvl, how='left', left_on=['date', 'Symbol', 'Name'], right_on=['date', 'Symbol', 'Name'])
    # master_df = pd.merge(master_df, defi_tvl, how='left', left_on=['date', 'Symbol', 'Name'], right_on=['date', 'Symbol', 'Name'])
    master_df = pd.merge(master_df, dune_tua, how='left', left_on=['date', 'Symbol', 'Name'], right_on=['date', 'Symbol', 'Name'])
    master_df = pd.merge(master_df, tt_metrics, how='left', left_on=['date', 'Symbol', 'Name'], right_on=['date', 'Symbol', 'Name'])
    master_df = pd.merge(master_df, defistation_tvl, how='left', left_on=['date', 'Symbol', 'Name'], right_on=['date', 'Symbol', 'Name'])
    master_df = pd.merge(master_df, solana_tvl, how='left', left_on=['date', 'Symbol', 'Name'], right_on=['date', 'Symbol', 'Name'])
    master_df = pd.merge(master_df, master_symbols, left_on=['Symbol', 'Name'], right_on=['Symbol', 'Name'])
    # master_df['required'] = (master_df['is_defistation'] == 1) | (master_df['is_solana'] == 1) | (master_df['is_debank'] == 1) | (master_df['is_tt_coin'] == 1) | (master_df['is_defi_tvl'] == 1) | (master_df['is_dune_tua'] == 1)
    master_df['required'] = (master_df['Name'].isin(all_datasource_symbols['name_in_coingecko']))
    del master_df['is_debank']
    del master_df['is_tt_coin']
    # del master_df['is_defi_tvl']
    del master_df['is_dune_tua']
    del master_df['is_cmc_supply']
    del master_df['is_defistation']
    del master_df['is_solana']
    master_df = master_df[(master_df['Marketcap CMC'] > 10000000) | (master_df['Symbol'].isin(required_symbols))].reset_index(drop=True)
    return master_df

In [62]:
def get_data_df(all_datasource_symbols):
    df = get_joins_data_df(all_datasource_symbols)
    df = df[(df['Symbol'].isin(all_datasource_symbols)) | (df['required'])]
    df = df.reset_index(drop=True)
    return df

In [63]:
all_data_source_symbols = get_all_other_datasource_symbols()
df = get_data_df(all_data_source_symbols)

ValueError: cannot reindex from a duplicate axis

In [12]:
len(all_data_source_symbols)

459

In [13]:
df.columns

Index(['date', 'Symbol', 'Name', 'Price', 'Marketcap CMC', 'Volume CMC',
       'Circulating supply CMC', 'MAX Supply CMC', 'Total Supply CMC',
       'TVL Coingecko', 'Users 24hr Debank', '24hr_Debank_users_max',
       'Transactions Count Debank', 'Trading Volume Debank',
       'Borrowing Volume Debank', 'TVL Debank', 'TVL Defipulse',
       'Users life-to-date duneanlytics', 'Revenue TT',
       'Revenue Supply Side TT', 'Revenue Protocol TT', 'Price/Sale', 'GMV TT',
       'tvl_defistation', 'users_defistation', 'tvl_solana', 'Tags',
       'required'],
      dtype='object')

In [14]:
df[df['Symbol'] == 'AAVE']['24hr_Debank_users_max'][-30:]

699    7078.0
700    7460.0
701    5948.0
702    5964.0
703    5891.0
704    6816.0
705    6162.0
706    6048.0
707    3708.0
708    3533.0
709     764.0
710    2136.0
711    2555.0
712    1458.0
713    1538.0
714    2274.0
715    9369.0
716    8018.0
717    7147.0
718    6028.0
719    7545.0
720    5521.0
721    5781.0
722    6241.0
723    6299.0
724    5745.0
725    5841.0
726    6369.0
727    6100.0
728    5693.0
Name: 24hr_Debank_users_max, dtype: float64

In [15]:
original_df = df.copy()

In [16]:
len(original_df.Symbol.unique().tolist())

405

In [17]:
len(df.Symbol.unique().tolist())

405

In [18]:
# df.columns

In [19]:
ffill_columns = ['Users life-to-date duneanlytics', 'tvl_defistation', 'tvl_solana', 'tvl_defistation', 'Revenue TT', 'Revenue Supply Side TT', 'Revenue Protocol TT', 'Price/Sale', 'GMV TT']

def ffill_columns_values(df, columns):
    df = df.reset_index(drop=True)
    df.index = pd.DatetimeIndex(df['date'])
    for column in columns:
        df[column] = df.groupby(['Symbol','Name'])[column].ffill()
    df = df.reset_index(drop=True)
    return df

In [20]:
df = ffill_columns_values(df, ffill_columns)

In [21]:
df[df['Symbol'] == 'RAY']['tvl_solana']

36506    4.111275e+08
36507    3.816011e+08
36508    4.335738e+08
36509    4.895894e+08
36510    5.891269e+08
             ...
36682    8.822644e+08
36683    8.976373e+08
36684    9.303872e+08
36685    9.367030e+08
36686    9.152664e+08
Name: tvl_solana, Length: 181, dtype: float64

In [59]:
df['Marketcap CMC'].unique().tolist()

[32044660.26,
 42607025.18,
 21916637.47,
 41976242.96,
 37221137.65,
 137151621.68400002,
 38308523.38,
 738715108.99,
 2390324.31,
 5019045.5,
 70019348.83,
 111056781.7,
 85712415.31,
 585630267.04,
 975723269.07,
 31463120.0,
 96781249.4,
 412143794.75,
 6944917514.76,
 28984496.91,
 40835156.43,
 4600196.38,
 5660275.958491315,
 20301832633.72,
 195459187.58,
 34759495.03,
 240420863.24,
 4365028372.7,
 19298398.79,
 695890369.79,
 683369982.14,
 16946247.63,
 610925196.92,
 6136206.306798724,
 113598951.23,
 11352874.38,
 9188829.07,
 13103284.95,
 0.0,
 6309207.82,
 68303140.54,
 15045183.16,
 423625088584.19,
 11902560.17,
 33726276.26,
 4397309.72,
 4659931518.1,
 422302737.47,
 11994392.95,
 34620316.36,
 56471651.01,
 175122979.25,
 19922074.6,
 14372158.32,
 86884362.88,
 115500602.82,
 63154165.27,
 17126445.79,
 142700471.89,
 905433508.58,
 58263554.1,
 74672578.82,
 2893798.84,
 3339236658.43,
 20414158.31,
 1650009711.16,
 98420975.37,
 6728436.74,
 2661403.71,
 71806910.82,
 179932372.92,
 32544213.09,
 3636077351.43,
 2757082.54,
 8184545.53,
 194180863.33,
 15455764.82,
 69475834114.54,
 20510415.3,
 53442135.17,
 729662488.1,
 519239918.61,
 429886635.96,
 1124492751.65,
 2880403.13,
 105087903.72000001,
 35973883.08,
 63619120.0,
 284506849.02,
 73097105.46,
 10604071.83,
 29267976.74,
 626058604.25,
 525662937.17,
 24945762.67,
 22973941.73,
 2228569.97,
 5686212.827820058,
 20387249195.31,
 2931692.95,
 1100112335.18,
 19774439.79,
 35412515.54,
 187944363.93,
 79754285.26,
 54263543.55,
 465759561.11,
 70395329.31,
 958801028.88,
 575304224.67,
 23197034.96,
 3106046.18,
 8940256.02,
 145600097.87,
 12187912.01,
 5775683.432772808,
 458363215.57,
 40145792.59,
 4835157312.98,
 39519249.21,
 62890754.36,
 4288843.64,
 101930786.85,
 2161202.25,
 34404884.37,
 36002495.55,
 15772516.14,
 14641978.53,
 4437530.99,
 88202942.68,
 8131673.93,
 108172053.7,
 17165977.63,
 30624895.92,
 31449266.05,
 56005701.76,
 2679175.49,
 40440111.08,
 2623526.93,
 33544722.25,
 16565944.2,
 147173821.0341,
 39839733.86,
 69402539.96,
 9299306.75,
 42996208.8,
 3356542655.44,
 62911942.33,
 22121208.66,
 6423276.95,
 745666453.02,
 424399426.07,
 1648547221.66,
 70559023.51,
 724071491.75,
 802368045.79,
 247405341.46,
 254381200.57,
 19997543.01,
 61943543.95,
 129292696.19,
 12141713.68,
 87078149.31,
 72336758959.73,
 4603028363.42,
 21350612.53,
 112196371.45,
 13167253.97,
 8100970.32,
 1009442760.11,
 22174974.5,
 103122424.17,
 680888157.98,
 739013157.46,
 89327989.26,
 137443186.16,
 3545740493.14,
 4243450.96,
 2695877.78,
 281403381.81,
 56415309.45,
 21835481.64,
 547722697.4,
 441850902134.23,
 13579006.54,
 197011079.43,
 179259259.71,
 7519474399.46,
 496585024.81,
 15192011.59,
 30668286.63,
 33665470.76,
 638385664.66,
 603787878.27,
 851816812.97,
 1373200251.43,
 223807323.61,
 100327515.63,
 66201438.68,
 29154484.19,
 58103713.15,
 35942963.75,
 431808778580.3,
 7912894.88,
 4646411.55,
 6543197.51,
 3885882.96,
 10531243.0,
 2729101.19,
 571709214.36,
 38041363.22,
 32630316.31,
 36559125.99,
 5624604.58,
 1732809.02,
 17695427.82,
 2765665940.7,
 18132962.45,
 143728191.0141,
 151388107.52,
 107210045.23,
 15697476.32,
 30108148.85,
 64970661.67,
 439894313.81,
 112690516.99,
 4310702.65,
 9142379.67,
 505247139.56,
 92787632.49,
 11291374.58,
 247639728.16,
 51672766.49,
 41628024.47,
 12804581.71,
 3822463.09,
 27778127.77,
 21017748.99,
 78899218.04,
 58801158.63,
 7093232.08,
 2213845.39,
 98475938.63,
 168228017.7,
 59582461.14,
 19043616.22,
 18954357.13,
 58777792.67,
 48776918.43,
 902812157.56,
 12955528.84,
 612614374.07,
 3425726107.55,
 11467765.63,
 138000735.99,
 2700702.01,
 402458429.18,
 4490740604.68,
 52129315.31,
 18957299.73,
 31115308.56,
 516823895.68,
 20459114819.8,
 480893678.03,
 66517758494.16,
 11076943.27,
 159040088.56,
 23369314.96,
 995679979.29,
 3236415.8082561027,
 27024160.1,
 18549073.71,
 15388861.12,
 2644525.65,
 272256631.08,
 4207716404.04,
 778063494.56,
 28559818.06,
 2698619.8,
 12400921.91,
 395554877.69,
 373720891.93,
 56149028.29,
 4086021.42,
 5394667.449386734,
 6735539589.93,
 92711572.86,
 37136930.91,
 212217095.783,
 11936914.93,
 30395784.52,
 588856733.13,
 110060807.99,
 86272515.49,
 95433328.76,
 179728143.9,
 273086715.8,
 64545327.41,
 55171160.7,
 583425690.2,
 19003583.52,
 37341147.91,
 20948190.86,
 4582660903.82,
 171368596.58,
 4668978.68,
 514206134.04,
 455053172.74,
 103980911.71,
 33003500.62,
 281766124.88199997,
 654792710.79,
 16329942.94,
 10958599.81,
 441017197764.42,
 12024771.92,
 29714368.73,
 61387567.56,
 106591503.01,
 2005394.37,
 10648426.19,
 31597371.39,
 7381279578.64,
 19330879.63,
 134190358.57290001,
 44266941.86,
 673600069.52,
 19220738.26,
 963409600.29,
 38252016.53,
 442778683.01,
 38793220.04,
 252092336.85,
 30332815.77,
 270596191.89,
 2568740.16,
 33609509.91,
 42326560.86,
 434407906.86,
 600531691.6,
 827681786.45,
 5349137.919939523,
 163737536.24,
 2629021.77,
 16747242.69,
 3260724.4335363293,
 22583286.64,
 74346238.85,
 3900900.5,
 114929779.63,
 2058527.74,
 1555323519.22,
 905198426.23,
 20531759415.57,
 526404953.02,
 19810762.84,
 61175112.88,
 4070593.32,
 3538335202.57,
 5727570.75,
 2320849.18,
 11685890.04,
 146584371.67,
 8027518.98,
 52079801.31,
 69704465559.66,
 12798256.74,
 2694344.11,
 96717869.87,
 13010670.2,
 12809263.89,
 4693298909.31,
 31683892.96,
 12170921.57,
 3490572261.99,
 4189403.12,
 36180022.39,
 8070204.49,
 57023477.87,
 715989957.68,
 117158349.05,
 1059047303.84,
 60377287.94,
 63447288.36,
 7414078.17,
 100936176.22,
 17974611.24,
 443464284.94,
 4931546.15,
 71863157.67,
 28333208.34,
 24615071.35,
 11876303.09,
 5829616.13,
 691704142.56,
 29621454.44,
 958013751.5,
 3336777846.03,
 261304760.74,
 32003953.54,
 37492235.06,
 2579869.83,
 130353208.79910001,
 18512953.91,
 112098164.9,
 2003748.47,
 1085914080.72,
 21836572.95,
 68279503.4,
 1529925703.56,
 56403232.16,
 900828920.95,
 1814963.02,
 5551346.54,
 5095678.89,
 8474907.44,
 606923901.74,
 42020307.37,
 29406318.17,
 18139025.61,
 18319572.81,
 31806975.74,
 40387172.75,
 14089139.99,
 12058380.83,
 3359646.0893055266,
 16645485.86,
 146180377.07,
 452711423.91,
 36825397.16,
 5253491.652729124,
 2619387.04,
 179130355.91,
 94982574.11999999,
 4659822224.37,
 422754678.28,
 11287205.42,
 255296942.35099998,
 669183137.19,
 56635922.46,
 10889462.15,
 4532134.09,
 17584370.06,
 98733149.79,
 529557196.69,
 2574266.48,
 234040185.07,
 67312349.73,
 3771626.69,
 12720855.96,
 29835251.75,
 10547067.52,
 103788281.49,
 814145787.35,
 29310679.37,
 3536352382.02,
 8402415630.93,
 443080295.33,
 710278779.86,
 52654888.87,
 18875436.39,
 4789239870.85,
 71400061459.63,
 20687636701.03,
 11983128.98,
 60065296.1,
 107986943.1,
 60477506.41,
 11509764.02,
 2325246.66,
 51634675.89,
 458297232691.9,
 4413437.93,
 268621050.48,
 33361832.33,
 56646973.53,
 167383818.42,
 83675472.89,
 12303482.55,
 449258702.17,
 104872232.86,
 584963463.87,
 182507302.33,
 445248710.26,
 23577643.31,
 115642214.32,
 25019693.92,
 7333284.45,
 75842830.82,
 27342463.57,
 63335534.27,
 15736881.84,
 44676033.27,
 8727373.1,
 106567083.14,
 27741164.93,
 8567168165.0,
 30631251.64,
 417425711.29,
 876098440.14,
 55133461.68,
 675148612.41,
 26501543.97,
 3547869512.6,
 2454475.95,
 12346728.45,
 61669699.54,
 32650535.45,
 887360070.27,
 182306831.55,
 49166054.31,
 10117229.23,
 15066196.54,
 120816814.46,
 41005561.99,
 100620157.16,
 14453842.56,
 28748235.31,
 18780330.57,
 72483025274.85,
 5048752.529902095,
 93710739.82,
 51769359.98,
 4632413801.46,
 405081695.45,
 10693983.52,
 205962094.459,
 434245926.51,
 8599297.05,
 41255929.55,
 712499872.4,
 10571488.5,
 55322659.27,
 491250863156.98,
 17545764.37,
 4495117.25,
 11995429.55,
 100344620.92,
 241620795.3,
 171012386.4,
 18718847.42,
 2509045.53,
 11507174.1,
 599617259.3,
 20682693558.19,
 535411746.99,
 10733081.64,
 41474977.72,
 11883381.85,
 16811123.31,
 4834318541.29,
 138452828.18,
 4530728.946174955,
 459332147.91,
 265590411.0,
 35848176.32,
 2509599.78,
 1050582598.65,
 4098533.93,
 658671538.04,
 28981370.05,
 63186736.47,
 35841192.8,
 104935238.13,
 159647270.72,
 5790798.94,
 64710723.6,
 898979377.01,
 21557709.75,
 10617163.17,
 7215777.23,
 5526676.87,
 29000270.98,
 18004144.67,
 1684074.78,
 17082099.7,
 113596281.79200001,
 573747738.35,
 1491670303.93,
 1903721.68,
 2199800.92,
 572005320.65,
 30208497.94,
 72949016.0,
 55569176.4,
 5030708.77,
 61066137.42,
 262404225.6,
 109452343.33,
 35207685.49,
 224728.35,
 21611328.0,
 3215622814.21,
 24013167.38,
 84397480.37,
 3787537.07,
 5636540.4,
 4839330613.85,
 104863729.56,
 13500685.87,
 141766127.32,
 4390734.221606634,
 4529379.36,
 34353124.95,
 5474112.43,
 992839784.49,
 279933116.24,
 16249620.4,
 16883113.8,
 18261564.82,
 483403669.54,
 24336072.66,
 170590827.39,
 729375669.81,
 33283111.7,
 3590225.28,
 10591235.18,
 12727982.24,
 58993052.36,
 22117328.94,
 73151078.13,
 4561582.08,
 488213268382.01,
 113832455.97,
 106398297.29,
 199351489.52,
 1610447.52,
 21123124.31,
 61765174.27,
 68653696.52,
 8439551136.23,
 96967954.01,
 2509640.55,
 4791796.49855071,
 4592307413.22,
 1510425125.03,
 52869673.32,
 426178356.99,
 9488884.92,
 12726581.76,
 184208477.981,
 7072957.91,
 438632514.22,
 11889488.76,
 888284496.56,
 55615090.38,
 16755274.18,
 49656040.55,
 117068274.9537,
 60682595.61,
 55053892.54,
 101876267.24,
 120906663.21,
 194232228.14,
 31509290.7,
 1765405.4,
 14989653.11,
 578584638.25,
 664293931.03,
 19589936.74,
 3722812.92,
 36196742.78,
 924546580.84,
 30684627.98,
 22626907.17,
 87351508.38,
 9872783.1,
 3170263194.62,
 36430948.3,
 15523333.7,
 41475399.83,
 60284137.83,
 5617116.71,
 30348361.29,
 19162559.78,
 90625832.96,
 18883422.38,
 10479410.75,
 20729387121.49,
 35654549.45,
 2139619.68,
 493411900.83,
 77828069141.05,
 580710699.35,
 28782960.42,
 162937193.31,
 218723.69,
 31815239.8,
 2300205.77,
 12148865.22,
 462677110.54,
 924485286.18,
 3582730027.76,
 267936439.42,
 563004444.35,
 27585423.4,
 682526309.47,
 31521190.3,
 179577170.03,
 301030151.3,
 4678983.22,
 58245191.6,
 6990552.57,
 4823595.61,
 70585367.31,
 17295448.55,
 18738636.54,
 981448509.29,
 4408652.093736184,
 1895736.4,
 210753302.75,
 3756106.0,
 5919855.24,
 3711001.27,
 50768793.14,
 3162631384.87,
 8608138657.32,
 26330611.42,
 1682065.17,
 4864886.699174746,
 12618365.92,
 25227817.58,
 18989553.98,
 142029166.99,
 282471109.6,
 15833126.77,
 171350760.66,
 63640597.06,
 586399767.24,
 95648408.87,
 14189780.69,
 64415153.82,
 107000340.18,
 77303205.6,
 1651772.22,
 1600175380.62,
 21139388.64,
 5764576.68,
 227955.36,
 30019541.61,
 113740541.8128,
 36997476.52,
 984160252.9,
 696413723.2,
 630916382.15,
 88376845.85,
 32126589.56,
 32518743.78,
 31672261.44,
 96941015.0,
 44092653.28,
 474508724.89,
 52934788.29,
 683161553.89,
 97623837.31,
 83282601744.93,
 164232059.1,
 16243530.22,
 6183379.99,
 5176189131.66,
 32128456.52,
 1312385.6,
 11432777.83,
 12513064.61,
 62628565.52,
 19397818.0,
 32198411.85,
 24918056.16,
 55327467.42,
 9872339.53,
 3587471.22,
 130342178.06,
 503339329917.2,
 8747044.56,
 441380411.32,
 34705610.75,
 80107730.74,
 493293710.1,
 12808331.31,
 19328944.86,
 2461534.05,
 462026200.69,
 175206870.42,
 169639418.234,
 20791781912.6,
 744627084.18,
 34396669.96,
 3627985593.57,
 582576325.25,
 69400068.61,
 5892566077.36,
 20160539.57,
 959011053.16,
 10303905.43,
 18276818.16,
 31822625.46,
 885266861.66,
 112697335.52,
 10006536.17,
 497627095.21,
 12588742.01,
 21945402.67,
 9487155.83,
 190511144.61,
 56324421.51,
 24789768.37,
 9976338.45,
 6727781086.98,
 32069298.51,
 12723358.59,
 911198711.94,
 36166582.34,
 443228978.27,
 130429011.93,
 3915612.46,
 53901708.93,
 508523687096.69,
 3305080.44,
 4790031.999356817,
 11817214.28,
 32107276.61,
 665294669.57,
 2543983.69,
 111164835.14,
 93536430.08,
 83420334908.86,
 190104225.08,
 55552256.1,
 20433558.53,
 5383158.13,
 9959549.16,
 6039324.04,
 77974154.25,
 19326295.89,
 33618522.62,
 501251.87,
 718365003.49,
 1849214.64,
 10734801.41,
 13012223.67,
 8542261137.11,
 51929537.06,
 6723931.58,
 168214666.51000002,
 4230684.963972049,
 19414125.55,
 5625044697.98,
 51363346.91,
 465004662.62,
 64067211.56,
 20812479542.83,
 20985618.55,
 76055712.34,
 5320349.4,
 6158170.63,
 3698412274.84,
 236903.7,
 29824969.14,
 118603982.0238,
 36581229.15,
 68208596.92,
 1597397.6,
 936493441.55,
 29775355.37,
 16905995.62,
 739037120.63,
 26429037.27,
 3040839826.95,
 314570550.79,
 616013318.03,
 859848824.52,
 29495608.3,
 32469754.84,
 4301462.88,
 9596684.98,
 29713935.34,
 46919637.89,
 1543106751.02,
 1628436.9,
 11966475.45,
 474066500.57,
 219245679.72,
 91256253.83,
 17928119.54,
 274013400.82,
 14712549.96,
 165648103.55,
 985107448.88,
 60810510.53,
 563085162.15,
 573014174.35,
 15405531.84,
 138740764.49,
 19941965.47,
 73635467.41,
 444071755.89,
 3430793.1,
 105337694.11,
 66923366.91,
 17730637.06,
 14247928.44,
 92343980.09,
 518866502.09,
 174181700.97,
 31598861.23,
 79458848.55000001,
 65854000.78,
 31399217.21,
 10381873.9,
 11791237.83,
 1111315023.94,
 460218550.42,
 688977262.42,
 28471646.0,
 85722581848.93,
 17633530.58,
 964857612.04,
 436380489.48,
 9093835.05,
 2465111.31,
 2889641250.3,
 20893813528.23,
 54045135.13,
 126884520.22,
 2760630.52,
 50528840.69,
 9642295.57,
 29929416.42,
 67185379.65,
 809600770.18,
 56331277.21,
 27523334.86,
 19739596.52,
 28253757.52,
 574468696.25,
 19052422.53,
 486840705.95,
 33911695.94,
 18854692.58,
 180808724.77,
 91182116.16,
 3680443610.87,
 48964352.45,
 6492175417.39,
 14389427.4,
 693613198.36,
 30983952.86,
 536033807160.84,
 61043257.66,
 161256758.08,
 14415638.56,
 103061344.91,
 90665919.22,
 140827477.8,
 1623246.88,
 269741339.24,
 1502366991.98,
 90010760.1,
 694018912.08,
 20961259.42,
 6187370.94,
 78683528.12,
 55868593.69,
 254677.16,
 35441422.59,
 137902369.899,
 31131760.26,
 9509337.52,
 36371316.51,
 973018228.85,
 15696658.49,
 466706536.15,
 16016618.22,
 592113774.58,
 20720562.98,
 324806319.19,
 2135275.38,
 6955018.56,
 1518078.38,
 5542890.0,
 3587131.69,
 17964089.96,
 22087221.17,
 4431488.47,
 94292992.23,
 655603849.26,
 14415734.94,
 15661976.92,
 12562999.12,
 215383371.36,
 192318571.92,
 51717412.12,
 5507131904.71,
 26094844.67,
 3938457.53,
 116170478.19,
 11907557.39,
 195989779.0,
 4866137.67,
 8571310123.74,
 ...]

In [23]:
df.tvl_defistation.unique()

array([      nan, 74614746., 68067114., ...,  7670045.,  9826656.,
        9152562.])

In [24]:
required_tags

['Binance Smart Chain Ecosystem',
 'Polkadot Ecosystem',
 'Cosmos Ecosystem',
 'Solana Ecosystem',
 'Avalanche Ecosystem',
 'HECO Chain Ecosystem',
 'Layer 1',
 'Decentralized Finance (DeFi)',
 'Yield Farming',
 'Decentralized Exchange Token (DEX)',
 'Governance',
 'DaoMaker Ecosystem',
 'Gaming',
 'Stablecoins',
 'Asset Manager',
 'Centralized Exchange Token (CEX)',
 'Eth 2.0 Staking',
 'Yield Aggregator',
 'Lending/Borrowing',
 'Options',
 'Launchpad']

### Adding cmc tags as column

In [25]:
def append_tags_in_columns(df):
    required_tags.sort()
    tag_df = pd.DataFrame(df['Tags'].copy())

    required_tags_map = {}
    i = 0
    for tag in required_tags:
        required_tags_map[tag] = i
        i = i + 1
        
    all_symbol_tags = []
    for index, row in tag_df.iterrows():
        tag = [''] * (len(required_tags))
        tags = row['Tags']
        tags = tags.split(',') if tags else []
        for t in tags:
            index = required_tags_map[t] if t in required_tags_map else -1
            if index > -1:
                tag[index] = 1
        all_symbol_tags.append(tag)

    tag_columns = []
    tag_columns.extend(required_tags)
    tag_column_df = pd.DataFrame(all_symbol_tags, columns = tag_columns)
    df = df.join(tag_column_df)
    del df['Tags']
    df.reset_index(inplace=True, drop=True)
    return df

In [26]:
df = append_tags_in_columns(df)

Filter symbols.

In [27]:
exceptional_coins = ['BTC', 'ETH', 'BNB', 'SOL']
df = df[(df['Symbol'].isin(exceptional_coins)) | (df['Decentralized Finance (DeFi)'] == 1) | (df['required'])]
del df['required']
# df = df[(df['defi'] == 1)]

In [28]:
len(df.Name.unique())

418

In [29]:
df.loc[((df['Marketcap CMC'] == 0) | (df['Marketcap CMC'].isna())), 'Marketcap CMC'] = df['Total Supply CMC'] * df['Price']

In [60]:
df[df['Symbol'] == 'ZRX']

,date,Symbol,Name,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Coingecko,...,HECO Chain Ecosystem,Launchpad,Layer 1,Lending/Borrowing,Options,Polkadot Ecosystem,Solana Ecosystem,Stablecoins,Yield Aggregator,Yield Farming
91,2020-12-21,ZRX,0x,0.379458,2.845068e+08,7.704968e+07,7.497721e+08,NaN,1.000000e+09,NaN,...,,,,,,1,,,,
185,2020-12-22,ZRX,0x,0.375319,2.814034e+08,4.782253e+07,7.497721e+08,NaN,1.000000e+09,NaN,...,,,,,,1,,,,
241,2020-12-23,ZRX,0x,0.330287,2.476397e+08,8.622976e+07,7.497721e+08,NaN,1.000000e+09,NaN,...,,,,,,1,,,,
308,2020-12-24,ZRX,0x,0.364226,2.730867e+08,4.406587e+07,7.497721e+08,NaN,1.000000e+09,NaN,...,,,,,,1,,,,
492,2020-12-25,ZRX,0x,0.358270,2.686211e+08,4.192997e+07,7.497721e+08,NaN,1.000000e+09,NaN,...,,,,,,1,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48908,2021-08-19,ZRX,0x,0.957250,8.093444e+08,7.580353e+07,8.453416e+08,1.000000e+09,1.000000e+09,NaN,...,,,,,,1,,,,
49086,2021-08-20,ZRX,0x,1.040000,8.763418e+08,7.979058e+07,8.453416e+08,1.000000e+09,1.000000e+09,NaN,...,,,,,,1,,,,
49657,2021-08-21,ZRX,0x,1.050000,8.845695e+08,7.854692e+07,8.453416e+08,1.000000e+09,1.000000e+09,NaN,...,,,,,,1,,,,
49843,2021-08-22,ZRX,0x,1.120000,9.429800e+08,1.355173e+08,8.453416e+08,1.000000e+09,1.000000e+09,NaN,...,,,,,,1,,,,
50362,2021-08-23,ZRX,0x,1.130000,9.575901e+08,1.260482e+08,8.453416e+08,1.000000e+09,1.000000e+09,NaN,...,,,,,,1,,,,

In [31]:
original_df

,date,Symbol,Name,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Coingecko,...,Revenue TT,Revenue Supply Side TT,Revenue Protocol TT,Price/Sale,GMV TT,tvl_defistation,users_defistation,tvl_solana,Tags,required
0,2020-12-22,ZRX,0x,3.753186e-01,2.814034e+08,4.782253e+07,7.497721e+08,NaN,1.000000e+09,NaN,...,5081.518355,0.0,5081.518355,327.001984,5.320025e+07,NaN,NaN,NaN,"Decentralized Exchange Token (DEX),Polygon Eco...",True
1,2020-12-21,ZRX,0x,3.794578e-01,2.845068e+08,7.704968e+07,7.497721e+08,NaN,1.000000e+09,NaN,...,4324.639219,0.0,4324.639219,351.334865,6.543229e+07,NaN,NaN,NaN,"Decentralized Exchange Token (DEX),Polygon Eco...",True
2,2021-05-25,ZRX,0x,9.765790e-01,8.219621e+08,1.149969e+08,8.416750e+08,1.000000e+09,1.000000e+09,NaN,...,20635.444305,0.0,20635.444305,53.273242,4.951713e+08,NaN,NaN,NaN,"Decentralized Exchange Token (DEX),Polygon Eco...",True
3,2021-05-24,ZRX,0x,9.845410e-01,8.286635e+08,1.398001e+08,8.416750e+08,1.000000e+09,1.000000e+09,NaN,...,29366.033133,0.0,29366.033133,53.631765,7.224367e+08,NaN,NaN,NaN,"Decentralized Exchange Token (DEX),Polygon Eco...",True
4,2021-05-23,ZRX,0x,8.038367e-01,6.765693e+08,1.512389e+08,8.416750e+08,1.000000e+09,1.000000e+09,NaN,...,55391.462027,0.0,55391.462027,64.133494,1.048609e+09,NaN,NaN,NaN,"Decentralized Exchange Token (DEX),Polygon Eco...",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58383,2021-08-23,BURGER,Burger Swap,5.930000e+00,0.000000e+00,2.705462e+07,0.000000e+00,2.100000e+07,1.525357e+07,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Decentralized Exchange Token (DEX),Automated M...",True
58384,2021-08-23,JOE,JOE,7.361820e-01,0.000000e+00,1.056522e+07,0.000000e+00,5.000000e+08,1.106428e+08,160499737.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Avalanche Ecosystem,",True
58385,2021-08-23,PIGGY,Piggy Bank Token,8.300000e-09,0.000000e+00,2.114400e+04,0.000000e+00,NaN,1.000000e+15,NaN,...,NaN,NaN,NaN,NaN,NaN,9152562.0,682.0,NaN,",",True
58386,2021-08-23,SBR,Saber,2.767570e-01,2.758335e+07,3.251160e+05,9.966620e+07,1.000000e+10,1.001302e+08,629898012.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.301253e+08,"Solana Ecosystem,",True
58387,2021-08-23,SCREAM,Scream,1.433000e+01,0.000000e+00,1.279520e+05,0.000000e+00,2.000000e+06,2.000000e+06,25369377.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,",",True

In [32]:
df[df['Symbol'] == 'MATIC']

,date,Symbol,Name,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Coingecko,...,HECO Chain Ecosystem,Launchpad,Layer 1,Lending/Borrowing,Options,Polkadot Ecosystem,Solana Ecosystem,Stablecoins,Yield Aggregator,Yield Farming
33796,2021-05-25,MATIC,Polygon,1.940050,1.205080e+10,6.515075e+09,6.211590e+09,1.000000e+10,1.000000e+10,NaN,...,,,,,,,,,,
33797,2021-05-24,MATIC,Polygon,1.717577,1.065515e+10,9.112451e+09,6.203590e+09,1.000000e+10,1.000000e+10,NaN,...,,,,,,,,,,
33798,2021-05-23,MATIC,Polygon,1.086715,6.698067e+09,3.787399e+09,6.163590e+09,1.000000e+10,1.000000e+10,NaN,...,,,,,,,,,,
33799,2021-05-22,MATIC,Polygon,1.193292,7.345414e+09,2.559785e+09,6.155590e+09,1.000000e+10,1.000000e+10,NaN,...,,,,,,,,,,
33800,2021-05-21,MATIC,Polygon,1.482336,9.124650e+09,3.691087e+09,6.155590e+09,1.000000e+10,1.000000e+10,NaN,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33983,2021-08-19,MATIC,Polygon,1.320000,8.569401e+09,9.252998e+08,6.458577e+09,1.000000e+10,1.000000e+10,9.520187e+09,...,,,,,,,,,,
33984,2021-08-20,MATIC,Polygon,1.490000,9.721925e+09,1.208315e+09,6.458577e+09,1.000000e+10,1.000000e+10,1.026193e+10,...,,,,,,,,,,
33985,2021-08-21,MATIC,Polygon,1.670000,1.075352e+10,1.532249e+09,6.458577e+09,1.000000e+10,1.000000e+10,1.076217e+10,...,,,,,,,,,,
33986,2021-08-22,MATIC,Polygon,1.630000,1.058084e+10,1.317166e+09,6.458577e+09,1.000000e+10,1.000000e+10,1.048213e+10,...,,,,,,,,,,
33987,2021-08-23,MATIC,Polygon,1.630000,1.053126e+10,1.106773e+09,6.458577e+09,1.000000e+10,1.000000e+10,1.050223e+10,...,,,,,,,,,,

### adding columns like TVL_max, Defi Volume_max, users_life_max and etc.

In [33]:
def add_other_columns(df):
    # df['TVL_max'] = df[['TVL Debank', 'TVL Defipulse']].max(axis=1)
    # df['TVL_max'] = df[['TVL Debank', 'TVL Defipulse', 'tvl_defistation']].max(axis=1)
    df['TVL_max'] = df[['TVL Debank', 'TVL Defipulse', 'tvl_defistation', 'tvl_solana', 'TVL Coingecko']].max(axis=1)
    df['GMV'] = df['GMV TT']
    df['Defi Volume DeBank'] = (df['Trading Volume Debank'].fillna(0) + df['Borrowing Volume Debank'].fillna(0)).replace({'0': np.nan, 0: np.nan})
    # add defi volume max as max of gmv from tokenterminal and defi volume debank
    df['Defi Volume_max'] = df[['GMV', 'Defi Volume DeBank']].max(axis=1)
    # add defi volume max as max of gmv from tokenterminal and defi volume debank
    df['Defi Volume_max'] = df[['GMV', 'Defi Volume DeBank']].max(axis=1)
    df['max_test'] = df[['MAX Supply CMC', 'Total Supply CMC']].max(axis=1)
    df['fully_diluted_mkt_cap'] = df.max_test * df.Price
    df["total_revenue"] = df['Revenue TT']
    df["total_supply_revenue"] = df['Revenue Supply Side TT']
    df["total_protocol_revenue"] = df['Revenue Protocol TT']
    df['users_life_max'] = df[['users_defistation', 'Users life-to-date duneanlytics']].max(axis=1)
    del df['max_test']
    df = df.sort_values('date')
    return df

In [34]:
df = add_other_columns(df)

In [35]:
def select_required_metrics_coins_only(df):

    def fillter_coins_basis_metrics(df, column, symbol):
        tmp_df = df[df['Symbol'] == symbol][column].isnull()
        return tmp_df.sum() == tmp_df.count()

    to_delete_symbols = []
    required_metrics = ['TVL_max', 'Defi Volume_max', 'total_revenue']
    symbols = df.Symbol.unique().tolist()
    for symbol in symbols:
        to_delete = True
        for metric in required_metrics:
            to_delete = fillter_coins_basis_metrics(df, metric, symbol)
            if not to_delete:
                break
        to_delete_symbols.append([symbol, to_delete])
    to_delete_symbols_df = pd.DataFrame(to_delete_symbols, columns=['Symbol', 'to_delete'])
    to_delete_symbols_df = to_delete_symbols_df[to_delete_symbols_df['to_delete']]
    to_delete_symbols = to_delete_symbols_df['Symbol'].values.tolist()
    df2 = df.drop(df[df['Symbol'].isin(to_delete_symbols)].index)
    df2 = df2.reset_index(drop=True)
    return df2

In [36]:
df = select_required_metrics_coins_only(df)
df

,date,Symbol,Name,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Coingecko,...,Yield Farming,TVL_max,GMV,Defi Volume DeBank,Defi Volume_max,fully_diluted_mkt_cap,total_revenue,total_supply_revenue,total_protocol_revenue,users_life_max
0,2020-12-21,TRB,Tellor,19.889399,32044660.26,28798929.57,1.611143e+06,NaN,1.694832e+06,NaN,...,,1.563044e+02,NaN,NaN,NaN,3.370919e+07,NaN,NaN,NaN,NaN
1,2020-12-21,PRQ,PARSIQ,0.408170,42607025.18,4924221.66,1.043856e+08,5.000000e+08,5.000000e+08,NaN,...,,NaN,NaN,NaN,NaN,2.040848e+08,NaN,NaN,NaN,NaN
2,2020-12-21,PEAK,PEAKDEFI,0.285950,21916637.47,277293.69,7.664508e+07,0.000000e+00,4.805654e+08,NaN,...,,7.922376e+04,NaN,NaN,NaN,1.374175e+08,NaN,NaN,NaN,NaN
3,2020-12-21,HEGIC,Hegic,0.133017,41976242.96,2046318.38,3.155709e+08,3.012010e+09,3.012010e+09,NaN,...,,9.037167e+07,5.138888e+05,NaN,5.138888e+05,4.006480e+08,42792.863023,37653.974567,5138.888456,1767.0
4,2020-12-21,CAKE,PancakeSwap,0.476475,37221137.65,960525.97,7.811769e+07,NaN,1.142132e+08,NaN,...,1,8.789615e+07,NaN,2559.180808,2.559181e+03,5.441975e+07,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50407,2021-08-23,YVS,YVS Finance,0.297550,158584.00,94148.00,5.329644e+05,NaN,1.953820e+06,NaN,...,,1.334647e+05,NaN,NaN,NaN,5.813591e+05,NaN,NaN,NaN,NaN
50408,2021-08-23,AGVE,Agave Token,181.930000,5057747.00,12547.55,2.779990e+04,1.000000e+05,1.000000e+05,NaN,...,,1.171463e+06,NaN,NaN,NaN,1.819300e+07,NaN,NaN,NaN,NaN
50409,2021-08-23,SWAMP,Swampy,1.860000,3720000.00,106993.00,0.000000e+00,2.000000e+06,2.000000e+06,41151471.0,...,,4.115147e+07,NaN,NaN,NaN,3.720000e+06,NaN,NaN,NaN,NaN
50410,2021-08-23,POOL,PoolTogether,16.250000,43504329.00,286218.00,2.677128e+06,1.000000e+07,1.000000e+07,184096476.0,...,,1.840965e+08,1.324032e+08,NaN,1.324032e+08,1.625000e+08,6769.712685,3384.856343,3384.856343,NaN
50411,2021-08-23,SCREAM,Scream,14.330000,28660000.00,127952.00,0.000000e+00,2.000000e+06,2.000000e+06,25369377.0,...,,2.614201e+07,NaN,NaN,NaN,2.866000e+07,NaN,NaN,NaN,NaN

In [37]:
cmc_symbol_name_df = get_all_other_datasource_symbols()
cmc_symbol_name_df['Symbol'] = cmc_symbol_name_df['symbol']
cmc_symbol_name_df['Name'] = cmc_symbol_name_df['name_in_coingecko']

In [38]:
cmc_symbol_name_df

    symbol name_in_coingecko Symbol           Name
0    $KING         King Swap  $KING      King Swap
1    1INCH             1inch  1INCH          1inch
2     AAVE              Aave   AAVE           Aave
3      ACS          Acryptos    ACS       Acryptos
4      ADD     Add.xyz (NEW)    ADD  Add.xyz (NEW)
..     ...               ...    ...            ...
454    UIP       UnlimitedIP    UIP    UnlimitedIP
455   USDC          USD Coin   USDC       USD Coin
456   USDT            Tether   USDT         Tether
457  WAVES             Waves  WAVES          Waves
458    JOE               JOE    JOE            JOE

[459 rows x 4 columns]

In [39]:
df[df['Marketcap CMC'] > 10000000].reset_index(drop=True)

,date,Symbol,Name,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Coingecko,...,Yield Farming,TVL_max,GMV,Defi Volume DeBank,Defi Volume_max,fully_diluted_mkt_cap,total_revenue,total_supply_revenue,total_protocol_revenue,users_life_max
0,2020-12-21,TRB,Tellor,19.889399,3.204466e+07,2.879893e+07,1.611143e+06,NaN,1.694832e+06,NaN,...,,1.563044e+02,NaN,NaN,NaN,3.370919e+07,NaN,NaN,NaN,NaN
1,2020-12-21,PRQ,PARSIQ,0.408170,4.260703e+07,4.924222e+06,1.043856e+08,5.000000e+08,5.000000e+08,NaN,...,,NaN,NaN,NaN,NaN,2.040848e+08,NaN,NaN,NaN,NaN
2,2020-12-21,PEAK,PEAKDEFI,0.285950,2.191664e+07,2.772937e+05,7.664508e+07,0.000000e+00,4.805654e+08,NaN,...,,7.922376e+04,NaN,NaN,NaN,1.374175e+08,NaN,NaN,NaN,NaN
3,2020-12-21,HEGIC,Hegic,0.133017,4.197624e+07,2.046318e+06,3.155709e+08,3.012010e+09,3.012010e+09,NaN,...,,9.037167e+07,5.138888e+05,NaN,5.138888e+05,4.006480e+08,42792.863023,37653.974567,5138.888456,1767.0
4,2020-12-21,CAKE,PancakeSwap,0.476475,3.722114e+07,9.605260e+05,7.811769e+07,NaN,1.142132e+08,NaN,...,1,8.789615e+07,NaN,2.559181e+03,2.559181e+03,5.441975e+07,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35724,2021-08-23,COMP,Compound,462.550000,2.496310e+09,2.077673e+08,5.400845e+06,1.000000e+07,1.000000e+07,1.109190e+10,...,1,1.140832e+10,8.083584e+09,8.535560e+09,8.535560e+09,4.625500e+09,890061.877448,785742.661914,104319.215534,299456.0
35725,2021-08-23,RARI,Rarible,31.200000,1.456313e+08,1.297773e+07,4.682813e+06,2.500000e+07,2.500000e+07,NaN,...,,4.659083e+03,1.145947e+05,NaN,1.145947e+05,7.800000e+08,5729.736524,0.000000,5729.736524,NaN
35726,2021-08-23,BANANA,ApeSwap Finance,4.750000,2.465545e+08,4.087318e+06,5.186375e+07,6.333892e+07,6.333892e+07,5.992366e+08,...,1,6.529257e+08,NaN,NaN,NaN,3.008599e+08,NaN,NaN,NaN,49034.0
35727,2021-08-23,POOL,PoolTogether,16.250000,4.350433e+07,2.862180e+05,2.677128e+06,1.000000e+07,1.000000e+07,1.840965e+08,...,,1.840965e+08,1.324032e+08,NaN,1.324032e+08,1.625000e+08,6769.712685,3384.856343,3384.856343,NaN
35728,2021-08-23,SCREAM,Scream,14.330000,2.866000e+07,1.279520e+05,0.000000e+00,2.000000e+06,2.000000e+06,2.536938e+07,...,,2.614201e+07,NaN,NaN,NaN,2.866000e+07,NaN,NaN,NaN,NaN

### Adding all ratios

In [40]:
# add n day users
def calculate_nDay_users(df, days):
    column_name = f"total_users_{days}d"
    df[column_name] = 0
    for index, row in cmc_symbol_name_df.iterrows():
        symbol = row['Symbol']
        name = row['Name']
        temp_df = df[(df['Symbol'] == symbol) & (df['Name'] == name)].copy()
        temp_df['parent_index'] = temp_df.index
        temp_df.index = pd.DatetimeIndex(temp_df['date'])
        temp_df[column_name] = temp_df['24hr_Debank_users_max'].rolling(f"{days}d").sum()
        temp_df.index = temp_df["parent_index"]
        del temp_df['parent_index']
        for index, row in temp_df.iterrows():
            df.loc[index, column_name] = row[column_name]

In [41]:
def calculate_nDay_revenue(df, days):
    column_name = f"total_revenue_{days}d"
    df[column_name] = 0
    for index, row in cmc_symbol_name_df.iterrows():
        symbol = row['Symbol']
        name = row['Name']
        temp_df = df[(df['Symbol'] == symbol) & (df['Name'] == name)].copy()
        temp_df['parent_index'] = temp_df.index
        temp_df.index = pd.DatetimeIndex(temp_df['date'])
        temp_df[column_name] = temp_df['total_revenue'].rolling(f"{days}d").sum()
        temp_df.index = temp_df["parent_index"]
        del temp_df['parent_index']
        for index, row in temp_df.iterrows():
            df.loc[index, column_name] = row[column_name]

In [42]:
# function for defi volume sums
# substitute for volume cmc sum
# changing defi volume debank to Defi Volume_max
def calculate_nDay_defi_volume(df, days):
    column_name = f"total_defi_volume_{days}d"
    df[column_name] = 0
    for index, row in cmc_symbol_name_df.iterrows():
        symbol = row['Symbol']
        name = row['Name']
        temp_df = df[(df['Symbol'] == symbol) & (df['Name'] == name)].copy()
        temp_df['parent_index'] = temp_df.index
        temp_df.index = pd.DatetimeIndex(temp_df['date'])
        temp_df[column_name] = temp_df['Defi Volume_max'].rolling(f"{days}d").sum()
        temp_df.index = temp_df["parent_index"]
        del temp_df['parent_index']
        for index, row in temp_df.iterrows():
            df.loc[index, column_name] = row[column_name]

In [43]:
def calculate_nDay_change(df, days, column, column_name):
    df[column_name] = 0
    for index, row in cmc_symbol_name_df.iterrows():
        symbol = row['Symbol']
        name = row['Name']
        temp_df = df[(df['Symbol'] == symbol) & (df['Name'] == name)].copy()
        temp_df['parent_index'] = temp_df.index
        temp_df.index = pd.DatetimeIndex(temp_df['date'])
        temp_df[column_name] = temp_df[column].pct_change(days)
        temp_df.index = temp_df["parent_index"]
        del temp_df['parent_index']
        for index, row in temp_df.iterrows():
            df.loc[index, column_name] = row[column_name]
    
def calculate_nDay_std(df, days, column, column_name, div_by_column='Price'):
    df[column_name] = 0
    for index, row in cmc_symbol_name_df.iterrows():
        symbol = row['Symbol']
        name = row['Name']
        temp_df = df[(df['Symbol'] == symbol) & (df['Name'] == name)].copy()
        temp_df['parent_index'] = temp_df.index
        temp_df.index = pd.DatetimeIndex(temp_df['date'])
        temp_df[column_name] = temp_df[column].rolling(days).std() / temp_df[div_by_column]
        temp_df.index = temp_df["parent_index"]
        del temp_df['parent_index']
        for index, row in temp_df.iterrows():
            df.loc[index, column_name] = row[column_name]

In [44]:
def add_ratios_and_pct_change(df):
    calculate_nDay_revenue(df, 7)
    calculate_nDay_revenue(df, 30)
    #calculate_nDay_trading_volume(df, 30)
    calculate_nDay_defi_volume(df, 30)

    # add n day users
    calculate_nDay_users(df, 30)

    # add 1, 3, 7, 30 day defi volume pct change here
    # added column calculations
    #
    calculate_nDay_change(df, 1, 'Defi Volume_max', 'Defi_volume_pct_chg_1d')
    calculate_nDay_change(df, 3, 'Defi Volume_max', 'Defi_volume_pct_chg_3d')
    calculate_nDay_change(df, 7, 'Defi Volume_max', 'Defi_volume_pct_chg_7d')
    calculate_nDay_change(df, 30, 'Defi Volume_max', 'Defi_volume_pct_chg_30d')
    #
    # flip such that mc in numerator 
    #df['VOL : MC'] = df['Volume CMC'] / df['Marketcap CMC']
    df['MC : VOL'] = df['Marketcap CMC'] / df['Volume CMC'] 
    # added column calculations
    calculate_nDay_change(df, 1, 'MC : VOL', 'MC_VOL_pct_chg_1d')
    calculate_nDay_change(df, 3, 'MC : VOL', 'MC_VOL_pct_chg_3d')
    calculate_nDay_change(df, 7, 'MC : VOL', 'MC_VOL_pct_chg_7d')
    calculate_nDay_change(df, 30, 'MC : VOL', 'MC_VOL_pct_chg_30d')
    #

    # flip such that mc in numerator
    #df['VOL : DMC'] = df['Volume CMC'] / df['fully_diluted_mkt_cap']
    df['DMC : VOL'] = df['fully_diluted_mkt_cap'] / df['Volume CMC']
    # added column calculations
    calculate_nDay_change(df, 1, 'DMC : VOL', 'DMC_VOL_pct_chg_1d')
    calculate_nDay_change(df, 3, 'DMC : VOL', 'DMC_VOL_pct_chg_3d')
    calculate_nDay_change(df, 7, 'DMC : VOL', 'DMC_VOL_pct_chg_7d')
    calculate_nDay_change(df, 30, 'DMC : VOL', 'DMC_VOL_pct_chg_30d')
    #



    df['MC : TVL'] = df['Marketcap CMC'] / df['TVL_max']
    # added column calculations
    calculate_nDay_change(df, 1, 'MC : TVL', 'MC_TVL_pct_chg_1d')
    calculate_nDay_change(df, 3, 'MC : TVL', 'MC_TVL_pct_chg_3d')
    calculate_nDay_change(df, 7, 'MC : TVL', 'MC_TVL_pct_chg_7d')
    calculate_nDay_change(df, 30, 'MC : TVL', 'MC_TVL_pct_chg_30d')
    #


    df['DMC : TVL'] = df['fully_diluted_mkt_cap'] / df['TVL_max']
    # added column calculations
    calculate_nDay_change(df, 1, 'DMC : TVL', 'DMC_TVL_pct_chg_1d')
    calculate_nDay_change(df, 3, 'DMC : TVL', 'DMC_TVL_pct_chg_3d')
    calculate_nDay_change(df, 7, 'DMC : TVL', 'DMC_TVL_pct_chg_7d')
    calculate_nDay_change(df, 30, 'DMC : TVL', 'DMC_TVL_pct_chg_30d')
    #


    df['MC : users (1d)'] = df['Marketcap CMC'] / df['24hr_Debank_users_max']
    # added column calculations
    calculate_nDay_change(df, 1, 'MC : users (1d)', 'MC_users_pct_chg_1d')
    calculate_nDay_change(df, 3, 'MC : users (1d)', 'MC_users_pct_chg_3d')
    calculate_nDay_change(df, 7, 'MC : users (1d)', 'MC_users_pct_chg_7d')
    calculate_nDay_change(df, 30, 'MC : users (1d)', 'MC_users_pct_chg_30d')
    #




    df['DMC : users (1d)'] = df['fully_diluted_mkt_cap'] / df['24hr_Debank_users_max']
    # added column calculations
    calculate_nDay_change(df, 1, 'DMC : users (1d)', 'DMC_users_pct_chg_1d')
    calculate_nDay_change(df, 3, 'DMC : users (1d)', 'DMC_users_pct_chg_3d')
    calculate_nDay_change(df, 7, 'DMC : users (1d)', 'DMC_users_pct_chg_7d')
    calculate_nDay_change(df, 30, 'DMC : users (1d)', 'DMC_users_pct_chg_30d')
    #



    df['MC : transactions (1d)'] = df['Marketcap CMC'] / df['Transactions Count Debank']
    # added column calculations
    calculate_nDay_change(df, 1, 'MC : transactions (1d)', 'MC_transactions_pct_chg_1d')
    calculate_nDay_change(df, 3, 'MC : transactions (1d)', 'MC_transactions_pct_chg_3d')
    calculate_nDay_change(df, 7, 'MC : transactions (1d)', 'MC_transactions_pct_chg_7d')
    calculate_nDay_change(df, 30, 'MC : transactions (1d)', 'MC_transactions_pct_chg_30d')
    #

    df['DMC : transactions (1d)'] = df['fully_diluted_mkt_cap'] / df['Transactions Count Debank']
    # added column calculations
    calculate_nDay_change(df, 1, 'DMC : transactions (1d)', 'DMC_transactions_pct_chg_1d')
    calculate_nDay_change(df, 3, 'DMC : transactions (1d)', 'DMC_transactions_pct_chg_3d')
    calculate_nDay_change(df, 7, 'DMC : transactions (1d)', 'DMC_transactions_pct_chg_7d')
    calculate_nDay_change(df, 30, 'DMC : transactions (1d)', 'DMC_transactions_pct_chg_30d')
    #

    #df['MC : DEX Vol (1d)'] = df['Marketcap CMC'] / df['Trading Volume Debank']
    # add
    df['MC : Defi Vol (1d)'] = df['Marketcap CMC'] / df['Defi Volume_max']
    # added column calculations
    calculate_nDay_change(df, 1, 'MC : Defi Vol (1d)', 'MC_defi_volume_pct_chg_1d')
    calculate_nDay_change(df, 3, 'MC : Defi Vol (1d)', 'MC_defi_volume_pct_chg_3d')
    calculate_nDay_change(df, 7, 'MC : Defi Vol (1d)', 'MC_defi_volume_pct_chg_7d')
    calculate_nDay_change(df, 30, 'MC : Defi Vol (1d)', 'MC_defi_volume_pct_chg_30d')
    #


    df['MC : Defi Vol (30d)'] = df['Marketcap CMC'] / df['total_defi_volume_30d']
    #df['DMC : DEX Vol (1d)'] = df['fully_diluted_mkt_cap'] / df['Trading Volume Debank']
    #df['DMC : DEX Vol (30d)'] = df['fully_diluted_mkt_cap'] / df['total_volume_30d']



    df['MC : revenue'] = df['Marketcap CMC'] / df['total_revenue']
    # added column calculations
    calculate_nDay_change(df, 1, 'MC : revenue', 'MC_revenue_pct_chg_1d')
    calculate_nDay_change(df, 3, 'MC : revenue', 'MC_revenue_pct_chg_3d')
    calculate_nDay_change(df, 7, 'MC : revenue', 'MC_revenue_pct_chg_7d')
    calculate_nDay_change(df, 30, 'MC : revenue', 'MC_revenue_pct_chg_30d')
    #

    df['DMC : revenue'] = df['fully_diluted_mkt_cap'] / df['total_revenue']
    # added column calculations
    calculate_nDay_change(df, 1, 'DMC : revenue', 'DMC_revenue_pct_chg_1d')
    calculate_nDay_change(df, 3, 'DMC : revenue', 'DMC_revenue_pct_chg_3d')
    calculate_nDay_change(df, 7, 'DMC : revenue', 'DMC_revenue_pct_chg_7d')
    calculate_nDay_change(df, 30, 'DMC : revenue', 'DMC_revenue_pct_chg_30d')
    #


    df['MC : total_users_30d'] = df['Marketcap CMC'] / df['total_users_30d']
    # added column calculations
    calculate_nDay_change(df, 1, 'MC : total_users_30d', 'MC_total_users_30d_pct_chg_1d')
    calculate_nDay_change(df, 3, 'MC : total_users_30d', 'MC_total_users_30d_pct_chg_3d')
    calculate_nDay_change(df, 7, 'MC : total_users_30d', 'MC_total_users_30d_pct_chg_7d')
    calculate_nDay_change(df, 30, 'MC : total_users_30d', 'MC_total_users_30d_pct_chg_30d')
    #

    df['DMC : total_users_30d'] = df['fully_diluted_mkt_cap'] / df['total_users_30d']
    # added column calculations
    calculate_nDay_change(df, 1, 'DMC : total_users_30d', 'DMC_total_users_30d_pct_chg_1d')
    calculate_nDay_change(df, 3, 'DMC : total_users_30d', 'DMC_total_users_30d_pct_chg_3d')
    calculate_nDay_change(df, 7, 'DMC : total_users_30d', 'DMC_total_users_30d_pct_chg_7d')
    calculate_nDay_change(df, 30, 'DMC : total_users_30d', 'DMC_total_users_30d_pct_chg_30d')
    #

    df['MC : Users_life'] = df['Marketcap CMC'] / df['users_life_max']
    # added column calculations
    calculate_nDay_change(df, 1, 'MC : Users_life', 'MC_Users_life_pct_chg_1d')
    calculate_nDay_change(df, 3, 'MC : Users_life', 'MC_Users_life_pct_chg_3d')
    calculate_nDay_change(df, 7, 'MC : Users_life', 'MC_Users_life_pct_chg_7d')
    calculate_nDay_change(df, 30, 'MC : Users_life', 'MC_Users_life_pct_chg_30d')
    #
    df['DMC : Users_life'] = df['fully_diluted_mkt_cap'] / df['users_life_max']
    # added column calculations
    calculate_nDay_change(df, 1, 'DMC : Users_life', 'DMC_Users_life_pct_chg_1d')
    calculate_nDay_change(df, 3, 'DMC : Users_life', 'DMC_Users_life_pct_chg_3d')
    calculate_nDay_change(df, 7, 'DMC : Users_life', 'DMC_Users_life_pct_chg_7d')
    calculate_nDay_change(df, 30, 'DMC : Users_life', 'DMC_Users_life_pct_chg_30d')
    #
    calculate_nDay_change(df, 1, 'Price', 'Price_pct_chg_1d')
    calculate_nDay_change(df, 3, 'Price', 'Price_pct_chg_3d')
    calculate_nDay_change(df, 7, 'Price', 'Price_pct_chg_7d')
    calculate_nDay_change(df, 30, 'Price', 'Price_pct_chg_30d')
    calculate_nDay_std(df, 7, 'Price', 'Price_7day_volatility_pct', div_by_column='Price')
    calculate_nDay_std(df, 30, 'Price', 'Price_30day_volatility_pct', div_by_column='Price')
    calculate_nDay_std(df, 90, 'Price', 'Price_90day_volatility_pct', div_by_column='Price')
    #
    calculate_nDay_change(df, 1, 'Marketcap CMC', 'MC_pct_chg_1d')
    calculate_nDay_change(df, 3, 'Marketcap CMC', 'MC_pct_chg_3d')
    calculate_nDay_change(df, 7, 'Marketcap CMC', 'MC_pct_chg_7d')
    calculate_nDay_change(df, 30, 'Marketcap CMC', 'MC_pct_chg_30d')
    calculate_nDay_std(df, 30, 'Marketcap CMC', 'MC_30day_volatility_pct', div_by_column='Marketcap CMC')
    calculate_nDay_std(df, 90, 'Marketcap CMC', 'MC_90day_volatility_pct', div_by_column='Marketcap CMC')
    #
    calculate_nDay_change(df, 1, 'fully_diluted_mkt_cap', 'DMC_pct_chg_1d')
    calculate_nDay_change(df, 3, 'fully_diluted_mkt_cap', 'DMC_pct_chg_3d')
    calculate_nDay_change(df, 7, 'fully_diluted_mkt_cap', 'DMC_pct_chg_7d')
    calculate_nDay_change(df, 30, 'fully_diluted_mkt_cap', 'DMC_pct_chg_30d')
    calculate_nDay_std(df, 30, 'fully_diluted_mkt_cap', 'DMC_30day_volatility_pct', div_by_column='fully_diluted_mkt_cap')
    calculate_nDay_std(df, 90, 'fully_diluted_mkt_cap', 'DMC_90day_volatility_pct', div_by_column='fully_diluted_mkt_cap')
    #
    calculate_nDay_change(df, 1, 'Circulating supply CMC', 'CS_pct_chg_1d')
    calculate_nDay_change(df, 3, 'Circulating supply CMC', 'CS_pct_chg_d')
    calculate_nDay_change(df, 7, 'Circulating supply CMC', 'CS_pct_chg_7d')
    calculate_nDay_change(df, 30, 'Circulating supply CMC', 'CS_pct_chg_30d')
    calculate_nDay_std(df, 30, 'Circulating supply CMC', 'CS_30day_volatility_pct', div_by_column='Circulating supply CMC')
    calculate_nDay_std(df, 90, 'Circulating supply CMC', 'CS_90day_volatility_pct', div_by_column='Circulating supply CMC')
    #
    calculate_nDay_change(df, 1, 'Volume CMC', 'Volume_pct_chg_1d')
    calculate_nDay_change(df, 3, 'Volume CMC', 'Volume_pct_chg_3d')
    calculate_nDay_change(df, 7, 'Volume CMC', 'Volume_pct_chg_7d')
    calculate_nDay_change(df, 30, 'Volume CMC', 'Volume_pct_chg_30d')
    calculate_nDay_std(df, 30, 'Volume CMC', 'Volume_30day_volatility_pct', div_by_column='Volume CMC')
    calculate_nDay_std(df, 90, 'Volume CMC', 'Volume_90day_volatility_pct', div_by_column='Volume CMC')
    #
    calculate_nDay_change(df, 1, 'TVL_max', 'TVL_pct_chg_1d')
    calculate_nDay_change(df, 3, 'TVL_max', 'TVL_pct_chg_3d')
    calculate_nDay_change(df, 7, 'TVL_max', 'TVL_pct_chg_7d')
    calculate_nDay_change(df, 30, 'TVL_max', 'TVL_pct_chg_30d')
    calculate_nDay_std(df, 30, 'TVL_max', 'TVL_30day_volatility_pct', div_by_column='TVL_max')
    calculate_nDay_std(df, 90, 'TVL_max', 'TVL_90day_volatility_pct', div_by_column='TVL_max')
    #
    calculate_nDay_change(df, 1, 'total_revenue', 'Rev_pct_chg_1d')
    calculate_nDay_change(df, 3, 'total_revenue', 'Rev_pct_chg_3d')
    calculate_nDay_change(df, 7, 'total_revenue', 'Rev_pct_chg_7d')
    calculate_nDay_change(df, 30, 'total_revenue', 'Rev_pct_chg_30d')
    
    calculate_nDay_change(df, 1, 'Circulating supply CMC', 'emission_rate')
    
    calculate_nDay_std(df, 30, 'total_revenue', 'Rev_30day_volatility_pct', div_by_column='total_revenue')
    calculate_nDay_std(df, 90, 'total_revenue', 'Rev_90day_volatility_pct', div_by_column='total_revenue')
    df['Annual revenue (estimate)'] = df['total_revenue_30d'] * (1 + df['Rev_pct_chg_30d'])*12
    return df

In [45]:
# df = add_ratios_and_pct_change(df)

In [46]:
df

,date,Symbol,Name,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Coingecko,...,Yield Farming,TVL_max,GMV,Defi Volume DeBank,Defi Volume_max,fully_diluted_mkt_cap,total_revenue,total_supply_revenue,total_protocol_revenue,users_life_max
0,2020-12-21,TRB,Tellor,19.889399,32044660.26,28798929.57,1.611143e+06,NaN,1.694832e+06,NaN,...,,1.563044e+02,NaN,NaN,NaN,3.370919e+07,NaN,NaN,NaN,NaN
1,2020-12-21,PRQ,PARSIQ,0.408170,42607025.18,4924221.66,1.043856e+08,5.000000e+08,5.000000e+08,NaN,...,,NaN,NaN,NaN,NaN,2.040848e+08,NaN,NaN,NaN,NaN
2,2020-12-21,PEAK,PEAKDEFI,0.285950,21916637.47,277293.69,7.664508e+07,0.000000e+00,4.805654e+08,NaN,...,,7.922376e+04,NaN,NaN,NaN,1.374175e+08,NaN,NaN,NaN,NaN
3,2020-12-21,HEGIC,Hegic,0.133017,41976242.96,2046318.38,3.155709e+08,3.012010e+09,3.012010e+09,NaN,...,,9.037167e+07,5.138888e+05,NaN,5.138888e+05,4.006480e+08,42792.863023,37653.974567,5138.888456,1767.0
4,2020-12-21,CAKE,PancakeSwap,0.476475,37221137.65,960525.97,7.811769e+07,NaN,1.142132e+08,NaN,...,1,8.789615e+07,NaN,2559.180808,2.559181e+03,5.441975e+07,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50407,2021-08-23,YVS,YVS Finance,0.297550,158584.00,94148.00,5.329644e+05,NaN,1.953820e+06,NaN,...,,1.334647e+05,NaN,NaN,NaN,5.813591e+05,NaN,NaN,NaN,NaN
50408,2021-08-23,AGVE,Agave Token,181.930000,5057747.00,12547.55,2.779990e+04,1.000000e+05,1.000000e+05,NaN,...,,1.171463e+06,NaN,NaN,NaN,1.819300e+07,NaN,NaN,NaN,NaN
50409,2021-08-23,SWAMP,Swampy,1.860000,3720000.00,106993.00,0.000000e+00,2.000000e+06,2.000000e+06,41151471.0,...,,4.115147e+07,NaN,NaN,NaN,3.720000e+06,NaN,NaN,NaN,NaN
50410,2021-08-23,POOL,PoolTogether,16.250000,43504329.00,286218.00,2.677128e+06,1.000000e+07,1.000000e+07,184096476.0,...,,1.840965e+08,1.324032e+08,NaN,1.324032e+08,1.625000e+08,6769.712685,3384.856343,3384.856343,NaN
50411,2021-08-23,SCREAM,Scream,14.330000,28660000.00,127952.00,0.000000e+00,2.000000e+06,2.000000e+06,25369377.0,...,,2.614201e+07,NaN,NaN,NaN,2.866000e+07,NaN,NaN,NaN,NaN

In [47]:
def arrange_columns(df):
    columns = df.columns.tolist()
    for tag in required_tags:
        columns.remove(tag)
    columns.extend(required_tags)
    return df[columns]

In [48]:
df = arrange_columns(df)

### Generating neg div score

In [49]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
from sklearn.linear_model import LinearRegression
import numpy as np
import pymysql
import traceback2


def read_csv_as_df():
    df = pd.read_csv('/tmp/coins_data.csv')
    df.index = pd.DatetimeIndex(df['time'])
    del df['time']
    df = df[df.index >= datetime(2020, 12, 26)]
    return df

def __connect__():
    db_user = 'coin'
    db_password = 'dragonstone#123'
    db_name = 'master_data'
    db_host = 'localhost'
    return pymysql.connect(
        unix_socket=None,
        host=db_host,
        user=db_user,
        password=db_password,
        db=db_name,
        charset='latin1',
        cursorclass=pymysql.cursors.DictCursor)


def get_cursor(connection):
    if connection is None:
        connection = __connect__()
    connection.ping(reconnect=True)
    return connection.cursor()


def insert_defi_neg_div_score(df, date):
    connection = __connect__()
    cursor = get_cursor(connection)
    dt = date.timestamp()
    for i, row in df.iterrows():
        try:
            sys_name = row["Symbol"]
            name = sys_name.split("###")[1]
            symbol = sys_name.split("###")[0]
            print(dt, date, symbol, name, row['C_Price'], row['3_Day_LB'], row['5_Day_LB'])
            sql = "INSERT INTO `defi_neg_div_score` (`timestamp_dt`, `symbol`, `name`, `price`, `3_Day_LB`, `5_Day_LB`) VALUES (FROM_UNIXTIME(%s), %s, %s, %s, %s, %s)"
            cursor.execute(sql, (dt, symbol, name, row['C_Price'], row['3_Day_LB'], row['5_Day_LB']))
        except Exception:
            print(traceback2.format_exc())
    connection.commit()
    cursor.close()
    connection.close()

def clean_data(df):
    index = df.index.values
#     print(index)
    if 'USDT' in index:
        del df['USDT']
    if 'USDC' in index:
        del df['USDC']
    if 'DAI' in index:
        del df['DAI']
    if 'BUSD' in index:
        del df['BUSD']
    if 'HUSD' in index:
        del df['HUSD']
    if 'TUSD' in index:
        del df['TUSD']
    if 'BTC' in index:
        del df['BTC']
    data_values_df = pd.DataFrame(df.isna().sum(), columns=['nan_count'])
    tmp_df = pd.DataFrame(df.count(), columns=['values_count'])
    data_values_df['values_count'] = tmp_df['values_count']
    data_values_df['rows_count'] = data_values_df['values_count'] + data_values_df['nan_count']
#     print(data_values_df)
    delete_coin_df = data_values_df[data_values_df['nan_count'] > (data_values_df['values_count'] * .20)]
    delete_coin_df.sort_values(['nan_count'])
    symbols_del = delete_coin_df.index.tolist()
    for symbol in symbols_del:
        print(f'Deleteing Coin: {symbol}')
        del df[symbol]
    df.ffill(inplace=True)
    df = df.dropna(axis=1)
    df.index = df.index
    return df


def get_todays_portfolio_balance(trades):
    balance = 0
    for symbol in trades:
        balance = balance + trades[symbol][3]
    return balance


def make_entry_symbol(df, trading_date, symbol, last_trade, fund):
    last_trade = last_trade.copy()
    todays_close = get_close_price_on(df, symbol, trading_date)
    if not len(last_trade):
        last_trade = [trading_date, todays_close, fund / todays_close, fund, 0]
        return last_trade
    last_trade[0] = trading_date
    last_trade[1] = todays_close
    last_trade[3] = last_trade[2] * todays_close
    last_trade[4] = last_trade[4] + 1
#     print(last_trade)
    return last_trade


def make_exit_symbol(df, trading_date, symbol, last_trade):
    quantity = last_trade[2]
    todays_close = get_close_price_on(df, symbol, trading_date)
    return quantity * todays_close


def get_not_in_list(new_list, old_list):
    not_in_new = []
    for symbol in old_list:
        if symbol not in new_list:
            not_in_new.append(symbol)
    return not_in_new


def get_commons(symbols1, symbols2):
    symbols_list = []
    for symbol in symbols2:
        if symbol in symbols1:
            symbols_list.append(symbol)
    return symbols_list


def get_joins(symbols1, symbols2):
    symbols_list = symbols1.copy()
    for symbol in symbols2:
        if symbol not in symbols1:
            symbols_list.append(symbol)
    return symbols_list


def get_todays_top_n_coin(df, trade_date, top_n, order='tail'):
    data = df.loc[trade_date]
    data = pd.DataFrame(data)
    data = data.rename(columns={data.columns[0]: 'C'})
    todays_close_df = pd.DataFrame(data)
    if order == 'head':
        todays_close_df = todays_close_df.sort_values(['C']).head(top_n)
    else:
        todays_close_df = todays_close_df.sort_values(['C']).tail(top_n)
    return todays_close_df.index.values.tolist()


def get_next_trading_day_as_index(start_date, hour):
    return pd.to_datetime((start_date + timedelta(days=1)).replace(hour=hour, minute=0, second=0).strftime("%Y %m %d %H:%M:00"))


def get_close_price_on(df, symbol, trade_date):
    data = df.loc[trade_date]
    data = pd.DataFrame(data)
    data = data.rename(columns={data.columns[0]: 'C'})
    todays_close_df = pd.DataFrame(data)
    try:
        return todays_close_df.loc[symbol]['C']
    except Exception:
        return 0


def get_qualified_coins(trade_date, factors_df, factors_count):
    factors_symbols = []
    index = 0
    for factor_df in factors_df:
        s1 = get_todays_top_n_coin(factor_df, trade_date, factors_count[index])
        index = index + 1
        factors_symbols.append(s1)
    symbols = factors_symbols[0]
    for index in range(1, len(factors_symbols)):
        symbols = get_commons(symbols, factors_symbols[index])
    return symbols


def update_coins_performance(coins_performence, todays_trading_symbols):
    symbol_performance = [0, 0]
    for symbol in todays_trading_symbols:
        if symbol in coins_performence:
            symbol_performance = coins_performence[symbol]
        else:
            symbol_performance = [0, 0]
            coins_performence[symbol] = symbol_performance
        symbol_performance[0] = symbol_performance[0] + 1


def update_total_days_count_in_coin_performance(coins_performence, days_count):
    for symbol in coins_performence:
        coins_performence[symbol][1] = days_count


def plot_portfolio_performence(trade_date, df, factors_df, factors_count):
    trades = {}
    trades['c-f'] = [trade_date, 0, 0, 0]
    last_day_trading_symbols = []
    is_first_day_trading = True
    portfolio_performence = []
    end_time = df.index.values.max()
    end_time = (end_time - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
    coins_performence = {}
    days_count = 0
    while trade_date.timestamp() < end_time:
        days_count = days_count + 1
        todays_trading_symbols = get_qualified_coins(trade_date, factors_df, factors_count)
        update_coins_performance(coins_performence, todays_trading_symbols)
        if is_first_day_trading:
            is_first_day_trading = False
            if not len(todays_trading_symbols):
                trades['c-f'][3] = 100000
                continue
            fund = 100000 / len(todays_trading_symbols)
            for symbol in todays_trading_symbols:
                trade = make_entry_symbol(df, trade_date, symbol, [], fund)
                trades[symbol] = trade
#             is_first_day_trading = False
            last_day_trading_symbols = todays_trading_symbols.copy()
            continue
        tmp_trades = trades

        trades = {}
        exit_fund = tmp_trades['c-f'][3]
        todays_exit_symbols = get_not_in_list(todays_trading_symbols, last_day_trading_symbols)
        todays_common_symbols = get_commons(todays_trading_symbols, last_day_trading_symbols)
        todays_new_entry_symbols = get_not_in_list(todays_common_symbols, todays_trading_symbols)

        new_symbol = []
        for symbol_c in todays_common_symbols:
            trade = tmp_trades[symbol_c]
            if trade[4] > 5:
                exit_fund = exit_fund + make_exit_symbol(df, trade_date, symbol_c, trade)
                if symbol_c in todays_trading_symbols:
                    todays_new_entry_symbols.append(symbol_c)
                continue
            trade = make_entry_symbol(df, trade_date, symbol_c, trade, 0)
            trades[symbol_c] = trade

        for exit_symbol in todays_exit_symbols:
            exit_trade = tmp_trades[exit_symbol]
            fund = make_exit_symbol(df, trade_date, exit_symbol, exit_trade)
            exit_fund = exit_fund + fund
        if len(todays_new_entry_symbols):
            new_entry_fund = exit_fund / len(todays_new_entry_symbols)
            exit_fund = 0
            for entry_symbol in todays_new_entry_symbols:
                trade = make_entry_symbol(df, trade_date, entry_symbol, [], new_entry_fund)
                trades[entry_symbol] = trade
                new_symbol.append(entry_symbol)
        tmp_trades['c-f'][3] = exit_fund
        tmp_trades['c-f'][0] = trade_date
        trades['c-f'] = tmp_trades['c-f']
#         if tmp_trades['c-f'][3] > 0:
#             print(f"Uninvested amount as on {tmp_trades['c-f'][0]} is {tmp_trades['c-f'][3]}")
        portfolio_performence.append([get_todays_portfolio_balance(trades), trade_date])
        trade_date = get_next_trading_day_as_index(trade_date, trade_date.hour)
        last_day_trading_symbols = get_joins(todays_common_symbols, new_symbol)
    update_total_days_count_in_coin_performance(coins_performence, days_count)
    print(f'Last Trading Day: {trade_date}. Currently Coins in Portfolio: \n {todays_trading_symbols}')
    return [portfolio_performence, todays_trading_symbols, coins_performence]


def plot_portfolio_for_config(close_df, factors_pct, factors_df):
    total_symbols_count = len(close_df.columns.values.tolist())
    factors_count = []
    for factor_pct in factors_pct:
        factors_count.append(int(total_symbols_count / 100 * factor_pct))

    start_time = factors_df[0].index.values.min()
    start_time_secs = (start_time - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
    start_time = datetime.utcfromtimestamp(start_time_secs)
    trade_date = start_time + timedelta(days=0)
    trade_date = get_next_trading_day_as_index(trade_date, trade_date.hour)
    print(f'Trading Start Date: {trade_date}')
    portfolio = plot_portfolio_performence(trade_date, close_df, factors_df, factors_count)
    portfolio_performence = portfolio[0]
    performance_df = pd.DataFrame(portfolio_performence, columns=['balance', 'time'])
    performance_df.index = pd.DatetimeIndex(performance_df['time'])
    del performance_df['time']
    performance_df.plot(figsize=[18, 10])
#     plt.savefig(f'/tmp/portfolio_{"_".join(str(x) for x in factors_pct)}.png')

    print(f'Current Portfilio Balance: {portfolio_performence[-1][0]}')
    return portfolio[1:]


def get_rsq(x):
    X = x.values.reshape(-1, 1)
    Y = np.arange(1, len(X) + 1).reshape(-1, 1)
    linear_regressor = LinearRegression(fit_intercept=True)
    linear_regressor.fit(Y, X)
    return linear_regressor.score(Y, X)
#     return r2_score(Y, X)


def get_portfolio_version_coins(close_df, factors_df):
    # factors_df = [_7_days_pct_change_df, _days_sumed_pct_change_df, _6_hour_rsq_df, _pure_div_score]
    factors = [25, 10, 10, 99]
    coins_performance = plot_portfolio_for_config(close_df, factors, factors_df)
    coin_performance_df = pd.DataFrame.from_dict(coins_performance[1], orient='index', columns=['Occurrences', 'Total Trading Day'])
    coin_performance_df = coin_performance_df.sort_values(['Occurrences'], ascending=True)
#     coin_performance_df.to_csv(f'/tmp/portfolio_{"_".join(str(x) for x in factors)}_coin_performance.csv')
    s1 = coins_performance[0]
    factors = [25, 99, 50, 7.5]
    coins_performance = plot_portfolio_for_config(close_df, factors, factors_df)
    coin_performance_df = pd.DataFrame.from_dict(coins_performance[1], orient='index', columns=['Occurrences', 'Total Trading Day'])
    coin_performance_df = coin_performance_df.sort_values(['Occurrences'], ascending=True)
#     coin_performance_df.to_csv(f'/tmp/portfolio_{"_".join(str(x) for x in factors)}_coin_performance.csv')
    s2 = coins_performance[0]
    return get_joins(s1, s2)


def run_portfolio_version(close_df, factors_df, _6_hour_resampled_df, day):
    _7_days_pct_change_df = _6_hour_resampled_df.pct_change(periods=day * 4)
    factors_df[0] = _7_days_pct_change_df
    return get_portfolio_version_coins(close_df, factors_df)


def get_coins_price(close_df, symbols):
    df = close_df.iloc[[-1]]
    symbols_price = f"As On {df.index.values[0]}<br>"
    for symbol in symbols:
        symbols_price = f'{symbols_price} {symbol}: ${df.iloc[0][symbol]},'
    return symbols_price


def get_lookback_df(close_df, lookback_symbols):
    close_df = close_df.iloc[[-1]]
    symbols = []
    for lookback in lookback_symbols:
        symbols = get_joins(symbols, lookback_symbols[lookback])
    data = []
    for symbol in symbols:
        data.append([
            symbol,
            close_df.iloc[0][symbol],
            symbol in lookback_symbols[3],
            symbol in lookback_symbols[5]
        ])
    df = pd.DataFrame(data, columns=['Symbol', 'C_Price', '3_Day_LB', '5_Day_LB'])
    return df


def run_algo(close_df):
    _6_hour_resampled_df = close_df.resample('6H').last()
    _6_hour_pct_change = _6_hour_resampled_df.pct_change(periods=1)
    _days_sumed_pct_change_df = _6_hour_pct_change.rolling(window=4).sum()
    _pure_div_score = _6_hour_pct_change.applymap(lambda x: x if x < 0 else 0)
    _pure_div_score = _pure_div_score.rolling(window=4).sum()
    _6_hour_rsq_df = _6_hour_resampled_df.rolling(window=28).apply(get_rsq)
    factors_df = [None, _days_sumed_pct_change_df, _6_hour_rsq_df, _pure_div_score]
    # return run_portfolio_version(close_df, factors_df, _6_hour_resampled_df, 7)
    days = [3, 5]
    msg = ""
    lookback_symbols = {}
    for day in days:
        msg = f'{msg}<br> {day}-day Lookback. <br>Coins Symbol in Portfolio are as below:<br>'
        symbols = run_portfolio_version(close_df, factors_df, _6_hour_resampled_df, day)
        lookback_symbols[day] = symbols
        msg = f'{msg} {get_coins_price(close_df, symbols)}<br><br>'
    lookback_df = get_lookback_df(close_df, lookback_symbols)
    return lookback_df


def delete_unnessecary_columns(df):
    df = df.drop_duplicates(keep='first')
    return df


def convert_symbols_to_columns(df):
    df = df.pivot(columns='symbol', values='C')
    return df


def get_symbols_close(ids):
    connection = __connect__()
    s = ",".join([f'"{s}"' for s in ids])
    sql = f"select * from coingecko_coin_hist_data where symbol in ({s})"
    print(sql)
    df = pd.read_sql(sql, connection)
    connection.close()
    return df

def get_symbols_close_data_df(data_df):
    ids = data_df['Symbol'].unique().tolist()
    df = get_symbols_close(ids)
    df['sym-name']  = df['symbol'] +'###'+df['name']
    df['symbol'] = df['sym-name']
    df['C'] = df['price']
    df = df[['symbol', 'C', 'timestamp_dt'] ].copy()
    df['timestamp_dt'] = pd.to_datetime(df['timestamp_dt'])
    df.index = pd.DatetimeIndex(df['timestamp_dt'])
    df.index = df.index + timedelta(seconds=60)
    df = df[df.index >= datetime(2021, 1, 15)]
    df = delete_unnessecary_columns(df)
    df = convert_symbols_to_columns(df)
    return df


def run_backtest(close_df):
    df = clean_data(close_df)
    print(f'1st Trading Day: {df.index.min()}. Last Trading Day: {df.index.max()}')
    symbols_neg_div_df = run_algo(df)
    return symbols_neg_div_df

def generate_defi_neg_div_score(data_df, start_date):
    close_df = get_symbols_close_data_df(data_df)
    close_df = close_df[close_df.index < start_date].copy()
    symbols_neg_div_df = run_backtest(close_df)
    date = datetime(start_date.year, start_date.month, start_date.day)
    insert_defi_neg_div_score(symbols_neg_div_df, date)

In [50]:
from datetime import timedelta
def generate_neg_div_score(df):
    now = datetime.now()
    start_date =  datetime(now.year, now.month, now.day - 3)
    while start_date < now:
        tmp_df = df[df['date'] < start_date].copy()
        generate_defi_neg_div_score(tmp_df, start_date)
        start_date = datetime(start_date.year, start_date.month, start_date.day) + timedelta(days=1)

In [51]:
def merge_neg_div_score(df):
    generate_neg_div_score(df)
    neg_div_score_df = pd.read_sql_query('select * from defi_neg_div_score', __connect__())
    neg_div_score_df['timestamp_dt'] = pd.to_datetime(neg_div_score_df['timestamp_dt'])
    if 'price' in neg_div_score_df.columns:
        del neg_div_score_df['price']
    tmp_df_2 = pd.merge(df, neg_div_score_df, how = 'left', left_on=['date', 'Symbol', 'Name'], right_on = ['timestamp_dt','symbol','name'])
    del tmp_df_2['symbol']
    del tmp_df_2['name']
    del tmp_df_2['timestamp_dt']
    return tmp_df_2

In [52]:
# df = merge_neg_div_score(df)

In [53]:
# df.columns.tolist()

In [54]:
df

,date,Symbol,Name,Price,Marketcap CMC,Volume CMC,Circulating supply CMC,MAX Supply CMC,Total Supply CMC,TVL Coingecko,...,HECO Chain Ecosystem,Launchpad,Layer 1,Lending/Borrowing,Options,Polkadot Ecosystem,Solana Ecosystem,Stablecoins,Yield Aggregator,Yield Farming
0,2020-12-21,TRB,Tellor,19.889399,32044660.26,28798929.57,1.611143e+06,NaN,1.694832e+06,NaN,...,,,,,,,,,,
1,2020-12-21,PRQ,PARSIQ,0.408170,42607025.18,4924221.66,1.043856e+08,5.000000e+08,5.000000e+08,NaN,...,,,,,,1,1,,,
2,2020-12-21,PEAK,PEAKDEFI,0.285950,21916637.47,277293.69,7.664508e+07,0.000000e+00,4.805654e+08,NaN,...,,,,,,,,,,
3,2020-12-21,HEGIC,Hegic,0.133017,41976242.96,2046318.38,3.155709e+08,3.012010e+09,3.012010e+09,NaN,...,,,,,1,,,,,
4,2020-12-21,CAKE,PancakeSwap,0.476475,37221137.65,960525.97,7.811769e+07,NaN,1.142132e+08,NaN,...,,,,,,,,,,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50407,2021-08-23,YVS,YVS Finance,0.297550,158584.00,94148.00,5.329644e+05,NaN,1.953820e+06,NaN,...,,,,,,,,,,
50408,2021-08-23,AGVE,Agave Token,181.930000,5057747.00,12547.55,2.779990e+04,1.000000e+05,1.000000e+05,NaN,...,,,,,,,,,,
50409,2021-08-23,SWAMP,Swampy,1.860000,3720000.00,106993.00,0.000000e+00,2.000000e+06,2.000000e+06,41151471.0,...,,,,,,,,,,
50410,2021-08-23,POOL,PoolTogether,16.250000,43504329.00,286218.00,2.677128e+06,1.000000e+07,1.000000e+07,184096476.0,...,,,,,,,,,,
50411,2021-08-23,SCREAM,Scream,14.330000,28660000.00,127952.00,0.000000e+00,2.000000e+06,2.000000e+06,25369377.0,...,,,,,,,,,,

## Farms And Pool

### Append the most stable and non stable farm and pool rates.

In [55]:
stable_coins = "USDT, USDC, DAI, BUSD, SUSD, UST, TUSD".split(",")


def get_stable_coin(pair1, pair2):
    if pair1 in stable_coins:
        return pair1
    elif pair2 in stable_coins:
        return pair2
    else:
        return'NA'


def get_pancakswap_and_raydium_farm_data():
    pancakswap_farm_df = pd.read_sql_query('select * from pancakswap_farm_pool_data;', __connect__())
    pancakswap_farm_df = pancakswap_farm_df[['timestamp_dt', 'pair1', 'pair2', 'pool_rate', 'farm_payment', 'where', 'includes_stablecoin']]
    raydium_farm_df = pd.read_sql_query('select * from raydium_farm_pool_data;', __connect__())
    merged_df = pancakswap_farm_df.append(raydium_farm_df)
    return merged_df


def get_cmc_and_liqudityfolio_pool_and_farm_data_df():
    cmc_farm_df = pd.read_sql_query('select * from cmc_farming_yield;', __connect__())
    cmc_farm_df = cmc_farm_df[['timestamp_dt', 'pair1', 'pair2', 'pool_rate', 'farm_payment', 'where', 'includes_stablecoin']]
    cmc_farm_df = cmc_farm_df[cmc_farm_df['where'].isin(['PancakeSwap', 'SushiSwap', 'BakeryToken', 'SUN'])]
    liquidityfolio_pool_df = pd.read_sql_query('select * from liquidityfolio_pool;', __connect__())
    liquidityfolio_pool_df = liquidityfolio_pool_df[liquidityfolio_pool_df['where'] == 'Uniswap']
    liquidityfolio_pool_df = liquidityfolio_pool_df[['timestamp_dt', 'pair1', 'pair2', 'pool_rate', 'farm_payment', 'where', 'includes_stablecoin']]
    liquidityfolio_pool_df['pool_rate'] = liquidityfolio_pool_df['pool_rate'] * 1200
    merged_df = cmc_farm_df.append(liquidityfolio_pool_df)
    return merged_df


def get_farm_and_pool_merged_data_df():
    cmc_and_liqudityfolio_pool_and_farm_data_df = get_cmc_and_liqudityfolio_pool_and_farm_data_df()
    pancakswap_and_raydium_farm_df = get_pancakswap_and_raydium_farm_data()
    merged_df = cmc_and_liqudityfolio_pool_and_farm_data_df.append(pancakswap_and_raydium_farm_df)
    merged_df['pool_rate'] = merged_df['pool_rate']/100
    return merged_df
    

def get_pool_rates(merged_eth_df, stable, defi_symbol):
    data = [np.nan] * 4
    merged_eth_df = merged_eth_df[(merged_eth_df['includes_stablecoin'] == stable) & (merged_eth_df['farm_payment'].isnull())]
    if not merged_eth_df.empty:
        scenario_1 = merged_eth_df.sort_values(['pool_rate']).iloc[-1]
#         print([defi_symbol, merged_eth_df.shape])
        stable_coin = get_stable_coin(scenario_1['pair1'], scenario_1['pair2'])
        other_pair = scenario_1['pair2'] if scenario_1['pair1'] == defi_symbol else scenario_1['pair1']
        data = [other_pair, scenario_1['pool_rate'], stable_coin, scenario_1['where']]
    return data


def get_farm_rates(merged_eth_df, stable, defi_symbol):
    data = [np.nan] * 5
    merged_eth_df = merged_eth_df[(merged_eth_df['includes_stablecoin'] == stable) & (merged_eth_df['farm_payment'].notnull())]
    if not merged_eth_df.empty:
        scenario_1 = merged_eth_df.sort_values(['pool_rate']).iloc[-1]
        stable_coin = get_stable_coin(scenario_1['pair1'], scenario_1['pair2'])
        other_pair = scenario_1['pair2'] if scenario_1['pair1'] == defi_symbol else scenario_1['pair1']
        data = [other_pair, scenario_1['pool_rate'], stable_coin, scenario_1['where'], scenario_1['farm_payment']]
    return data


def get_farm_and_pool_rates(merged_df):
    data = [np.nan] * 18
    defi_symbol = merged_df['defi_symbol'].max()
    merged_eth_df = merged_df[(merged_df['pair1'] == defi_symbol) | (merged_df['pair2'] == defi_symbol)].copy().reset_index(drop=True)
    if not merged_eth_df.empty:
        scenario_1_data = get_pool_rates(merged_eth_df, True, defi_symbol)
        scenario_2_data = get_pool_rates(merged_eth_df, False, defi_symbol)
        scenario_3_data = get_farm_rates(merged_eth_df, True, defi_symbol)
        scenario_4_data = get_farm_rates(merged_eth_df, False, defi_symbol)
        data = []
        data.extend(scenario_1_data)
        data.extend(scenario_2_data)
        data.extend(scenario_3_data)
        data.extend(scenario_4_data)
    r_data = [defi_symbol]
    r_data.extend(data)
    return r_data


def get_stable_non_stable_pool_rates(merged_eth_df):
    grouped_df = merged_eth_df.sort_values('pool_rate').reset_index(drop=True).groupby('timestamp_dt')
    nd_list = grouped_df.apply(lambda x: get_farm_and_pool_rates(x))
    if len(nd_list) > 0:
        index = nd_list.index[0]
        data = [index]
        data.extend(nd_list[0])
        return data
    return None


def get_farm_and_pool_data_symbols(merged_df, defi_symbols):
    data = []
    for defi_symbol in defi_symbols:
        merged_eth_df = merged_df[(merged_df['pair1'] == defi_symbol) | (merged_df['pair2'] == defi_symbol)].copy().reset_index(drop=True)
        merged_eth_df['defi_symbol'] = defi_symbol
        tmp = get_stable_non_stable_pool_rates(merged_eth_df)
        if tmp:
            data.append(tmp)
    return data


def merge_farm_and_pool_data(data_df):
    defi_symbols = data_df['Symbol'].unique().tolist()
    merged_df = get_farm_and_pool_merged_data_df()
    farm_and_pool_data = get_farm_and_pool_data_symbols(merged_df, defi_symbols)
    columns = ['date', 'symbol', 'top_stable_pool_pair', 'top_stable_pool_rate', 'top_stable_pool_coin', 'top_stable_pool_where', 'top_nonstable_pool_pair', 'top_nonstable_pool_rate', 'top_nonstable_pool_coin', 'top_nonstable_pool_where', 'top_stable_farm_pair', 'top_stable_farm_rate', 'top_stable_farm_coin', 'top_stable_farm_where', 'top_stable_farm_reward', 'top_nonstable_farm_pair', 'top_nonstable_farm_rate', 'top_nonstable_farm_coin', 'top_nonstable_farm_where', 'top_nonstable_farm_reward']
    farm_and_pool_df = pd.DataFrame(farm_and_pool_data, columns=columns)
    tmp_df_4 = pd.merge(data_df, farm_and_pool_df, how='left', left_on=['date', 'Symbol'], right_on=['date', 'symbol'])
    del tmp_df_4['symbol']
    tmp_df_5 = tmp_df_4.set_index(tmp_df_4['date'])
    columns = ['top_stable_pool_pair', 'top_stable_pool_rate', 'top_stable_pool_coin', 'top_stable_pool_where', 'top_nonstable_pool_pair', 'top_nonstable_pool_rate', 'top_nonstable_pool_coin', 'top_nonstable_pool_where', 'top_stable_farm_pair', 'top_stable_farm_rate', 'top_stable_farm_coin', 'top_stable_farm_where', 'top_stable_farm_reward', 'top_nonstable_farm_pair', 'top_nonstable_farm_rate', 'top_nonstable_farm_coin', 'top_nonstable_farm_where', 'top_nonstable_farm_reward']
    for column in columns:
        tmp_df_5[column] = tmp_df_5.groupby('Symbol')[column].transform(lambda x: x.ffill())
    tmp_df_5.reset_index(drop=True)
    return tmp_df_5

In [56]:
merged_df_ = get_farm_and_pool_merged_data_df()
merged_df_[merged_df_['where'] == 'balancer']

Empty DataFrame
Columns: [timestamp_dt, pair1, pair2, pool_rate, farm_payment, where, includes_stablecoin, tvl]
Index: []

In [57]:
df = merge_farm_and_pool_data(df)
df[df['date'] == pd.to_datetime("4/29/2021")]

KeyboardInterrupt:

In [ ]:
df[df['date'] == pd.to_datetime("5/1/2021")]['top_nonstable_farm_pair'].unique()

In [ ]:
# df.columns.tolist()

## Saving to csv File

In [ ]:
df.shape

In [ ]:
df.to_csv('coingecko_data_ratios_and_percentages.csv', index = False)

In [ ]:
df.date.max()

In [ ]:
df[df['Symbol'] == 'AAVE'][['Users life-to-date duneanlytics','date']]

In [ ]:
df

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
df = df.sort_values(['date','Symbol', 'Name'])

(df['Symbol'] + "____" + df['Name']).unique().tolist()

In [ ]:
df[df['Symbol'] == 'BASK']

# QA

In [ ]:
def get_all_mapping_symbols(mapping_table_name, data_table_name, mapping_source_col_name, data_table_col_name):
    sql = f'select * from {mapping_table_name} where symbol != "" and {mapping_source_col_name} in (select distinct {data_table_col_name} from {data_table_name});'
#     print(sql)
    symbols = pd.read_sql_query(sql, __connect__())
    return symbols

def get_datasource_all_tracked_coin_names(data_table_name, data_table_col_name):
    sql = f'select distinct {data_table_col_name} from {data_table_name};'
#     print(sql)
    symbols = pd.read_sql_query(sql, __connect__())
    return symbols[data_table_col_name].values.tolist()

def qa_data_source(df, mapping_table_name, data_table_name, mapping_source_col_name, data_table_col_name):
    source_all_coin_names = get_datasource_all_tracked_coin_names(data_table_name, data_table_col_name)
    print(source_all_coin_names)
    print(len(source_all_coin_names))
    mapping_symbol = get_all_mapping_symbols(mapping_table_name, data_table_name, mapping_source_col_name, data_table_col_name)
    print("Total Mappings: ", mapping_symbol.shape[0])
    name_in_cmc = mapping_symbol['name_in_cmc'].values.tolist()
    captured_names_df = df[df['Name'].isin(name_in_cmc)]
    captured_Names = captured_names_df['Name'].unique().tolist()
    print("Captured Names", len(captured_Names))
    uncaptured_names = [x for x in name_in_cmc if x not in captured_Names]
    print("Uncaptured Names: ", uncaptured_names)
    print(mapping_symbol[mapping_symbol['name_in_cmc'].isin(uncaptured_names)])
    data_symbol_group = captured_names_df.groupby(['Symbol'])
    data_df = data_symbol_group.agg({'date':['max', 'min']}).reset_index()
    print(data_df)
    print("Max Date", data_df['date']['max'].unique())

In [ ]:
qa_data_source(df, 'tt_symbols', 'tt_coin_metrics_v2', 'name_in_tt', 'name')

In [ ]:
qa_data_source(df, 'debank_symbols3', 'debank_project_tvl', 'name_in_debank', 'project')

In [ ]:
qa_data_source(df, 'debank_symbols3', 'debank_project_dex', 'name_in_debank', 'project')

In [ ]:
qa_data_source(df, 'debank_symbols3', 'debank_project_lendings', 'name_in_debank', 'symbol')

In [ ]:
qa_data_source(df, 'defi_symbols', 'defi_project_tvl', 'name_in_defi', 'project')

In [ ]:
qa_data_source(df, 'defistation_symbols', 'defistation_data', 'name_in_defistation', 'name')

In [ ]:
qa_data_source(df, 'dune_symbols', 'dune_total_users_analysis2', 'name_in_duneanalytics', 'symbol')

In [ ]:
qa_data_source(df, 'solana_symbols', 'solanaprojects_data', 'name_in_solana', 'name')

In [ ]:
df[df['Symbol'] == 'NMR']