In [1]:
from selenium import webdriver
import time
from bs4 import BeautifulSoup as soup
import pandas as pd
from selenium.webdriver.common.keys import Keys
import  re

In [16]:
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
options.add_argument('--incognito')
options.add_argument("no-sandbox")
options.add_argument("--disable-gpu")
options.add_argument("--window-size=1200,900")
options.add_argument("--disable-dev-shm-usage")
options.add_argument('--headless')
options.add_argument("start-maximized")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)
options.add_argument("--disable-blink-features")
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_argument("--enable-javascript")
browser = webdriver.Chrome("chromedriver", options=options)

# IE_path = 'D:\selds\IEDriver\IEDriverServer'
# options = webdriver.IeOptions()
# browser = webdriver.Ie(IE_path, options=options)

In [34]:
def extract_data(page_source):
    df_c =  pd.DataFrame(columns = ['name','earned', 'apr'])
    
    page_soup = soup(page_source, "html.parser")
    table = page_soup.findAll("table")#, {"class": "sc-hRMXGO hbbpxV"})
    rows =  table[0].tbody.findAll("tr")
    for row in rows: 
        divs = row.findAll("div", {"color": "text"})
        name = divs[0].text
        earned = row.find_all("span")[0].text
        apr = row.find_all(text=re.compile('%'))[0]
        df_c.at[len(df_c)] = [name,earned,apr]
    return df_c

extract_data(page_source)

          name earned      apr
0     CAKE-BNB      0   61.19%
1     BUSD-BNB      0   21.32%
2    MCOIN-UST      0  542.61%
3      WIN-BNB      0  144.04%
4      TRX-BNB      0   60.64%
..         ...    ...      ...
115   LINK-BNB      0   33.88%
116    EOS-BNB      0   19.14%
117    DOT-BNB      0   25.77%
118   BAND-BNB      0   65.06%
119    ADA-BNB      0   28.24%

[120 rows x 3 columns]

In [17]:
browser.get("https://pancakeswap.finance/farms")
time.sleep(5)
prev_len = 0
curr_len = 100
count = 0
while count<5:
    print(curr_len)
    time.sleep(3)
    page_source = browser.page_source
    #df = extract_data(page_source)
    time.sleep(3)
    #print(df)
    body = browser.find_element_by_css_selector('body')
    body.send_keys(Keys.PAGE_DOWN)
    time.sleep(1)
    body.send_keys(Keys.PAGE_DOWN)
    curr_len = len(page_source)
    if curr_len == prev_len:
        count = count+1
    else:
        count = 0
    prev_len = curr_len

100
63316
79344
95314
111278
127214
143183
159146
159454
175386
191332
207245
207320
207320
207320
207320
207320
207314
207314
207314
207314
207314

In [35]:
page_source = browser.page_source
df = extract_data(page_source)
df

          name earned      apr
0     CAKE-BNB      0    61.1%
1     BUSD-BNB      0   21.28%
2    MCOIN-UST      0  565.08%
3      WIN-BNB      0  144.07%
4      TRX-BNB      0   60.61%
..         ...    ...      ...
115   LINK-BNB      0   33.86%
116    EOS-BNB      0   19.19%
117    DOT-BNB      0   25.73%
118   BAND-BNB      0   65.02%
119    ADA-BNB      0    28.2%

[120 rows x 3 columns]

In [36]:
df.to_csv('Pancakeswap_Farms.csv',index=None)

In [37]:
browser.close()