In [1]:
from selenium import webdriver
import time
from bs4 import BeautifulSoup as soup
import pandas as pd
from selenium.webdriver.common.keys import Keys
import  re

In [2]:
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
#options.add_argument('--incognito')
#options.add_argument('--headless')
options.add_argument("start-maximized")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)
options.add_argument("--disable-blink-features")
options.add_argument("--disable-blink-features=AutomationControlled")
browser = webdriver.Chrome("chromedriver", options=options)

# IE_path = 'D:\selds\IEDriver\IEDriverServer'
# options = webdriver.IeOptions()
# browser = webdriver.Ie(IE_path, options=options)

In [3]:
def extract_data(page_source):
    df_c =  pd.DataFrame(columns = ['name','earned', 'apr', 'liquidity', 'multiplier'])
    
    page_soup = soup(page_source, "html.parser")
    table = page_soup.findAll("table")#, {"class": "sc-hRMXGO hbbpxV"})
    #heads = table[0].thead.tr.findAll("th")
    rows =  table[0].tbody.findAll("tr")
    for row in rows: 
        divs = row.findAll("div", {"color": "text"})
        name = divs[0].text
        #name
        earned = row.find_all("span")[0].text
        #earned
        apr = row.find_all(text=re.compile('%'))[0]
        #apr
        liq = divs[1].text
        #liq
        mul = row.find_all(text=re.compile('x'))[0]
        #mul
        #print(f'{name} {earned} {apr} {liq} {mul}')
        df_c.at[len(df_c)] = [name,earned,apr,liq,mul]
    return df_c

In [4]:
time.sleep(5)
browser.get("https://pancakeswap.finance/farms")
prev_len = 0
curr_len = 100
count = 0
while count<5:
    print(curr_len)
    time.sleep(3)
    page_source = browser.page_source
    #df = extract_data(page_source)
    time.sleep(3)
    #print(df)
    body = browser.find_element_by_css_selector('body')
    body.send_keys(Keys.PAGE_DOWN)
    time.sleep(1)
    body.send_keys(Keys.PAGE_DOWN)
    curr_len = len(page_source)
    if curr_len == prev_len:
        count = count+1
    else:
        count = 0
    prev_len = curr_len

100
100
126072
126072
126072
126072
126072
126072
126072
126072
126072
126072
180813
180813
289905
289905
344477
344477
399060
399060
399400
399400
453985
453985
508553
508553
563100
563100
599492
599492
599604
599604
599604
599604
599601
599601
599601
599601
599601
599601
599601
599601
599601
599601

In [5]:
page_source = browser.page_source
df = extract_data(page_source)
df

           name earned      apr       liquidity multiplier
0      CAKE-BNB      0   71.42%  $1,625,699,644        40x
1      BUSD-BNB      0    24.3%    $955,493,631         8x
2      PNT-PBTC      0  798.65%      $7,269,173         2x
3    XMARK-BUSD      0  378.14%     $15,352,818         2x
4     BTCB-BUSD      0   19.75%    $147,009,261         1x
..          ...    ...      ...             ...        ...
111    LINK-BNB      0   33.85%     $85,745,936         1x
112     EOS-BNB      0   22.35%     $12,985,073       0.1x
113     DOT-BNB      0    29.4%     $98,737,336         1x
114    BAND-BNB      0   69.31%     $41,878,368         1x
115     ADA-BNB      0   28.74%     $50,495,553       0.5x

[116 rows x 5 columns]

           name earned      apr       liquidity multiplier
0      CAKE-BNB      0   71.42%  $1,625,699,644        40x
1      BUSD-BNB      0    24.3%    $955,493,631         8x
2      PNT-PBTC      0  798.65%      $7,269,173         2x
3    XMARK-BUSD      0  378.14%     $15,352,818         2x
4     BTCB-BUSD      0   19.75%    $147,009,261         1x
..          ...    ...      ...             ...        ...
111    LINK-BNB      0   33.85%     $85,745,936         1x
112     EOS-BNB      0   22.35%     $12,985,073       0.1x
113     DOT-BNB      0    29.4%     $98,737,336         1x
114    BAND-BNB      0   69.31%     $41,878,368         1x
115     ADA-BNB      0   28.74%     $50,495,553       0.5x

[116 rows x 5 columns]

In [6]:
df.to_csv('Pancakeswap_Farms.csv',index=None)

In [7]:
browser.close()