### https://trello.com/c/xjAkL36o/54-merge-manual-raydium-and-pancakeswap-into-yield-report

In [10]:
import requests
import pandas as pd
import pymysql
import numpy as np
from datetime import datetime
import traceback2


stable_coins = "USDT, USDC, DAI, BUSD, SUSD, UST, TUSD".split(",")

In [9]:
def __connect__():
    db_user = 'coin'
    db_password = 'dragonstone#123'
    db_name = 'master_data'
    db_host = 'localhost'
    return pymysql.connect(
        unix_socket=None,
        host=db_host,
        user=db_user,
        password=db_password,
        db=db_name,
        charset='latin1',
        cursorclass=pymysql.cursors.DictCursor)


def get_cursor(connection):
    if connection is None:
        connection = __connect__()
    connection.ping(reconnect=True)
    return connection.cursor()

In [12]:
pancakswap_df = pd.read_csv('PancakeSwap_manual.csv')
raydium_df = pd.read_csv('Raydium_manual.csv')
pancakswap_df['includes_stablecoin'] = (pancakswap_df['Pair_1'].isin(stable_coins)) | (pancakswap_df['Pair_2'].isin(stable_coins))
raydium_df['includes_stablecoin'] = (raydium_df['Pair_1'].isin(stable_coins)) | (raydium_df['Pair_2'].isin(stable_coins))

In [13]:
raydium_df

,Date,Pair_1,Pair_2,Where,Farm_payment,Pool_rate,includes_stablecoin
0,5/3/2021,RAY,USDT,Raydium,RAY,190.37,True
1,5/3/2021,RAY,USDC,Raydium,RAY,176.53,False
2,5/3/2021,RAY,SRM,Raydium,RAY,116.91,False
3,5/3/2021,RAY,SOL,Raydium,RAY,88.81,False
4,5/3/2021,RAY,ETH,Raydium,RAY,121.54,False
5,5/3/2021,FIDA,RAY,Raydium,FIDA-RAY,119.89,False
6,5/3/2021,OXY,RAY,Raydium,OXY-RAY,98.18,False
7,5/3/2021,MAPS,RAY,Raydium,MAPS-RAY,114.11,False
8,5/3/2021,KIN,RAY,Raydium,KIN-RAY,185.63,False
9,5/3/2021,COPE,USDC,Raydium,COPE,548.96,False
10,5/3/2021,STEP,USDC,Raydium,STEP,1410.22,False
11,5/3/2021,MEDIA,USDC,Raydium,MEDIA,417.02,False

In [14]:
pancakswap_df

,Date,Pair_1,Pair_2,Where,Farm_payment,Pool_rate,pool_tvl,includes_stablecoin
0,5/3/2021,CAKE,BNB,PancakeSwap,CAKE,74.33,1718847,False
1,5/3/2021,BUSD,BNB,PancakeSwap,CAKE,25.61,997816,False
2,5/3/2021,ETH,BNB,PancakeSwap,CAKE,12.04,529096265,False
3,5/3/2021,USDT,BUSD,PancakeSwap,CAKE,13.49,472049664,True
4,5/3/2021,BTCB,BNB,PancakeSwap,CAKE,15.13,421808142,False
5,5/3/2021,USDT,BNB,PancakeSwap,CAKE,18.78,338604357,True
6,5/3/2021,BUNNY,BNB,PancakeSwap,CAKE,26.66,118972005,False
7,5/3/2021,USDC,BUSD,PancakeSwap,CAKE,16.59,95709301,False
8,5/3/2021,UNI,BNB,PancakeSwap,CAKE,33.59,94300563,False
9,5/3/2021,BTCB,BUSD,PancakeSwap,CAKE,35.05,90762920,False
10,5/3/2021,DAI,BUSD,PancakeSwap,CAKE,17.81,89146030,False
11,5/3/2021,DOT,BNB,PancakeSwap,CAKE,35.89,88554086,False
12,5/3/2021,VAI,BUSD,PancakeSwap,CAKE,18.40,86377401,False
13,5/3/2021,LINK,BNB,PancakeSwap,CAKE,37.86,84067272,False
14,5/3/2021,XRP,BNB,PancakeSwap,CAKE,45.77,69524878,False
15,5/3/2021,UST,BUSD,PancakeSwap,CAKE,23.12,68807199,False
16,5/3/2021,XVS,BNB,PancakeSwap,CAKE,60.22,52867925,False
17,5/3/2021,ALPHA,BNB,PancakeSwap,CAKE,62.69,50526237,False
18,5/3/2021,ADA,BNB,PancakeSwap,CAKE,31.79,49820881,False
19,5/3/2021,TBTC,BTCB,PancakeSwap,CAKE,76.30,41513892,False
20,5/3/2021,ALPACA,BUSD,PancakeSwap,CAKE,79.86,39753759,False
21,5/3/2021,COMP,ETH,PancakeSwap,CAKE,8.05,39508261,False
22,5/3/2021,BAND,BNB,PancakeSwap,CAKE,81.66,38923370,False
23,5/3/2021,PBTC,BNB,PancakeSwap,CAKE,84.75,37568791,False
24,5/3/2021,HELMET,BNB,PancakeSwap,CAKE,43.22,36835143,False
25,5/3/2021,SFP,BND,PancakeSwap,CAKE,91.42,34826155,False
26,5/3/2021,TKO,BNB,PancakeSwap,CAKE,98.78,32317331,False
27,5/3/2021,ZIL,BNB,PancakeSwap,CAKE,105.23,30249830,False
28,5/3/2021,TPT,BUSD,PancakeSwap,CAKE,108.60,29338153,False
29,5/3/2021,SUSHI,ETH,PancakeSwap,CAKE,33.67,28386230,False
30,5/3/2021,REEF,BNB,PancakeSwap,CAKE,112.75,28258296,False
31,5/3/2021,SXP,BNB,PancakeSwap,CAKE,66.54,23931527,False

In [ ]:
def insert_pancakswap_data_df(df):
    connection = __connect__()
    cursor = get_cursor(connection)
    for i, row in df.iterrows():
        dt = row["date"].timestamp()
        try:
            pair2 = row["pair2"] if row["pair2"] else ' '
            print(row["date"], row["pair1"], pair2, row["Pool_rate"], row["pool_tvl"], row["Farm_payment"], row["Where"], row["includes_stablecoin"])
            sql = "INSERT INTO `pancakswap_pool_data` (`timestamp_dt`, `pair1`,`pair2`,`pool_rate`,`pool_size`,`farm_payment`,`where`,`includes_stablecoin`) VALUES (FROM_UNIXTIME(%s), %s, %s, %s, %s, %s, %s, %s)"
            cursor.execute(sql, (dt, row['name'], row["pair1"], pair2, row["pool_rate"], row["pool_size"], row["farm_payment"], row["where"], row["includes_stablecoin"]))
        except Exception as e:
            print(e)
    connection.commit()
    cursor.close()
    connection.close()


def insert_raydium_data_df(df):
    df = df.astype(object).where(pd.notnull(df), None)
    connection = __connect__()
    cursor = get_cursor(connection)
    for i, row in df.iterrows():
        try:
            dt = row["date"].timestamp()
            symbol = row['symbol'] if row['symbol'] else ' '
            print(row['date'], row['name'], symbol, row['price'], row['p_pct_change'], row['tvl'], row['tags'])
            sql = """
            INSERT INTO `solonaprojects_data` (`timestamp_dt`, `name`, `token`, `price`, `p_pct_change_24h`, `tvl`, `tags`) VALUES (FROM_UNIXTIME(%s), %s, %s, %s, %s, %s, %s)
            ON DUPLICATE KEY UPDATE
            `price` = VALUES(price),
            `p_pct_change_24h` = VALUES(p_pct_change_24h),
            `tvl` = VALUES(tvl),
            `tags` = VALUES(tags)
            """
            cursor.execute(sql, (dt , row['name'], symbol, row['price'], row['p_pct_change'], row['tvl'], row['tags']))
        except Exception as e:
            print('exception')
            print(traceback2.format_exc())
            print(e)
    connection.commit()
    cursor.close()
    connection.close()